/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.mantenimiento.swagger;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Código identificador del canal en sistema
 */
public enum CodigosCanales {
  
  BANCA_POR_INTERNET("BANCA_POR_INTERNET"),
  
  APP_BANCA_MOVIL("APP_BANCA_MOVIL"),
  
  BRANCH_AGENCIAS("BRANCH_AGENCIAS"),
  
  AFP_NET("AFP_NET"),
  
  KASNET_AGENTE_CORRESPONSAL("KASNET_AGENTE_CORRESPONSAL"),
  
  WESTERN_UNION_AGENTE_CORRESPONSAL("WESTERN_UNION_AGENTE_CORRESPONSAL"),
  
  ATM_CAJEROS_AUTOMATICOS("ATM_CAJEROS_AUTOMATICOS"),
  
  BANCA_INTERNET_PERSONA_NATURAL("BANCA_INTERNET_PERSONA_NATURAL"),
  
  BANCA_INTERNET_PERSONA_JURIDICA("BANCA_INTERNET_PERSONA_JURIDICA"),
  
  APP_BANCA_MOVIL_PERSONA_NATURAL("APP_BANCA_MOVIL_PERSONA_NATURAL"),
  
  APP_BANCA_MOVIL_PERSONA_JURIDICA("APP_BANCA_MOVIL_PERSONA_JURIDICA"),
  
  E_IBS("E-IBS"),
  
  BACKOFFICE("BACKOFFICE"),
  
  APP_CRM("APP_CRM"),
  
  PORTAL_PUBLICO("PORTAL_PUBLICO"),
  
  BANCA_TELEFONICA("BANCA_TELEFONICA"),
  
  IBS("IBS");

  private String value;

  CodigosCanales(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static CodigosCanales fromValue(String text) {
    for (CodigosCanales b : CodigosCanales.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

