/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * AhorroVuelto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class AhorroVuelto   {
  @JsonProperty("montoRedondeo")
  private Double montoRedondeo = null;

  @JsonProperty("codigoMoneda")
  private CodigosMonedas codigoMoneda = null;

  @JsonProperty("envioNotificaciones")
  private Boolean envioNotificaciones = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("canal")
  private CodigosCanales canal = null;

  public AhorroVuelto montoRedondeo(Double montoRedondeo) {
    this.montoRedondeo = montoRedondeo;
    return this;
  }

  /**
   * Valor vuelto
   * @return montoRedondeo
   **/
  @JsonProperty("montoRedondeo")
  @ApiModelProperty(value = "Valor vuelto")
  public Double getMontoRedondeo() {
    return montoRedondeo;
  }

  public void setMontoRedondeo(Double montoRedondeo) {
    this.montoRedondeo = montoRedondeo;
  }

  public AhorroVuelto codigoMoneda(CodigosMonedas codigoMoneda) {
    this.codigoMoneda = codigoMoneda;
    return this;
  }

  /**
   * Get codigoMoneda
   * @return codigoMoneda
   **/
  @JsonProperty("codigoMoneda")
  @ApiModelProperty(value = "")
  public CodigosMonedas getCodigoMoneda() {
    return codigoMoneda;
  }

  public void setCodigoMoneda(CodigosMonedas codigoMoneda) {
    this.codigoMoneda = codigoMoneda;
  }

  public AhorroVuelto envioNotificaciones(Boolean envioNotificaciones) {
    this.envioNotificaciones = envioNotificaciones;
    return this;
  }

  /**
   * Envio de notificaciones
   * @return envioNotificaciones
   **/
  @JsonProperty("envioNotificaciones")
  @ApiModelProperty(value = "Envio de notificaciones")
  public Boolean isEnvioNotificaciones() {
    return envioNotificaciones;
  }

  public void setEnvioNotificaciones(Boolean envioNotificaciones) {
    this.envioNotificaciones = envioNotificaciones;
  }

  public AhorroVuelto status(String status) {
    this.status = status;
    return this;
  }

  /**
   * Status
   * @return status
   **/
  @JsonProperty("status")
  @ApiModelProperty(value = "Status")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public AhorroVuelto canal(CodigosCanales canal) {
    this.canal = canal;
    return this;
  }

  /**
   * Get canal
   * @return canal
   **/
  @JsonProperty("canal")
  @ApiModelProperty(value = "")
  public CodigosCanales getCanal() {
    return canal;
  }

  public void setCanal(CodigosCanales canal) {
    this.canal = canal;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AhorroVuelto ahorroVuelto = (AhorroVuelto) o;
    return Objects.equals(this.montoRedondeo, ahorroVuelto.montoRedondeo) &&
        Objects.equals(this.codigoMoneda, ahorroVuelto.codigoMoneda) &&
        Objects.equals(this.envioNotificaciones, ahorroVuelto.envioNotificaciones) &&
        Objects.equals(this.status, ahorroVuelto.status) &&
        Objects.equals(this.canal, ahorroVuelto.canal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(montoRedondeo, codigoMoneda, envioNotificaciones, status, canal);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AhorroVuelto {\n");
    
    sb.append("    montoRedondeo: ").append(toIndentedString(montoRedondeo)).append("\n");
    sb.append("    codigoMoneda: ").append(toIndentedString(codigoMoneda)).append("\n");
    sb.append("    envioNotificaciones: ").append(toIndentedString(envioNotificaciones)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    canal: ").append(toIndentedString(canal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

