/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Sierve para almacenar las informacionaes de del archivo BxI
 */
@ApiModel(description = "Sierve para almacenar las informacionaes de del archivo BxI")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class ArchivoBaseBanbif   {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("nombre")
  private String nombre = null;

  @JsonProperty("producto")
  private Producto producto = null;

  @JsonProperty("camposPosicionales")
  private List<CampoPosicionalArchivo> camposPosicionales = null;

  public ArchivoBaseBanbif id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Identificador del archivo
   * @return id
   **/
  @JsonProperty("id")
  @ApiModelProperty(value = "Identificador del archivo")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ArchivoBaseBanbif nombre(String nombre) {
    this.nombre = nombre;
    return this;
  }

  /**
   * nombre del archivo
   * @return nombre
   **/
  @JsonProperty("nombre")
  @ApiModelProperty(value = "nombre del archivo")
  public String getNombre() {
    return nombre;
  }

  public void setNombre(String nombre) {
    this.nombre = nombre;
  }

  public ArchivoBaseBanbif producto(Producto producto) {
    this.producto = producto;
    return this;
  }

  /**
   * Get producto
   * @return producto
   **/
  @JsonProperty("producto")
  @ApiModelProperty(value = "")
  public Producto getProducto() {
    return producto;
  }

  public void setProducto(Producto producto) {
    this.producto = producto;
  }

  public ArchivoBaseBanbif camposPosicionales(List<CampoPosicionalArchivo> camposPosicionales) {
    this.camposPosicionales = camposPosicionales;
    return this;
  }

  public ArchivoBaseBanbif addCamposPosicionalesItem(CampoPosicionalArchivo camposPosicionalesItem) {
    if (this.camposPosicionales == null) {
      this.camposPosicionales = new ArrayList<CampoPosicionalArchivo>();
    }
    this.camposPosicionales.add(camposPosicionalesItem);
    return this;
  }

  /**
   * Get camposPosicionales
   * @return camposPosicionales
   **/
  @JsonProperty("camposPosicionales")
  @ApiModelProperty(value = "")
  public List<CampoPosicionalArchivo> getCamposPosicionales() {
    return camposPosicionales;
  }

  public void setCamposPosicionales(List<CampoPosicionalArchivo> camposPosicionales) {
    this.camposPosicionales = camposPosicionales;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArchivoBaseBanbif archivoBaseBanbif = (ArchivoBaseBanbif) o;
    return Objects.equals(this.id, archivoBaseBanbif.id) &&
        Objects.equals(this.nombre, archivoBaseBanbif.nombre) &&
        Objects.equals(this.producto, archivoBaseBanbif.producto) &&
        Objects.equals(this.camposPosicionales, archivoBaseBanbif.camposPosicionales);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, nombre, producto, camposPosicionales);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArchivoBaseBanbif {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nombre: ").append(toIndentedString(nombre)).append("\n");
    sb.append("    producto: ").append(toIndentedString(producto)).append("\n");
    sb.append("    camposPosicionales: ").append(toIndentedString(camposPosicionales)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

