/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * Sierve para almacenar las informacionaes de los campos posicionales del archivo base banbif
 */
@ApiModel(description = "Sierve para almacenar las informacionaes de los campos posicionales del archivo base banbif")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class CampoPosicionalArchivo   {
  @JsonProperty("nombre")
  private String nombre = null;

  @JsonProperty("posicionInicial")
  private BigDecimal posicionInicial = null;

  @JsonProperty("posicionFinal")
  private BigDecimal posicionFinal = null;

  public CampoPosicionalArchivo nombre(String nombre) {
    this.nombre = nombre;
    return this;
  }

  /**
   * nombre del campo
   * @return nombre
   **/
  @JsonProperty("nombre")
  @ApiModelProperty(value = "nombre del campo")
  public String getNombre() {
    return nombre;
  }

  public void setNombre(String nombre) {
    this.nombre = nombre;
  }

  public CampoPosicionalArchivo posicionInicial(BigDecimal posicionInicial) {
    this.posicionInicial = posicionInicial;
    return this;
  }

  /**
   * Posición inicial del campo
   * @return posicionInicial
   **/
  @JsonProperty("posicionInicial")
  @ApiModelProperty(value = "Posición inicial del campo")
  public BigDecimal getPosicionInicial() {
    return posicionInicial;
  }

  public void setPosicionInicial(BigDecimal posicionInicial) {
    this.posicionInicial = posicionInicial;
  }

  public CampoPosicionalArchivo posicionFinal(BigDecimal posicionFinal) {
    this.posicionFinal = posicionFinal;
    return this;
  }

  /**
   * Posición final del campo
   * @return posicionFinal
   **/
  @JsonProperty("posicionFinal")
  @ApiModelProperty(value = "Posición final del campo")
  public BigDecimal getPosicionFinal() {
    return posicionFinal;
  }

  public void setPosicionFinal(BigDecimal posicionFinal) {
    this.posicionFinal = posicionFinal;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CampoPosicionalArchivo campoPosicionalArchivo = (CampoPosicionalArchivo) o;
    return Objects.equals(this.nombre, campoPosicionalArchivo.nombre) &&
        Objects.equals(this.posicionInicial, campoPosicionalArchivo.posicionInicial) &&
        Objects.equals(this.posicionFinal, campoPosicionalArchivo.posicionFinal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nombre, posicionInicial, posicionFinal);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CampoPosicionalArchivo {\n");
    
    sb.append("    nombre: ").append(toIndentedString(nombre)).append("\n");
    sb.append("    posicionInicial: ").append(toIndentedString(posicionInicial)).append("\n");
    sb.append("    posicionFinal: ").append(toIndentedString(posicionFinal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

