/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * Sierve para almacenar las informacionaes de los campos secuenciales del archivo base de banbif
 */
@ApiModel(description = "Sierve para almacenar las informacionaes de los campos secuenciales del archivo base de banbif")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class CampoSecuencialArchivo   {
  @JsonProperty("nombre")
  private String nombre = null;

  @JsonProperty("secuencia")
  private BigDecimal secuencia = null;

  public CampoSecuencialArchivo nombre(String nombre) {
    this.nombre = nombre;
    return this;
  }

  /**
   * nombre del campo
   * @return nombre
   **/
  @JsonProperty("nombre")
  @ApiModelProperty(value = "nombre del campo")
  public String getNombre() {
    return nombre;
  }

  public void setNombre(String nombre) {
    this.nombre = nombre;
  }

  public CampoSecuencialArchivo secuencia(BigDecimal secuencia) {
    this.secuencia = secuencia;
    return this;
  }

  /**
   * Campo con el numero secuencial
   * @return secuencia
   **/
  @JsonProperty("secuencia")
  @ApiModelProperty(value = "Campo con el numero secuencial")
  public BigDecimal getSecuencia() {
    return secuencia;
  }

  public void setSecuencia(BigDecimal secuencia) {
    this.secuencia = secuencia;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CampoSecuencialArchivo campoSecuencialArchivo = (CampoSecuencialArchivo) o;
    return Objects.equals(this.nombre, campoSecuencialArchivo.nombre) &&
        Objects.equals(this.secuencia, campoSecuencialArchivo.secuencia);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nombre, secuencia);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CampoSecuencialArchivo {\n");
    
    sb.append("    nombre: ").append(toIndentedString(nombre)).append("\n");
    sb.append("    secuencia: ").append(toIndentedString(secuencia)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

