/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Canal
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class Canal   {
  @JsonProperty("codigo")
  private CodigosCanales codigo = null;

  @JsonProperty("descripcion")
  private String descripcion = null;

  public Canal codigo(CodigosCanales codigo) {
    this.codigo = codigo;
    return this;
  }

  /**
   * Get codigo
   * @return codigo
   **/
  @JsonProperty("codigo")
  @ApiModelProperty(value = "")
  public CodigosCanales getCodigo() {
    return codigo;
  }

  public void setCodigo(CodigosCanales codigo) {
    this.codigo = codigo;
  }

  public Canal descripcion(String descripcion) {
    this.descripcion = descripcion;
    return this;
  }

  /**
   * Descripción del canal por el cual se puede recaudar el convenio.
   * @return descripcion
   **/
  @JsonProperty("descripcion")
  @ApiModelProperty(value = "Descripción del canal por el cual se puede recaudar el convenio.")
  public String getDescripcion() {
    return descripcion;
  }

  public void setDescripcion(String descripcion) {
    this.descripcion = descripcion;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Canal canal = (Canal) o;
    return Objects.equals(this.codigo, canal.codigo) &&
        Objects.equals(this.descripcion, canal.descripcion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codigo, descripcion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Canal {\n");
    
    sb.append("    codigo: ").append(toIndentedString(codigo)).append("\n");
    sb.append("    descripcion: ").append(toIndentedString(descripcion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

