/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * Chequera utilizada en la transaccion
 */
@ApiModel(description = "Chequera utilizada en la transaccion")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class Chequera   {
  @JsonProperty("numeroChequeInicial")
  private BigDecimal numeroChequeInicial = null;

  @JsonProperty("numeroChequeFinal")
  private BigDecimal numeroChequeFinal = null;

  @JsonProperty("tipo")
  private String tipo = null;

  @JsonProperty("numeroChequesActivos")
  private String numeroChequesActivos = null;

  @JsonProperty("nroIdentClienCheq")
  private String nroIdentClienCheq = null;

  public Chequera numeroChequeInicial(BigDecimal numeroChequeInicial) {
    this.numeroChequeInicial = numeroChequeInicial;
    return this;
  }

  /**
   * Número del Cheque Inicial de la Chequera a la cual pertenece el Cheque de la Transacción.
   * @return numeroChequeInicial
   **/
  @JsonProperty("numeroChequeInicial")
  @ApiModelProperty(value = "Número del Cheque Inicial de la Chequera a la cual pertenece el Cheque de la Transacción.")
  public BigDecimal getNumeroChequeInicial() {
    return numeroChequeInicial;
  }

  public void setNumeroChequeInicial(BigDecimal numeroChequeInicial) {
    this.numeroChequeInicial = numeroChequeInicial;
  }

  public Chequera numeroChequeFinal(BigDecimal numeroChequeFinal) {
    this.numeroChequeFinal = numeroChequeFinal;
    return this;
  }

  /**
   * Número del Cheque Final de la Chequera a la cual pertenece el Cheque de la Transacción.
   * @return numeroChequeFinal
   **/
  @JsonProperty("numeroChequeFinal")
  @ApiModelProperty(value = "Número del Cheque Final de la Chequera a la cual pertenece el Cheque de la Transacción.")
  public BigDecimal getNumeroChequeFinal() {
    return numeroChequeFinal;
  }

  public void setNumeroChequeFinal(BigDecimal numeroChequeFinal) {
    this.numeroChequeFinal = numeroChequeFinal;
  }

  public Chequera tipo(String tipo) {
    this.tipo = tipo;
    return this;
  }

  /**
   * Tipo de Chequera utilizada en la Transacción
   * @return tipo
   **/
  @JsonProperty("tipo")
  @ApiModelProperty(value = "Tipo de Chequera utilizada en la Transacción")
  public String getTipo() {
    return tipo;
  }

  public void setTipo(String tipo) {
    this.tipo = tipo;
  }

  public Chequera numeroChequesActivos(String numeroChequesActivos) {
    this.numeroChequesActivos = numeroChequesActivos;
    return this;
  }

  /**
   * Número de Cheques Activos para la chequera de la Transacción.
   * @return numeroChequesActivos
   **/
  @JsonProperty("numeroChequesActivos")
  @ApiModelProperty(value = "Número de Cheques Activos para la chequera de la Transacción.")
  public String getNumeroChequesActivos() {
    return numeroChequesActivos;
  }

  public void setNumeroChequesActivos(String numeroChequesActivos) {
    this.numeroChequesActivos = numeroChequesActivos;
  }

  public Chequera nroIdentClienCheq(String nroIdentClienCheq) {
    this.nroIdentClienCheq = nroIdentClienCheq;
    return this;
  }

  /**
   * Número de Identificación Personal del Cliente que recibe la Chequera  (Cédula, Pasaporte, NIT, RUT,etc.)
   * @return nroIdentClienCheq
   **/
  @JsonProperty("nroIdentClienCheq")
  @ApiModelProperty(value = "Número de Identificación Personal del Cliente que recibe la Chequera  (Cédula, Pasaporte, NIT, RUT,etc.)")
  public String getNroIdentClienCheq() {
    return nroIdentClienCheq;
  }

  public void setNroIdentClienCheq(String nroIdentClienCheq) {
    this.nroIdentClienCheq = nroIdentClienCheq;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Chequera chequera = (Chequera) o;
    return Objects.equals(this.numeroChequeInicial, chequera.numeroChequeInicial) &&
        Objects.equals(this.numeroChequeFinal, chequera.numeroChequeFinal) &&
        Objects.equals(this.tipo, chequera.tipo) &&
        Objects.equals(this.numeroChequesActivos, chequera.numeroChequesActivos) &&
        Objects.equals(this.nroIdentClienCheq, chequera.nroIdentClienCheq);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroChequeInicial, numeroChequeFinal, tipo, numeroChequesActivos, nroIdentClienCheq);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Chequera {\n");
    
    sb.append("    numeroChequeInicial: ").append(toIndentedString(numeroChequeInicial)).append("\n");
    sb.append("    numeroChequeFinal: ").append(toIndentedString(numeroChequeFinal)).append("\n");
    sb.append("    tipo: ").append(toIndentedString(tipo)).append("\n");
    sb.append("    numeroChequesActivos: ").append(toIndentedString(numeroChequesActivos)).append("\n");
    sb.append("    nroIdentClienCheq: ").append(toIndentedString(nroIdentClienCheq)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

