/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;

/**
 * Cliente
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class Cliente   {
  @JsonProperty("usuarioBancaInternet")
  private String usuarioBancaInternet = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("nombre")
  private String nombre = null;

  @JsonProperty("numeroChequerasSolicitoCliente")
  private String numeroChequerasSolicitoCliente = null;

  @JsonProperty("apellidoMaterno")
  private String apellidoMaterno = null;

  @JsonProperty("apellidoPaterno")
  private String apellidoPaterno = null;

  @JsonProperty("nombresCompletos")
  private String nombresCompletos = null;

  @JsonProperty("tipoPersona")
  private TipoPersona tipoPersona = null;

  @JsonProperty("fechaVinculacion")
  private Date fechaVinculacion = null;

  @JsonProperty("codigoIBS")
  private String codigoIBS = null;

  @JsonProperty("documento")
  private DocumentoCliente documento = null;

  @JsonProperty("estadoCivil")
  private EstadoCivil estadoCivil = null;

  @JsonProperty("profesion")
  private Profesion profesion = null;

  @JsonProperty("genero")
  private Genero genero = null;

  @JsonProperty("fechaNacimiento")
  private Date fechaNacimiento = null;

  @JsonProperty("nacionalidad")
  private Nacionalidad nacionalidad = null;

  @JsonProperty("segmento")
  private Segmento segmento = null;

  @JsonProperty("conyugue")
  private Conyugue conyugue = null;

  @JsonProperty("edad")
  private BigDecimal edad = null;

  @JsonProperty("empleador")
  private Empresa empleador = null;

  @JsonProperty("fechaIngreso")
  private Date fechaIngreso = null;

  @JsonProperty("cargoOcupacion")
  private CargoOcupacion cargoOcupacion = null;

  @JsonProperty("continuidadLaboral")
  private BigDecimal continuidadLaboral = null;

  @JsonProperty("nivelEstudios")
  private NivelEstudio nivelEstudios = null;

  @JsonProperty("contacto")
  private ContactoPersona contacto = null;

  @JsonProperty("oficina")
  private Oficina oficina = null;

  @JsonProperty("banca")
  private Banca banca = null;

  @JsonProperty("categoria")
  private CategoriaCliente categoria = null;

  @JsonProperty("fechaCreacion")
  private Date fechaCreacion = null;

  @JsonProperty("latitud")
  private String latitud = null;

  @JsonProperty("longitud")
  private String longitud = null;

  @JsonProperty("notificacionRemuneracion")
  private NotificacionRemuneracion notificacionRemuneracion = null;

  @JsonProperty("tipoEnvioEecc")
  private TiposEnvioEecc tipoEnvioEecc = null;

  @JsonProperty("ultimoAtmUtilizado")
  private Atm ultimoAtmUtilizado = null;

  @JsonProperty("ultimoUsoAtm")
  private Date ultimoUsoAtm = null;

  @JsonProperty("situacionTransaccionAtm")
  private SituacionTransaccion situacionTransaccionAtm = null;

  @JsonProperty("tarjetas")
  private List<Tarjeta> tarjetas = null;

  @JsonProperty("funcionarioDelCliente")
  private String funcionarioDelCliente = null;

  @JsonProperty("sectorista")
  private Sectorista sectorista = null;

  public Cliente usuarioBancaInternet(String usuarioBancaInternet) {
    this.usuarioBancaInternet = usuarioBancaInternet;
    return this;
  }

  /**
   * Usuario Banca por Internet
   * @return usuarioBancaInternet
   **/
  @JsonProperty("usuarioBancaInternet")
  @ApiModelProperty(value = "Usuario Banca por Internet")
  public String getUsuarioBancaInternet() {
    return usuarioBancaInternet;
  }

  public void setUsuarioBancaInternet(String usuarioBancaInternet) {
    this.usuarioBancaInternet = usuarioBancaInternet;
  }

  public Cliente id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Identificador del cliente.
   * @return id
   **/
  @JsonProperty("id")
  @ApiModelProperty(value = "Identificador del cliente.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Cliente nombre(String nombre) {
    this.nombre = nombre;
    return this;
  }

  /**
   * Nombres del Cliente (sin los apellidos)
   * @return nombre
   **/
  @JsonProperty("nombre")
  @ApiModelProperty(value = "Nombres del Cliente (sin los apellidos)")
  public String getNombre() {
    return nombre;
  }

  public void setNombre(String nombre) {
    this.nombre = nombre;
  }

  public Cliente numeroChequerasSolicitoCliente(String numeroChequerasSolicitoCliente) {
    this.numeroChequerasSolicitoCliente = numeroChequerasSolicitoCliente;
    return this;
  }

  /**
   * Numero de Chequeras que solicito el Cliente
   * @return numeroChequerasSolicitoCliente
   **/
  @JsonProperty("numeroChequerasSolicitoCliente")
  @ApiModelProperty(value = "Numero de Chequeras que solicito el Cliente")
  public String getNumeroChequerasSolicitoCliente() {
    return numeroChequerasSolicitoCliente;
  }

  public void setNumeroChequerasSolicitoCliente(String numeroChequerasSolicitoCliente) {
    this.numeroChequerasSolicitoCliente = numeroChequerasSolicitoCliente;
  }

  public Cliente apellidoMaterno(String apellidoMaterno) {
    this.apellidoMaterno = apellidoMaterno;
    return this;
  }

  /**
   * Apellido materno
   * @return apellidoMaterno
   **/
  @JsonProperty("apellidoMaterno")
  @ApiModelProperty(value = "Apellido materno")
  public String getApellidoMaterno() {
    return apellidoMaterno;
  }

  public void setApellidoMaterno(String apellidoMaterno) {
    this.apellidoMaterno = apellidoMaterno;
  }

  public Cliente apellidoPaterno(String apellidoPaterno) {
    this.apellidoPaterno = apellidoPaterno;
    return this;
  }

  /**
   * Apellido paterno
   * @return apellidoPaterno
   **/
  @JsonProperty("apellidoPaterno")
  @ApiModelProperty(value = "Apellido paterno")
  public String getApellidoPaterno() {
    return apellidoPaterno;
  }

  public void setApellidoPaterno(String apellidoPaterno) {
    this.apellidoPaterno = apellidoPaterno;
  }

  public Cliente nombresCompletos(String nombresCompletos) {
    this.nombresCompletos = nombresCompletos;
    return this;
  }

  /**
   * Nombres Completos
   * @return nombresCompletos
   **/
  @JsonProperty("nombresCompletos")
  @ApiModelProperty(value = "Nombres Completos")
  public String getNombresCompletos() {
    return nombresCompletos;
  }

  public void setNombresCompletos(String nombresCompletos) {
    this.nombresCompletos = nombresCompletos;
  }

  public Cliente tipoPersona(TipoPersona tipoPersona) {
    this.tipoPersona = tipoPersona;
    return this;
  }

  /**
   * Get tipoPersona
   * @return tipoPersona
   **/
  @JsonProperty("tipoPersona")
  @ApiModelProperty(value = "")
  public TipoPersona getTipoPersona() {
    return tipoPersona;
  }

  public void setTipoPersona(TipoPersona tipoPersona) {
    this.tipoPersona = tipoPersona;
  }

  public Cliente fechaVinculacion(Date fechaVinculacion) {
    this.fechaVinculacion = fechaVinculacion;
    return this;
  }

  /**
   * Fecha de Vinculación del Cliente a la Institución
   * @return fechaVinculacion
   **/
  @JsonProperty("fechaVinculacion")
  @ApiModelProperty(value = "Fecha de Vinculación del Cliente a la Institución")
  public Date getFechaVinculacion() {
    return fechaVinculacion;
  }

  public void setFechaVinculacion(Date fechaVinculacion) {
    this.fechaVinculacion = fechaVinculacion;
  }

  public Cliente codigoIBS(String codigoIBS) {
    this.codigoIBS = codigoIBS;
    return this;
  }

  /**
   * Get codigoIBS
   * @return codigoIBS
   **/
  @JsonProperty("codigoIBS")
  @ApiModelProperty(value = "")
  public String getCodigoIBS() {
    return codigoIBS;
  }

  public void setCodigoIBS(String codigoIBS) {
    this.codigoIBS = codigoIBS;
  }

  public Cliente documento(DocumentoCliente documento) {
    this.documento = documento;
    return this;
  }

  /**
   * Get documento
   * @return documento
   **/
  @JsonProperty("documento")
  @ApiModelProperty(value = "")
  public DocumentoCliente getDocumento() {
    return documento;
  }

  public void setDocumento(DocumentoCliente documento) {
    this.documento = documento;
  }

  public Cliente estadoCivil(EstadoCivil estadoCivil) {
    this.estadoCivil = estadoCivil;
    return this;
  }

  /**
   * Get estadoCivil
   * @return estadoCivil
   **/
  @JsonProperty("estadoCivil")
  @ApiModelProperty(value = "")
  public EstadoCivil getEstadoCivil() {
    return estadoCivil;
  }

  public void setEstadoCivil(EstadoCivil estadoCivil) {
    this.estadoCivil = estadoCivil;
  }

  public Cliente profesion(Profesion profesion) {
    this.profesion = profesion;
    return this;
  }

  /**
   * Get profesion
   * @return profesion
   **/
  @JsonProperty("profesion")
  @ApiModelProperty(value = "")
  public Profesion getProfesion() {
    return profesion;
  }

  public void setProfesion(Profesion profesion) {
    this.profesion = profesion;
  }

  public Cliente genero(Genero genero) {
    this.genero = genero;
    return this;
  }

  /**
   * Get genero
   * @return genero
   **/
  @JsonProperty("genero")
  @ApiModelProperty(value = "")
  public Genero getGenero() {
    return genero;
  }

  public void setGenero(Genero genero) {
    this.genero = genero;
  }

  public Cliente fechaNacimiento(Date fechaNacimiento) {
    this.fechaNacimiento = fechaNacimiento;
    return this;
  }

  /**
   * Fecha de nacimiento
   * @return fechaNacimiento
   **/
  @JsonProperty("fechaNacimiento")
  @ApiModelProperty(value = "Fecha de nacimiento")
  public Date getFechaNacimiento() {
    return fechaNacimiento;
  }

  public void setFechaNacimiento(Date fechaNacimiento) {
    this.fechaNacimiento = fechaNacimiento;
  }

  public Cliente nacionalidad(Nacionalidad nacionalidad) {
    this.nacionalidad = nacionalidad;
    return this;
  }

  /**
   * Get nacionalidad
   * @return nacionalidad
   **/
  @JsonProperty("nacionalidad")
  @ApiModelProperty(value = "")
  public Nacionalidad getNacionalidad() {
    return nacionalidad;
  }

  public void setNacionalidad(Nacionalidad nacionalidad) {
    this.nacionalidad = nacionalidad;
  }

  public Cliente segmento(Segmento segmento) {
    this.segmento = segmento;
    return this;
  }

  /**
   * Get segmento
   * @return segmento
   **/
  @JsonProperty("segmento")
  @ApiModelProperty(value = "")
  public Segmento getSegmento() {
    return segmento;
  }

  public void setSegmento(Segmento segmento) {
    this.segmento = segmento;
  }

  public Cliente conyugue(Conyugue conyugue) {
    this.conyugue = conyugue;
    return this;
  }

  /**
   * Get conyugue
   * @return conyugue
   **/
  @JsonProperty("conyugue")
  @ApiModelProperty(value = "")
  public Conyugue getConyugue() {
    return conyugue;
  }

  public void setConyugue(Conyugue conyugue) {
    this.conyugue = conyugue;
  }

  public Cliente edad(BigDecimal edad) {
    this.edad = edad;
    return this;
  }

  /**
   * Edad del cliente
   * @return edad
   **/
  @JsonProperty("edad")
  @ApiModelProperty(value = "Edad del cliente")
  public BigDecimal getEdad() {
    return edad;
  }

  public void setEdad(BigDecimal edad) {
    this.edad = edad;
  }

  public Cliente empleador(Empresa empleador) {
    this.empleador = empleador;
    return this;
  }

  /**
   * Get empleador
   * @return empleador
   **/
  @JsonProperty("empleador")
  @ApiModelProperty(value = "")
  public Empresa getEmpleador() {
    return empleador;
  }

  public void setEmpleador(Empresa empleador) {
    this.empleador = empleador;
  }

  public Cliente fechaIngreso(Date fechaIngreso) {
    this.fechaIngreso = fechaIngreso;
    return this;
  }

  /**
   * fecha de ingreso
   * @return fechaIngreso
   **/
  @JsonProperty("fechaIngreso")
  @ApiModelProperty(value = "fecha de ingreso")
  public Date getFechaIngreso() {
    return fechaIngreso;
  }

  public void setFechaIngreso(Date fechaIngreso) {
    this.fechaIngreso = fechaIngreso;
  }

  public Cliente cargoOcupacion(CargoOcupacion cargoOcupacion) {
    this.cargoOcupacion = cargoOcupacion;
    return this;
  }

  /**
   * Get cargoOcupacion
   * @return cargoOcupacion
   **/
  @JsonProperty("cargoOcupacion")
  @ApiModelProperty(value = "")
  public CargoOcupacion getCargoOcupacion() {
    return cargoOcupacion;
  }

  public void setCargoOcupacion(CargoOcupacion cargoOcupacion) {
    this.cargoOcupacion = cargoOcupacion;
  }

  public Cliente continuidadLaboral(BigDecimal continuidadLaboral) {
    this.continuidadLaboral = continuidadLaboral;
    return this;
  }

  /**
   * Continuidad Laboral (años)
   * @return continuidadLaboral
   **/
  @JsonProperty("continuidadLaboral")
  @ApiModelProperty(value = "Continuidad Laboral (años)")
  public BigDecimal getContinuidadLaboral() {
    return continuidadLaboral;
  }

  public void setContinuidadLaboral(BigDecimal continuidadLaboral) {
    this.continuidadLaboral = continuidadLaboral;
  }

  public Cliente nivelEstudios(NivelEstudio nivelEstudios) {
    this.nivelEstudios = nivelEstudios;
    return this;
  }

  /**
   * Get nivelEstudios
   * @return nivelEstudios
   **/
  @JsonProperty("nivelEstudios")
  @ApiModelProperty(value = "")
  public NivelEstudio getNivelEstudios() {
    return nivelEstudios;
  }

  public void setNivelEstudios(NivelEstudio nivelEstudios) {
    this.nivelEstudios = nivelEstudios;
  }

  public Cliente contacto(ContactoPersona contacto) {
    this.contacto = contacto;
    return this;
  }

  /**
   * Get contacto
   * @return contacto
   **/
  @JsonProperty("contacto")
  @ApiModelProperty(value = "")
  public ContactoPersona getContacto() {
    return contacto;
  }

  public void setContacto(ContactoPersona contacto) {
    this.contacto = contacto;
  }

  public Cliente oficina(Oficina oficina) {
    this.oficina = oficina;
    return this;
  }

  /**
   * Get oficina
   * @return oficina
   **/
  @JsonProperty("oficina")
  @ApiModelProperty(value = "")
  public Oficina getOficina() {
    return oficina;
  }

  public void setOficina(Oficina oficina) {
    this.oficina = oficina;
  }

  public Cliente banca(Banca banca) {
    this.banca = banca;
    return this;
  }

  /**
   * Get banca
   * @return banca
   **/
  @JsonProperty("banca")
  @ApiModelProperty(value = "")
  public Banca getBanca() {
    return banca;
  }

  public void setBanca(Banca banca) {
    this.banca = banca;
  }

  public Cliente categoria(CategoriaCliente categoria) {
    this.categoria = categoria;
    return this;
  }

  /**
   * Get categoria
   * @return categoria
   **/
  @JsonProperty("categoria")
  @ApiModelProperty(value = "")
  public CategoriaCliente getCategoria() {
    return categoria;
  }

  public void setCategoria(CategoriaCliente categoria) {
    this.categoria = categoria;
  }

  public Cliente fechaCreacion(Date fechaCreacion) {
    this.fechaCreacion = fechaCreacion;
    return this;
  }

  /**
   * Fecha de creación del cliente
   * @return fechaCreacion
   **/
  @JsonProperty("fechaCreacion")
  @ApiModelProperty(value = "Fecha de creación del cliente")
  public Date getFechaCreacion() {
    return fechaCreacion;
  }

  public void setFechaCreacion(Date fechaCreacion) {
    this.fechaCreacion = fechaCreacion;
  }

  public Cliente latitud(String latitud) {
    this.latitud = latitud;
    return this;
  }

  /**
   * Get latitud
   * @return latitud
   **/
  @JsonProperty("latitud")
  @ApiModelProperty(value = "")
  public String getLatitud() {
    return latitud;
  }

  public void setLatitud(String latitud) {
    this.latitud = latitud;
  }

  public Cliente longitud(String longitud) {
    this.longitud = longitud;
    return this;
  }

  /**
   * Get longitud
   * @return longitud
   **/
  @JsonProperty("longitud")
  @ApiModelProperty(value = "")
  public String getLongitud() {
    return longitud;
  }

  public void setLongitud(String longitud) {
    this.longitud = longitud;
  }

  public Cliente notificacionRemuneracion(NotificacionRemuneracion notificacionRemuneracion) {
    this.notificacionRemuneracion = notificacionRemuneracion;
    return this;
  }

  /**
   * Get notificacionRemuneracion
   * @return notificacionRemuneracion
   **/
  @JsonProperty("notificacionRemuneracion")
  @ApiModelProperty(value = "")
  public NotificacionRemuneracion getNotificacionRemuneracion() {
    return notificacionRemuneracion;
  }

  public void setNotificacionRemuneracion(NotificacionRemuneracion notificacionRemuneracion) {
    this.notificacionRemuneracion = notificacionRemuneracion;
  }

  public Cliente tipoEnvioEecc(TiposEnvioEecc tipoEnvioEecc) {
    this.tipoEnvioEecc = tipoEnvioEecc;
    return this;
  }

  /**
   * Get tipoEnvioEecc
   * @return tipoEnvioEecc
   **/
  @JsonProperty("tipoEnvioEecc")
  @ApiModelProperty(value = "")
  public TiposEnvioEecc getTipoEnvioEecc() {
    return tipoEnvioEecc;
  }

  public void setTipoEnvioEecc(TiposEnvioEecc tipoEnvioEecc) {
    this.tipoEnvioEecc = tipoEnvioEecc;
  }

  public Cliente ultimoAtmUtilizado(Atm ultimoAtmUtilizado) {
    this.ultimoAtmUtilizado = ultimoAtmUtilizado;
    return this;
  }

  /**
   * Get ultimoAtmUtilizado
   * @return ultimoAtmUtilizado
   **/
  @JsonProperty("ultimoAtmUtilizado")
  @ApiModelProperty(value = "")
  public Atm getUltimoAtmUtilizado() {
    return ultimoAtmUtilizado;
  }

  public void setUltimoAtmUtilizado(Atm ultimoAtmUtilizado) {
    this.ultimoAtmUtilizado = ultimoAtmUtilizado;
  }

  public Cliente ultimoUsoAtm(Date ultimoUsoAtm) {
    this.ultimoUsoAtm = ultimoUsoAtm;
    return this;
  }

  /**
   * Fecha y hora de último uso de ATM
   * @return ultimoUsoAtm
   **/
  @JsonProperty("ultimoUsoAtm")
  @ApiModelProperty(value = "Fecha y hora de último uso de ATM")
  public Date getUltimoUsoAtm() {
    return ultimoUsoAtm;
  }

  public void setUltimoUsoAtm(Date ultimoUsoAtm) {
    this.ultimoUsoAtm = ultimoUsoAtm;
  }

  public Cliente situacionTransaccionAtm(SituacionTransaccion situacionTransaccionAtm) {
    this.situacionTransaccionAtm = situacionTransaccionAtm;
    return this;
  }

  /**
   * Get situacionTransaccionAtm
   * @return situacionTransaccionAtm
   **/
  @JsonProperty("situacionTransaccionAtm")
  @ApiModelProperty(value = "")
  public SituacionTransaccion getSituacionTransaccionAtm() {
    return situacionTransaccionAtm;
  }

  public void setSituacionTransaccionAtm(SituacionTransaccion situacionTransaccionAtm) {
    this.situacionTransaccionAtm = situacionTransaccionAtm;
  }

  public Cliente tarjetas(List<Tarjeta> tarjetas) {
    this.tarjetas = tarjetas;
    return this;
  }

  public Cliente addTarjetasItem(Tarjeta tarjetasItem) {
    if (this.tarjetas == null) {
      this.tarjetas = new ArrayList<Tarjeta>();
    }
    this.tarjetas.add(tarjetasItem);
    return this;
  }

  /**
   * Get tarjetas
   * @return tarjetas
   **/
  @JsonProperty("tarjetas")
  @ApiModelProperty(value = "")
  public List<Tarjeta> getTarjetas() {
    return tarjetas;
  }

  public void setTarjetas(List<Tarjeta> tarjetas) {
    this.tarjetas = tarjetas;
  }

  public Cliente funcionarioDelCliente(String funcionarioDelCliente) {
    this.funcionarioDelCliente = funcionarioDelCliente;
    return this;
  }

  /**
   * Funcionario del cliente
   * @return funcionarioDelCliente
   **/
  @JsonProperty("funcionarioDelCliente")
  @ApiModelProperty(value = "Funcionario del cliente")
  public String getFuncionarioDelCliente() {
    return funcionarioDelCliente;
  }

  public void setFuncionarioDelCliente(String funcionarioDelCliente) {
    this.funcionarioDelCliente = funcionarioDelCliente;
  }

  public Cliente sectorista(Sectorista sectorista) {
    this.sectorista = sectorista;
    return this;
  }

  /**
   * Get sectorista
   * @return sectorista
   **/
  @JsonProperty("sectorista")
  @ApiModelProperty(value = "")
  public Sectorista getSectorista() {
    return sectorista;
  }

  public void setSectorista(Sectorista sectorista) {
    this.sectorista = sectorista;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Cliente cliente = (Cliente) o;
    return Objects.equals(this.usuarioBancaInternet, cliente.usuarioBancaInternet) &&
        Objects.equals(this.id, cliente.id) &&
        Objects.equals(this.nombre, cliente.nombre) &&
        Objects.equals(this.numeroChequerasSolicitoCliente, cliente.numeroChequerasSolicitoCliente) &&
        Objects.equals(this.apellidoMaterno, cliente.apellidoMaterno) &&
        Objects.equals(this.apellidoPaterno, cliente.apellidoPaterno) &&
        Objects.equals(this.nombresCompletos, cliente.nombresCompletos) &&
        Objects.equals(this.tipoPersona, cliente.tipoPersona) &&
        Objects.equals(this.fechaVinculacion, cliente.fechaVinculacion) &&
        Objects.equals(this.codigoIBS, cliente.codigoIBS) &&
        Objects.equals(this.documento, cliente.documento) &&
        Objects.equals(this.estadoCivil, cliente.estadoCivil) &&
        Objects.equals(this.profesion, cliente.profesion) &&
        Objects.equals(this.genero, cliente.genero) &&
        Objects.equals(this.fechaNacimiento, cliente.fechaNacimiento) &&
        Objects.equals(this.nacionalidad, cliente.nacionalidad) &&
        Objects.equals(this.segmento, cliente.segmento) &&
        Objects.equals(this.conyugue, cliente.conyugue) &&
        Objects.equals(this.edad, cliente.edad) &&
        Objects.equals(this.empleador, cliente.empleador) &&
        Objects.equals(this.fechaIngreso, cliente.fechaIngreso) &&
        Objects.equals(this.cargoOcupacion, cliente.cargoOcupacion) &&
        Objects.equals(this.continuidadLaboral, cliente.continuidadLaboral) &&
        Objects.equals(this.nivelEstudios, cliente.nivelEstudios) &&
        Objects.equals(this.contacto, cliente.contacto) &&
        Objects.equals(this.oficina, cliente.oficina) &&
        Objects.equals(this.banca, cliente.banca) &&
        Objects.equals(this.categoria, cliente.categoria) &&
        Objects.equals(this.fechaCreacion, cliente.fechaCreacion) &&
        Objects.equals(this.latitud, cliente.latitud) &&
        Objects.equals(this.longitud, cliente.longitud) &&
        Objects.equals(this.notificacionRemuneracion, cliente.notificacionRemuneracion) &&
        Objects.equals(this.tipoEnvioEecc, cliente.tipoEnvioEecc) &&
        Objects.equals(this.ultimoAtmUtilizado, cliente.ultimoAtmUtilizado) &&
        Objects.equals(this.ultimoUsoAtm, cliente.ultimoUsoAtm) &&
        Objects.equals(this.situacionTransaccionAtm, cliente.situacionTransaccionAtm) &&
        Objects.equals(this.tarjetas, cliente.tarjetas) &&
        Objects.equals(this.funcionarioDelCliente, cliente.funcionarioDelCliente) &&
        Objects.equals(this.sectorista, cliente.sectorista);
  }

  @Override
  public int hashCode() {
    return Objects.hash(usuarioBancaInternet, id, nombre, numeroChequerasSolicitoCliente, apellidoMaterno, apellidoPaterno, nombresCompletos, tipoPersona, fechaVinculacion, codigoIBS, documento, estadoCivil, profesion, genero, fechaNacimiento, nacionalidad, segmento, conyugue, edad, empleador, fechaIngreso, cargoOcupacion, continuidadLaboral, nivelEstudios, contacto, oficina, banca, categoria, fechaCreacion, latitud, longitud, notificacionRemuneracion, tipoEnvioEecc, ultimoAtmUtilizado, ultimoUsoAtm, situacionTransaccionAtm, tarjetas, funcionarioDelCliente, sectorista);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Cliente {\n");
    
    sb.append("    usuarioBancaInternet: ").append(toIndentedString(usuarioBancaInternet)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nombre: ").append(toIndentedString(nombre)).append("\n");
    sb.append("    numeroChequerasSolicitoCliente: ").append(toIndentedString(numeroChequerasSolicitoCliente)).append("\n");
    sb.append("    apellidoMaterno: ").append(toIndentedString(apellidoMaterno)).append("\n");
    sb.append("    apellidoPaterno: ").append(toIndentedString(apellidoPaterno)).append("\n");
    sb.append("    nombresCompletos: ").append(toIndentedString(nombresCompletos)).append("\n");
    sb.append("    tipoPersona: ").append(toIndentedString(tipoPersona)).append("\n");
    sb.append("    fechaVinculacion: ").append(toIndentedString(fechaVinculacion)).append("\n");
    sb.append("    codigoIBS: ").append(toIndentedString(codigoIBS)).append("\n");
    sb.append("    documento: ").append(toIndentedString(documento)).append("\n");
    sb.append("    estadoCivil: ").append(toIndentedString(estadoCivil)).append("\n");
    sb.append("    profesion: ").append(toIndentedString(profesion)).append("\n");
    sb.append("    genero: ").append(toIndentedString(genero)).append("\n");
    sb.append("    fechaNacimiento: ").append(toIndentedString(fechaNacimiento)).append("\n");
    sb.append("    nacionalidad: ").append(toIndentedString(nacionalidad)).append("\n");
    sb.append("    segmento: ").append(toIndentedString(segmento)).append("\n");
    sb.append("    conyugue: ").append(toIndentedString(conyugue)).append("\n");
    sb.append("    edad: ").append(toIndentedString(edad)).append("\n");
    sb.append("    empleador: ").append(toIndentedString(empleador)).append("\n");
    sb.append("    fechaIngreso: ").append(toIndentedString(fechaIngreso)).append("\n");
    sb.append("    cargoOcupacion: ").append(toIndentedString(cargoOcupacion)).append("\n");
    sb.append("    continuidadLaboral: ").append(toIndentedString(continuidadLaboral)).append("\n");
    sb.append("    nivelEstudios: ").append(toIndentedString(nivelEstudios)).append("\n");
    sb.append("    contacto: ").append(toIndentedString(contacto)).append("\n");
    sb.append("    oficina: ").append(toIndentedString(oficina)).append("\n");
    sb.append("    banca: ").append(toIndentedString(banca)).append("\n");
    sb.append("    categoria: ").append(toIndentedString(categoria)).append("\n");
    sb.append("    fechaCreacion: ").append(toIndentedString(fechaCreacion)).append("\n");
    sb.append("    latitud: ").append(toIndentedString(latitud)).append("\n");
    sb.append("    longitud: ").append(toIndentedString(longitud)).append("\n");
    sb.append("    notificacionRemuneracion: ").append(toIndentedString(notificacionRemuneracion)).append("\n");
    sb.append("    tipoEnvioEecc: ").append(toIndentedString(tipoEnvioEecc)).append("\n");
    sb.append("    ultimoAtmUtilizado: ").append(toIndentedString(ultimoAtmUtilizado)).append("\n");
    sb.append("    ultimoUsoAtm: ").append(toIndentedString(ultimoUsoAtm)).append("\n");
    sb.append("    situacionTransaccionAtm: ").append(toIndentedString(situacionTransaccionAtm)).append("\n");
    sb.append("    tarjetas: ").append(toIndentedString(tarjetas)).append("\n");
    sb.append("    funcionarioDelCliente: ").append(toIndentedString(funcionarioDelCliente)).append("\n");
    sb.append("    sectorista: ").append(toIndentedString(sectorista)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

