/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Concepto Leasing
 */
public enum ConceptosLeasing {
  
  CUOTA("CUOTA"),
  
  IMPUESTO("IMPUESTO"),
  
  INFRACCION("INFRACCIOn");

  private String value;

  ConceptosLeasing(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ConceptosLeasing fromValue(String text) {
    for (ConceptosLeasing b : ConceptosLeasing.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

