/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;

/**
 * Convenio
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class Convenio   {
  @JsonProperty("codigo")
  private String codigo = null;

  @JsonProperty("descripcion")
  private String descripcion = null;

  @JsonProperty("fechaInicio")
  private Date fechaInicio = null;

  @JsonProperty("fechaFin")
  private Date fechaFin = null;

  @JsonProperty("fechaCreacion")
  private Date fechaCreacion = null;

  @JsonProperty("fechaActualizacion")
  private Date fechaActualizacion = null;

  @JsonProperty("estado")
  private String estado = null;

  @JsonProperty("recaudador")
  private Recaudador recaudador = null;

  @JsonProperty("empresa")
  private Empresa empresa = null;

  @JsonProperty("producto")
  private Producto producto = null;

  @JsonProperty("contactos")
  private List<ContactoConvenio> contactos = null;

  @JsonProperty("canales")
  private List<Canal> canales = null;

  public Convenio codigo(String codigo) {
    this.codigo = codigo;
    return this;
  }

  /**
   * Código identificador del convenio
   * @return codigo
   **/
  @JsonProperty("codigo")
  @ApiModelProperty(value = "Código identificador del convenio")
  public String getCodigo() {
    return codigo;
  }

  public void setCodigo(String codigo) {
    this.codigo = codigo;
  }

  public Convenio descripcion(String descripcion) {
    this.descripcion = descripcion;
    return this;
  }

  /**
   * Descripción del convenio
   * @return descripcion
   **/
  @JsonProperty("descripcion")
  @ApiModelProperty(value = "Descripción del convenio")
  public String getDescripcion() {
    return descripcion;
  }

  public void setDescripcion(String descripcion) {
    this.descripcion = descripcion;
  }

  public Convenio fechaInicio(Date fechaInicio) {
    this.fechaInicio = fechaInicio;
    return this;
  }

  /**
   * Fecha de inicio de vigencia del convenio. Formato ISO 8601.
   * @return fechaInicio
   **/
  @JsonProperty("fechaInicio")
  @ApiModelProperty(value = "Fecha de inicio de vigencia del convenio. Formato ISO 8601.")
  public Date getFechaInicio() {
    return fechaInicio;
  }

  public void setFechaInicio(Date fechaInicio) {
    this.fechaInicio = fechaInicio;
  }

  public Convenio fechaFin(Date fechaFin) {
    this.fechaFin = fechaFin;
    return this;
  }

  /**
   * Fecha de caducidad del convenio. Formato ISO 8601
   * @return fechaFin
   **/
  @JsonProperty("fechaFin")
  @ApiModelProperty(value = "Fecha de caducidad del convenio. Formato ISO 8601")
  public Date getFechaFin() {
    return fechaFin;
  }

  public void setFechaFin(Date fechaFin) {
    this.fechaFin = fechaFin;
  }

  public Convenio fechaCreacion(Date fechaCreacion) {
    this.fechaCreacion = fechaCreacion;
    return this;
  }

  /**
   * Fecha que se ingresó el convenio al sistema. Formato ISO 8601
   * @return fechaCreacion
   **/
  @JsonProperty("fechaCreacion")
  @ApiModelProperty(value = "Fecha que se ingresó el convenio al sistema. Formato ISO 8601")
  public Date getFechaCreacion() {
    return fechaCreacion;
  }

  public void setFechaCreacion(Date fechaCreacion) {
    this.fechaCreacion = fechaCreacion;
  }

  public Convenio fechaActualizacion(Date fechaActualizacion) {
    this.fechaActualizacion = fechaActualizacion;
    return this;
  }

  /**
   * Fecha que se realizó la última modificación al convenio en sistema. Formato ISO 8601
   * @return fechaActualizacion
   **/
  @JsonProperty("fechaActualizacion")
  @ApiModelProperty(value = "Fecha que se realizó la última modificación al convenio en sistema. Formato ISO 8601")
  public Date getFechaActualizacion() {
    return fechaActualizacion;
  }

  public void setFechaActualizacion(Date fechaActualizacion) {
    this.fechaActualizacion = fechaActualizacion;
  }

  public Convenio estado(String estado) {
    this.estado = estado;
    return this;
  }

  /**
   * Código que representa el estado del convenio, ver apartado con códigos de estado.
   * @return estado
   **/
  @JsonProperty("estado")
  @ApiModelProperty(value = "Código que representa el estado del convenio, ver apartado con códigos de estado.")
  public String getEstado() {
    return estado;
  }

  public void setEstado(String estado) {
    this.estado = estado;
  }

  public Convenio recaudador(Recaudador recaudador) {
    this.recaudador = recaudador;
    return this;
  }

  /**
   * Get recaudador
   * @return recaudador
   **/
  @JsonProperty("recaudador")
  @ApiModelProperty(value = "")
  public Recaudador getRecaudador() {
    return recaudador;
  }

  public void setRecaudador(Recaudador recaudador) {
    this.recaudador = recaudador;
  }

  public Convenio empresa(Empresa empresa) {
    this.empresa = empresa;
    return this;
  }

  /**
   * Get empresa
   * @return empresa
   **/
  @JsonProperty("empresa")
  @ApiModelProperty(value = "")
  public Empresa getEmpresa() {
    return empresa;
  }

  public void setEmpresa(Empresa empresa) {
    this.empresa = empresa;
  }

  public Convenio producto(Producto producto) {
    this.producto = producto;
    return this;
  }

  /**
   * Get producto
   * @return producto
   **/
  @JsonProperty("producto")
  @ApiModelProperty(value = "")
  public Producto getProducto() {
    return producto;
  }

  public void setProducto(Producto producto) {
    this.producto = producto;
  }

  public Convenio contactos(List<ContactoConvenio> contactos) {
    this.contactos = contactos;
    return this;
  }

  public Convenio addContactosItem(ContactoConvenio contactosItem) {
    if (this.contactos == null) {
      this.contactos = new ArrayList<ContactoConvenio>();
    }
    this.contactos.add(contactosItem);
    return this;
  }

  /**
   * Get contactos
   * @return contactos
   **/
  @JsonProperty("contactos")
  @ApiModelProperty(value = "")
  public List<ContactoConvenio> getContactos() {
    return contactos;
  }

  public void setContactos(List<ContactoConvenio> contactos) {
    this.contactos = contactos;
  }

  public Convenio canales(List<Canal> canales) {
    this.canales = canales;
    return this;
  }

  public Convenio addCanalesItem(Canal canalesItem) {
    if (this.canales == null) {
      this.canales = new ArrayList<Canal>();
    }
    this.canales.add(canalesItem);
    return this;
  }

  /**
   * Arreglo de estructura con información de los canales asociados al convenio para recaudar.
   * @return canales
   **/
  @JsonProperty("canales")
  @ApiModelProperty(value = "Arreglo de estructura con información de los canales asociados al convenio para recaudar.")
  public List<Canal> getCanales() {
    return canales;
  }

  public void setCanales(List<Canal> canales) {
    this.canales = canales;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Convenio convenio = (Convenio) o;
    return Objects.equals(this.codigo, convenio.codigo) &&
        Objects.equals(this.descripcion, convenio.descripcion) &&
        Objects.equals(this.fechaInicio, convenio.fechaInicio) &&
        Objects.equals(this.fechaFin, convenio.fechaFin) &&
        Objects.equals(this.fechaCreacion, convenio.fechaCreacion) &&
        Objects.equals(this.fechaActualizacion, convenio.fechaActualizacion) &&
        Objects.equals(this.estado, convenio.estado) &&
        Objects.equals(this.recaudador, convenio.recaudador) &&
        Objects.equals(this.empresa, convenio.empresa) &&
        Objects.equals(this.producto, convenio.producto) &&
        Objects.equals(this.contactos, convenio.contactos) &&
        Objects.equals(this.canales, convenio.canales);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codigo, descripcion, fechaInicio, fechaFin, fechaCreacion, fechaActualizacion, estado, recaudador, empresa, producto, contactos, canales);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Convenio {\n");
    
    sb.append("    codigo: ").append(toIndentedString(codigo)).append("\n");
    sb.append("    descripcion: ").append(toIndentedString(descripcion)).append("\n");
    sb.append("    fechaInicio: ").append(toIndentedString(fechaInicio)).append("\n");
    sb.append("    fechaFin: ").append(toIndentedString(fechaFin)).append("\n");
    sb.append("    fechaCreacion: ").append(toIndentedString(fechaCreacion)).append("\n");
    sb.append("    fechaActualizacion: ").append(toIndentedString(fechaActualizacion)).append("\n");
    sb.append("    estado: ").append(toIndentedString(estado)).append("\n");
    sb.append("    recaudador: ").append(toIndentedString(recaudador)).append("\n");
    sb.append("    empresa: ").append(toIndentedString(empresa)).append("\n");
    sb.append("    producto: ").append(toIndentedString(producto)).append("\n");
    sb.append("    contactos: ").append(toIndentedString(contactos)).append("\n");
    sb.append("    canales: ").append(toIndentedString(canales)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

