/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Objects;

/**
 * Conyugue
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class Conyugue   {
  @JsonProperty("nombre")
  private String nombre = null;

  @JsonProperty("apellidos")
  private String apellidos = null;

  @JsonProperty("documento")
  private DocumentoCliente documento = null;

  @JsonProperty("fechaNacimiento")
  private Date fechaNacimiento = null;

  @JsonProperty("nacionalidad")
  private Nacionalidad nacionalidad = null;

  @JsonProperty("paisResidencia")
  private Pais paisResidencia = null;

  @JsonProperty("cargoOcupacion")
  private CargoOcupacion cargoOcupacion = null;

  @JsonProperty("empleador")
  private Empresa empleador = null;

  @JsonProperty("actividadEconomica")
  private ActividadEconomica actividadEconomica = null;

  @JsonProperty("fechaIngreso")
  private Date fechaIngreso = null;

  @JsonProperty("profesion")
  private Profesion profesion = null;

  @JsonProperty("nivelEstudios")
  private NivelEstudio nivelEstudios = null;

  @JsonProperty("monedaIngresos")
  private CodigosMonedas monedaIngresos = null;

  @JsonProperty("ingresoNeto")
  private BigDecimal ingresoNeto = null;

  @JsonProperty("sectorista")
  private Sectorista sectorista = null;

  @JsonProperty("funcionarioDelCliente")
  private String funcionarioDelCliente = null;

  public Conyugue nombre(String nombre) {
    this.nombre = nombre;
    return this;
  }

  /**
   * Nombres del Conyugue (sin los apellidos)
   * @return nombre
   **/
  @JsonProperty("nombre")
  @ApiModelProperty(value = "Nombres del Conyugue (sin los apellidos)")
  public String getNombre() {
    return nombre;
  }

  public void setNombre(String nombre) {
    this.nombre = nombre;
  }

  public Conyugue apellidos(String apellidos) {
    this.apellidos = apellidos;
    return this;
  }

  /**
   * Apellidos
   * @return apellidos
   **/
  @JsonProperty("apellidos")
  @ApiModelProperty(value = "Apellidos")
  public String getApellidos() {
    return apellidos;
  }

  public void setApellidos(String apellidos) {
    this.apellidos = apellidos;
  }

  public Conyugue documento(DocumentoCliente documento) {
    this.documento = documento;
    return this;
  }

  /**
   * Get documento
   * @return documento
   **/
  @JsonProperty("documento")
  @ApiModelProperty(value = "")
  public DocumentoCliente getDocumento() {
    return documento;
  }

  public void setDocumento(DocumentoCliente documento) {
    this.documento = documento;
  }

  public Conyugue fechaNacimiento(Date fechaNacimiento) {
    this.fechaNacimiento = fechaNacimiento;
    return this;
  }

  /**
   * Fecha de nacimiento
   * @return fechaNacimiento
   **/
  @JsonProperty("fechaNacimiento")
  @ApiModelProperty(value = "Fecha de nacimiento")
  public Date getFechaNacimiento() {
    return fechaNacimiento;
  }

  public void setFechaNacimiento(Date fechaNacimiento) {
    this.fechaNacimiento = fechaNacimiento;
  }

  public Conyugue nacionalidad(Nacionalidad nacionalidad) {
    this.nacionalidad = nacionalidad;
    return this;
  }

  /**
   * Get nacionalidad
   * @return nacionalidad
   **/
  @JsonProperty("nacionalidad")
  @ApiModelProperty(value = "")
  public Nacionalidad getNacionalidad() {
    return nacionalidad;
  }

  public void setNacionalidad(Nacionalidad nacionalidad) {
    this.nacionalidad = nacionalidad;
  }

  public Conyugue paisResidencia(Pais paisResidencia) {
    this.paisResidencia = paisResidencia;
    return this;
  }

  /**
   * Get paisResidencia
   * @return paisResidencia
   **/
  @JsonProperty("paisResidencia")
  @ApiModelProperty(value = "")
  public Pais getPaisResidencia() {
    return paisResidencia;
  }

  public void setPaisResidencia(Pais paisResidencia) {
    this.paisResidencia = paisResidencia;
  }

  public Conyugue cargoOcupacion(CargoOcupacion cargoOcupacion) {
    this.cargoOcupacion = cargoOcupacion;
    return this;
  }

  /**
   * Get cargoOcupacion
   * @return cargoOcupacion
   **/
  @JsonProperty("cargoOcupacion")
  @ApiModelProperty(value = "")
  public CargoOcupacion getCargoOcupacion() {
    return cargoOcupacion;
  }

  public void setCargoOcupacion(CargoOcupacion cargoOcupacion) {
    this.cargoOcupacion = cargoOcupacion;
  }

  public Conyugue empleador(Empresa empleador) {
    this.empleador = empleador;
    return this;
  }

  /**
   * Get empleador
   * @return empleador
   **/
  @JsonProperty("empleador")
  @ApiModelProperty(value = "")
  public Empresa getEmpleador() {
    return empleador;
  }

  public void setEmpleador(Empresa empleador) {
    this.empleador = empleador;
  }

  public Conyugue actividadEconomica(ActividadEconomica actividadEconomica) {
    this.actividadEconomica = actividadEconomica;
    return this;
  }

  /**
   * Get actividadEconomica
   * @return actividadEconomica
   **/
  @JsonProperty("actividadEconomica")
  @ApiModelProperty(value = "")
  public ActividadEconomica getActividadEconomica() {
    return actividadEconomica;
  }

  public void setActividadEconomica(ActividadEconomica actividadEconomica) {
    this.actividadEconomica = actividadEconomica;
  }

  public Conyugue fechaIngreso(Date fechaIngreso) {
    this.fechaIngreso = fechaIngreso;
    return this;
  }

  /**
   * Fecha Ingreso Cónyugue
   * @return fechaIngreso
   **/
  @JsonProperty("fechaIngreso")
  @ApiModelProperty(value = "Fecha Ingreso Cónyugue")
  public Date getFechaIngreso() {
    return fechaIngreso;
  }

  public void setFechaIngreso(Date fechaIngreso) {
    this.fechaIngreso = fechaIngreso;
  }

  public Conyugue profesion(Profesion profesion) {
    this.profesion = profesion;
    return this;
  }

  /**
   * Get profesion
   * @return profesion
   **/
  @JsonProperty("profesion")
  @ApiModelProperty(value = "")
  public Profesion getProfesion() {
    return profesion;
  }

  public void setProfesion(Profesion profesion) {
    this.profesion = profesion;
  }

  public Conyugue nivelEstudios(NivelEstudio nivelEstudios) {
    this.nivelEstudios = nivelEstudios;
    return this;
  }

  /**
   * Get nivelEstudios
   * @return nivelEstudios
   **/
  @JsonProperty("nivelEstudios")
  @ApiModelProperty(value = "")
  public NivelEstudio getNivelEstudios() {
    return nivelEstudios;
  }

  public void setNivelEstudios(NivelEstudio nivelEstudios) {
    this.nivelEstudios = nivelEstudios;
  }

  public Conyugue monedaIngresos(CodigosMonedas monedaIngresos) {
    this.monedaIngresos = monedaIngresos;
    return this;
  }

  /**
   * Get monedaIngresos
   * @return monedaIngresos
   **/
  @JsonProperty("monedaIngresos")
  @ApiModelProperty(value = "")
  public CodigosMonedas getMonedaIngresos() {
    return monedaIngresos;
  }

  public void setMonedaIngresos(CodigosMonedas monedaIngresos) {
    this.monedaIngresos = monedaIngresos;
  }

  public Conyugue ingresoNeto(BigDecimal ingresoNeto) {
    this.ingresoNeto = ingresoNeto;
    return this;
  }

  /**
   * Ingreso Neto
   * @return ingresoNeto
   **/
  @JsonProperty("ingresoNeto")
  @ApiModelProperty(value = "Ingreso Neto")
  public BigDecimal getIngresoNeto() {
    return ingresoNeto;
  }

  public void setIngresoNeto(BigDecimal ingresoNeto) {
    this.ingresoNeto = ingresoNeto;
  }

  public Conyugue sectorista(Sectorista sectorista) {
    this.sectorista = sectorista;
    return this;
  }

  /**
   * Get sectorista
   * @return sectorista
   **/
  @JsonProperty("sectorista")
  @ApiModelProperty(value = "")
  public Sectorista getSectorista() {
    return sectorista;
  }

  public void setSectorista(Sectorista sectorista) {
    this.sectorista = sectorista;
  }

  public Conyugue funcionarioDelCliente(String funcionarioDelCliente) {
    this.funcionarioDelCliente = funcionarioDelCliente;
    return this;
  }

  /**
   * Funcionario del cliente
   * @return funcionarioDelCliente
   **/
  @JsonProperty("funcionarioDelCliente")
  @ApiModelProperty(value = "Funcionario del cliente")
  public String getFuncionarioDelCliente() {
    return funcionarioDelCliente;
  }

  public void setFuncionarioDelCliente(String funcionarioDelCliente) {
    this.funcionarioDelCliente = funcionarioDelCliente;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Conyugue conyugue = (Conyugue) o;
    return Objects.equals(this.nombre, conyugue.nombre) &&
        Objects.equals(this.apellidos, conyugue.apellidos) &&
        Objects.equals(this.documento, conyugue.documento) &&
        Objects.equals(this.fechaNacimiento, conyugue.fechaNacimiento) &&
        Objects.equals(this.nacionalidad, conyugue.nacionalidad) &&
        Objects.equals(this.paisResidencia, conyugue.paisResidencia) &&
        Objects.equals(this.cargoOcupacion, conyugue.cargoOcupacion) &&
        Objects.equals(this.empleador, conyugue.empleador) &&
        Objects.equals(this.actividadEconomica, conyugue.actividadEconomica) &&
        Objects.equals(this.fechaIngreso, conyugue.fechaIngreso) &&
        Objects.equals(this.profesion, conyugue.profesion) &&
        Objects.equals(this.nivelEstudios, conyugue.nivelEstudios) &&
        Objects.equals(this.monedaIngresos, conyugue.monedaIngresos) &&
        Objects.equals(this.ingresoNeto, conyugue.ingresoNeto) &&
        Objects.equals(this.sectorista, conyugue.sectorista) &&
        Objects.equals(this.funcionarioDelCliente, conyugue.funcionarioDelCliente);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nombre, apellidos, documento, fechaNacimiento, nacionalidad, paisResidencia, cargoOcupacion, empleador, actividadEconomica, fechaIngreso, profesion, nivelEstudios, monedaIngresos, ingresoNeto, sectorista, funcionarioDelCliente);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Conyugue {\n");
    
    sb.append("    nombre: ").append(toIndentedString(nombre)).append("\n");
    sb.append("    apellidos: ").append(toIndentedString(apellidos)).append("\n");
    sb.append("    documento: ").append(toIndentedString(documento)).append("\n");
    sb.append("    fechaNacimiento: ").append(toIndentedString(fechaNacimiento)).append("\n");
    sb.append("    nacionalidad: ").append(toIndentedString(nacionalidad)).append("\n");
    sb.append("    paisResidencia: ").append(toIndentedString(paisResidencia)).append("\n");
    sb.append("    cargoOcupacion: ").append(toIndentedString(cargoOcupacion)).append("\n");
    sb.append("    empleador: ").append(toIndentedString(empleador)).append("\n");
    sb.append("    actividadEconomica: ").append(toIndentedString(actividadEconomica)).append("\n");
    sb.append("    fechaIngreso: ").append(toIndentedString(fechaIngreso)).append("\n");
    sb.append("    profesion: ").append(toIndentedString(profesion)).append("\n");
    sb.append("    nivelEstudios: ").append(toIndentedString(nivelEstudios)).append("\n");
    sb.append("    monedaIngresos: ").append(toIndentedString(monedaIngresos)).append("\n");
    sb.append("    ingresoNeto: ").append(toIndentedString(ingresoNeto)).append("\n");
    sb.append("    sectorista: ").append(toIndentedString(sectorista)).append("\n");
    sb.append("    funcionarioDelCliente: ").append(toIndentedString(funcionarioDelCliente)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

