/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Objects;

/**
 * Cuota
 */
@ApiModel(description = "Cuota")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class Cuota   {
  @JsonProperty("numero")
  private BigDecimal numero = null;

  @JsonProperty("capital")
  private Double capital = null;

  @JsonProperty("interes")
  private Double interes = null;

  @JsonProperty("interesMora")
  private Double interesMora = null;

  @JsonProperty("interesCompensatorioVencido")
  private Double interesCompensatorioVencido = null;

  @JsonProperty("seguro")
  private Double seguro = null;

  @JsonProperty("comision")
  private Double comision = null;

  @JsonProperty("monto")
  private Double monto = null;

  @JsonProperty("mora")
  private BigDecimal mora = null;

  @JsonProperty("diasMora")
  private BigDecimal diasMora = null;

  @JsonProperty("itf")
  private BigDecimal itf = null;

  @JsonProperty("totalPagar")
  private BigDecimal totalPagar = null;

  @JsonProperty("estado")
  private String estado = null;

  @JsonProperty("fechaVencimiento")
  private Date fechaVencimiento = null;

  @JsonProperty("diasTranscurridosUltimoPago")
  private BigDecimal diasTranscurridosUltimoPago = null;

  @JsonProperty("diasPendientesSiguientePago")
  private BigDecimal diasPendientesSiguientePago = null;

  @JsonProperty("prestamo")
  private Prestamo prestamo = null;

  public Cuota numero(BigDecimal numero) {
    this.numero = numero;
    return this;
  }

  /**
   * Número de Cuota
   * @return numero
   **/
  @JsonProperty("numero")
  @ApiModelProperty(value = "Número de Cuota")
  public BigDecimal getNumero() {
    return numero;
  }

  public void setNumero(BigDecimal numero) {
    this.numero = numero;
  }

  public Cuota capital(Double capital) {
    this.capital = capital;
    return this;
  }

  /**
   * Capital Cuota
   * @return capital
   **/
  @JsonProperty("capital")
  @ApiModelProperty(value = "Capital Cuota")
  public Double getCapital() {
    return capital;
  }

  public void setCapital(Double capital) {
    this.capital = capital;
  }

  public Cuota interes(Double interes) {
    this.interes = interes;
    return this;
  }

  /**
   * Interés Cuota
   * @return interes
   **/
  @JsonProperty("interes")
  @ApiModelProperty(value = "Interés Cuota")
  public Double getInteres() {
    return interes;
  }

  public void setInteres(Double interes) {
    this.interes = interes;
  }

  public Cuota interesMora(Double interesMora) {
    this.interesMora = interesMora;
    return this;
  }

  /**
   * Interés Mora
   * @return interesMora
   **/
  @JsonProperty("interesMora")
  @ApiModelProperty(value = "Interés Mora")
  public Double getInteresMora() {
    return interesMora;
  }

  public void setInteresMora(Double interesMora) {
    this.interesMora = interesMora;
  }

  public Cuota interesCompensatorioVencido(Double interesCompensatorioVencido) {
    this.interesCompensatorioVencido = interesCompensatorioVencido;
    return this;
  }

  /**
   * Interés compensatorio Vencido
   * @return interesCompensatorioVencido
   **/
  @JsonProperty("interesCompensatorioVencido")
  @ApiModelProperty(value = "Interés compensatorio Vencido")
  public Double getInteresCompensatorioVencido() {
    return interesCompensatorioVencido;
  }

  public void setInteresCompensatorioVencido(Double interesCompensatorioVencido) {
    this.interesCompensatorioVencido = interesCompensatorioVencido;
  }

  public Cuota seguro(Double seguro) {
    this.seguro = seguro;
    return this;
  }

  /**
   * Seguro Cuota
   * @return seguro
   **/
  @JsonProperty("seguro")
  @ApiModelProperty(value = "Seguro Cuota")
  public Double getSeguro() {
    return seguro;
  }

  public void setSeguro(Double seguro) {
    this.seguro = seguro;
  }

  public Cuota comision(Double comision) {
    this.comision = comision;
    return this;
  }

  /**
   * Comisión Cuota
   * @return comision
   **/
  @JsonProperty("comision")
  @ApiModelProperty(value = "Comisión Cuota")
  public Double getComision() {
    return comision;
  }

  public void setComision(Double comision) {
    this.comision = comision;
  }

  public Cuota monto(Double monto) {
    this.monto = monto;
    return this;
  }

  /**
   * Monto de Cuota
   * @return monto
   **/
  @JsonProperty("monto")
  @ApiModelProperty(value = "Monto de Cuota")
  public Double getMonto() {
    return monto;
  }

  public void setMonto(Double monto) {
    this.monto = monto;
  }

  public Cuota mora(BigDecimal mora) {
    this.mora = mora;
    return this;
  }

  /**
   * Interés de Mora
   * @return mora
   **/
  @JsonProperty("mora")
  @ApiModelProperty(value = "Interés de Mora")
  public BigDecimal getMora() {
    return mora;
  }

  public void setMora(BigDecimal mora) {
    this.mora = mora;
  }

  public Cuota diasMora(BigDecimal diasMora) {
    this.diasMora = diasMora;
    return this;
  }

  /**
   * Días de Mora
   * @return diasMora
   **/
  @JsonProperty("diasMora")
  @ApiModelProperty(value = "Días de Mora")
  public BigDecimal getDiasMora() {
    return diasMora;
  }

  public void setDiasMora(BigDecimal diasMora) {
    this.diasMora = diasMora;
  }

  public Cuota itf(BigDecimal itf) {
    this.itf = itf;
    return this;
  }

  /**
   * Monto ITF
   * @return itf
   **/
  @JsonProperty("itf")
  @ApiModelProperty(value = "Monto ITF")
  public BigDecimal getItf() {
    return itf;
  }

  public void setItf(BigDecimal itf) {
    this.itf = itf;
  }

  public Cuota totalPagar(BigDecimal totalPagar) {
    this.totalPagar = totalPagar;
    return this;
  }

  /**
   * Total a Pagar por Cuota (Monto de Cuota + ITF)
   * @return totalPagar
   **/
  @JsonProperty("totalPagar")
  @ApiModelProperty(value = "Total a Pagar por Cuota (Monto de Cuota + ITF)")
  public BigDecimal getTotalPagar() {
    return totalPagar;
  }

  public void setTotalPagar(BigDecimal totalPagar) {
    this.totalPagar = totalPagar;
  }

  public Cuota estado(String estado) {
    this.estado = estado;
    return this;
  }

  /**
   * Estado
   * @return estado
   **/
  @JsonProperty("estado")
  @ApiModelProperty(value = "Estado")
  public String getEstado() {
    return estado;
  }

  public void setEstado(String estado) {
    this.estado = estado;
  }

  public Cuota fechaVencimiento(Date fechaVencimiento) {
    this.fechaVencimiento = fechaVencimiento;
    return this;
  }

  /**
   * Fecha de Vencimiento de Cuota
   * @return fechaVencimiento
   **/
  @JsonProperty("fechaVencimiento")
  @ApiModelProperty(value = "Fecha de Vencimiento de Cuota")
  public Date getFechaVencimiento() {
    return fechaVencimiento;
  }

  public void setFechaVencimiento(Date fechaVencimiento) {
    this.fechaVencimiento = fechaVencimiento;
  }

  public Cuota diasTranscurridosUltimoPago(BigDecimal diasTranscurridosUltimoPago) {
    this.diasTranscurridosUltimoPago = diasTranscurridosUltimoPago;
    return this;
  }

  /**
   * Días Transcurridos desde último Pago
   * @return diasTranscurridosUltimoPago
   **/
  @JsonProperty("diasTranscurridosUltimoPago")
  @ApiModelProperty(value = "Días Transcurridos desde último Pago")
  public BigDecimal getDiasTranscurridosUltimoPago() {
    return diasTranscurridosUltimoPago;
  }

  public void setDiasTranscurridosUltimoPago(BigDecimal diasTranscurridosUltimoPago) {
    this.diasTranscurridosUltimoPago = diasTranscurridosUltimoPago;
  }

  public Cuota diasPendientesSiguientePago(BigDecimal diasPendientesSiguientePago) {
    this.diasPendientesSiguientePago = diasPendientesSiguientePago;
    return this;
  }

  /**
   * Días Pendientes para el siguiente Pago
   * @return diasPendientesSiguientePago
   **/
  @JsonProperty("diasPendientesSiguientePago")
  @ApiModelProperty(value = "Días Pendientes para el siguiente Pago")
  public BigDecimal getDiasPendientesSiguientePago() {
    return diasPendientesSiguientePago;
  }

  public void setDiasPendientesSiguientePago(BigDecimal diasPendientesSiguientePago) {
    this.diasPendientesSiguientePago = diasPendientesSiguientePago;
  }

  public Cuota prestamo(Prestamo prestamo) {
    this.prestamo = prestamo;
    return this;
  }

  /**
   * Get prestamo
   * @return prestamo
   **/
  @JsonProperty("prestamo")
  @ApiModelProperty(value = "")
  public Prestamo getPrestamo() {
    return prestamo;
  }

  public void setPrestamo(Prestamo prestamo) {
    this.prestamo = prestamo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Cuota cuota = (Cuota) o;
    return Objects.equals(this.numero, cuota.numero) &&
        Objects.equals(this.capital, cuota.capital) &&
        Objects.equals(this.interes, cuota.interes) &&
        Objects.equals(this.interesMora, cuota.interesMora) &&
        Objects.equals(this.interesCompensatorioVencido, cuota.interesCompensatorioVencido) &&
        Objects.equals(this.seguro, cuota.seguro) &&
        Objects.equals(this.comision, cuota.comision) &&
        Objects.equals(this.monto, cuota.monto) &&
        Objects.equals(this.mora, cuota.mora) &&
        Objects.equals(this.diasMora, cuota.diasMora) &&
        Objects.equals(this.itf, cuota.itf) &&
        Objects.equals(this.totalPagar, cuota.totalPagar) &&
        Objects.equals(this.estado, cuota.estado) &&
        Objects.equals(this.fechaVencimiento, cuota.fechaVencimiento) &&
        Objects.equals(this.diasTranscurridosUltimoPago, cuota.diasTranscurridosUltimoPago) &&
        Objects.equals(this.diasPendientesSiguientePago, cuota.diasPendientesSiguientePago) &&
        Objects.equals(this.prestamo, cuota.prestamo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numero, capital, interes, interesMora, interesCompensatorioVencido, seguro, comision, monto, mora, diasMora, itf, totalPagar, estado, fechaVencimiento, diasTranscurridosUltimoPago, diasPendientesSiguientePago, prestamo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Cuota {\n");
    
    sb.append("    numero: ").append(toIndentedString(numero)).append("\n");
    sb.append("    capital: ").append(toIndentedString(capital)).append("\n");
    sb.append("    interes: ").append(toIndentedString(interes)).append("\n");
    sb.append("    interesMora: ").append(toIndentedString(interesMora)).append("\n");
    sb.append("    interesCompensatorioVencido: ").append(toIndentedString(interesCompensatorioVencido)).append("\n");
    sb.append("    seguro: ").append(toIndentedString(seguro)).append("\n");
    sb.append("    comision: ").append(toIndentedString(comision)).append("\n");
    sb.append("    monto: ").append(toIndentedString(monto)).append("\n");
    sb.append("    mora: ").append(toIndentedString(mora)).append("\n");
    sb.append("    diasMora: ").append(toIndentedString(diasMora)).append("\n");
    sb.append("    itf: ").append(toIndentedString(itf)).append("\n");
    sb.append("    totalPagar: ").append(toIndentedString(totalPagar)).append("\n");
    sb.append("    estado: ").append(toIndentedString(estado)).append("\n");
    sb.append("    fechaVencimiento: ").append(toIndentedString(fechaVencimiento)).append("\n");
    sb.append("    diasTranscurridosUltimoPago: ").append(toIndentedString(diasTranscurridosUltimoPago)).append("\n");
    sb.append("    diasPendientesSiguientePago: ").append(toIndentedString(diasPendientesSiguientePago)).append("\n");
    sb.append("    prestamo: ").append(toIndentedString(prestamo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

