/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Direccion
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class Direccion   {
  @JsonProperty("direccion")
  private String direccion = null;

  @JsonProperty("estado")
  private String estado = null;

  @JsonProperty("lugar")
  private String lugar = null;

  @JsonProperty("ciudad")
  private String ciudad = null;

  @JsonProperty("barrio")
  private String barrio = null;

  @JsonProperty("departamento")
  private String departamento = null;

  @JsonProperty("pais")
  private String pais = null;

  @JsonProperty("aa")
  private String aa = null;

  public Direccion direccion(String direccion) {
    this.direccion = direccion;
    return this;
  }

  /**
   * Dirección
   * @return direccion
   **/
  @JsonProperty("direccion")
  @ApiModelProperty(value = "Dirección")
  public String getDireccion() {
    return direccion;
  }

  public void setDireccion(String direccion) {
    this.direccion = direccion;
  }

  public Direccion estado(String estado) {
    this.estado = estado;
    return this;
  }

  /**
   * Estado
   * @return estado
   **/
  @JsonProperty("estado")
  @ApiModelProperty(value = "Estado")
  public String getEstado() {
    return estado;
  }

  public void setEstado(String estado) {
    this.estado = estado;
  }

  public Direccion lugar(String lugar) {
    this.lugar = lugar;
    return this;
  }

  /**
   * Lugar
   * @return lugar
   **/
  @JsonProperty("lugar")
  @ApiModelProperty(value = "Lugar")
  public String getLugar() {
    return lugar;
  }

  public void setLugar(String lugar) {
    this.lugar = lugar;
  }

  public Direccion ciudad(String ciudad) {
    this.ciudad = ciudad;
    return this;
  }

  /**
   * Ciudad
   * @return ciudad
   **/
  @JsonProperty("ciudad")
  @ApiModelProperty(value = "Ciudad")
  public String getCiudad() {
    return ciudad;
  }

  public void setCiudad(String ciudad) {
    this.ciudad = ciudad;
  }

  public Direccion barrio(String barrio) {
    this.barrio = barrio;
    return this;
  }

  /**
   * Barrio
   * @return barrio
   **/
  @JsonProperty("barrio")
  @ApiModelProperty(value = "Barrio")
  public String getBarrio() {
    return barrio;
  }

  public void setBarrio(String barrio) {
    this.barrio = barrio;
  }

  public Direccion departamento(String departamento) {
    this.departamento = departamento;
    return this;
  }

  /**
   * Departamento
   * @return departamento
   **/
  @JsonProperty("departamento")
  @ApiModelProperty(value = "Departamento")
  public String getDepartamento() {
    return departamento;
  }

  public void setDepartamento(String departamento) {
    this.departamento = departamento;
  }

  public Direccion pais(String pais) {
    this.pais = pais;
    return this;
  }

  /**
   * País
   * @return pais
   **/
  @JsonProperty("pais")
  @ApiModelProperty(value = "País")
  public String getPais() {
    return pais;
  }

  public void setPais(String pais) {
    this.pais = pais;
  }

  public Direccion aa(String aa) {
    this.aa = aa;
    return this;
  }

  /**
   * A.A.
   * @return aa
   **/
  @JsonProperty("aa")
  @ApiModelProperty(value = "A.A.")
  public String getAa() {
    return aa;
  }

  public void setAa(String aa) {
    this.aa = aa;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Direccion direccion = (Direccion) o;
    return Objects.equals(this.direccion, direccion.direccion) &&
        Objects.equals(this.estado, direccion.estado) &&
        Objects.equals(this.lugar, direccion.lugar) &&
        Objects.equals(this.ciudad, direccion.ciudad) &&
        Objects.equals(this.barrio, direccion.barrio) &&
        Objects.equals(this.departamento, direccion.departamento) &&
        Objects.equals(this.pais, direccion.pais) &&
        Objects.equals(this.aa, direccion.aa);
  }

  @Override
  public int hashCode() {
    return Objects.hash(direccion, estado, lugar, ciudad, barrio, departamento, pais, aa);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Direccion {\n");
    
    sb.append("    direccion: ").append(toIndentedString(direccion)).append("\n");
    sb.append("    estado: ").append(toIndentedString(estado)).append("\n");
    sb.append("    lugar: ").append(toIndentedString(lugar)).append("\n");
    sb.append("    ciudad: ").append(toIndentedString(ciudad)).append("\n");
    sb.append("    barrio: ").append(toIndentedString(barrio)).append("\n");
    sb.append("    departamento: ").append(toIndentedString(departamento)).append("\n");
    sb.append("    pais: ").append(toIndentedString(pais)).append("\n");
    sb.append("    aa: ").append(toIndentedString(aa)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

