/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * DocumentoDeuda
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class DocumentoDeuda   {
  /**
   * Código del tipo de documento asociado a la deuda.
   */
  public enum TipoEnum {
    BOL("BOL"),
    
    FAC("FAC");

    private String value;

    TipoEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TipoEnum fromValue(String text) {
      for (TipoEnum b : TipoEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("tipo")
  private TipoEnum tipo = null;

  @JsonProperty("numero")
  private String numero = null;

  public DocumentoDeuda tipo(TipoEnum tipo) {
    this.tipo = tipo;
    return this;
  }

  /**
   * Código del tipo de documento asociado a la deuda.
   * @return tipo
   **/
  @JsonProperty("tipo")
  @ApiModelProperty(value = "Código del tipo de documento asociado a la deuda.")
  public TipoEnum getTipo() {
    return tipo;
  }

  public void setTipo(TipoEnum tipo) {
    this.tipo = tipo;
  }

  public DocumentoDeuda numero(String numero) {
    this.numero = numero;
    return this;
  }

  /**
   * Número de documento asociado a la deuda
   * @return numero
   **/
  @JsonProperty("numero")
  @ApiModelProperty(value = "Número de documento asociado a la deuda")
  public String getNumero() {
    return numero;
  }

  public void setNumero(String numero) {
    this.numero = numero;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentoDeuda documentoDeuda = (DocumentoDeuda) o;
    return Objects.equals(this.tipo, documentoDeuda.tipo) &&
        Objects.equals(this.numero, documentoDeuda.numero);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tipo, numero);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentoDeuda {\n");
    
    sb.append("    tipo: ").append(toIndentedString(tipo)).append("\n");
    sb.append("    numero: ").append(toIndentedString(numero)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

