/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Formas/Medios de Pago
 */
public enum FormasPago {
  
  EFECTIVO("EFECTIVO"),
  
  CHEQUE_MISMO_BANCO("CHEQUE_MISMO_BANCO"),
  
  CARGO_CUENTA("CARGO_CUENTA"),
  
  DESCUENTO_PLANILLA("DESCUENTO_PLANILLA"),
  
  TARJETA("TARJETA");

  private String value;

  FormasPago(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static FormasPago fromValue(String text) {
    for (FormasPago b : FormasPago.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

