/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Tipos de Funcionalidad
 */
public enum Funcionalidad {
  
  AHORRO_VUELTO("AHORRO_VUELTO"),
  
  AHORRO_PROGRAMADO("AHORRO_PROGRAMADO"),
  
  DISPOSICION_EFECTIVO("DISPOSICION_EFECTIVO");

  private String value;

  Funcionalidad(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static Funcionalidad fromValue(String text) {
    for (Funcionalidad b : Funcionalidad.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

