/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.DecimalMax;
import java.math.BigDecimal;
import java.util.Objects;

/**
 * Garantia
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class Garantia   {
  @JsonProperty("numero")
  private BigDecimal numero = null;

  @JsonProperty("ambito")
  private String ambito = null;

  @JsonProperty("porcentaje")
  private BigDecimal porcentaje = null;

  @JsonProperty("importe")
  private BigDecimal importe = null;

  @JsonProperty("tipo")
  private TipoGarantia tipo = null;

  @JsonProperty("importeGravamen")
  private BigDecimal importeGravamen = null;

  @JsonProperty("vri")
  private BigDecimal vri = null;

  @JsonProperty("moneda")
  private CodigosMonedas moneda = null;

  @JsonProperty("funciones")
  private String funciones = null;

  public Garantia numero(BigDecimal numero) {
    this.numero = numero;
    return this;
  }

  /**
   * Numero de Garantia
   * maximum: 12
   * @return numero
   **/
  @JsonProperty("numero")
  @ApiModelProperty(value = "Numero de Garantia")
 @DecimalMax("12")  public BigDecimal getNumero() {
    return numero;
  }

  public void setNumero(BigDecimal numero) {
    this.numero = numero;
  }

  public Garantia ambito(String ambito) {
    this.ambito = ambito;
    return this;
  }

  /**
   * Ambito de la Garantia
   * @return ambito
   **/
  @JsonProperty("ambito")
  @ApiModelProperty(value = "Ambito de la Garantia")
  public String getAmbito() {
    return ambito;
  }

  public void setAmbito(String ambito) {
    this.ambito = ambito;
  }

  public Garantia porcentaje(BigDecimal porcentaje) {
    this.porcentaje = porcentaje;
    return this;
  }

  /**
   * Porcentaje Garantia
   * @return porcentaje
   **/
  @JsonProperty("porcentaje")
  @ApiModelProperty(value = "Porcentaje Garantia")
  public BigDecimal getPorcentaje() {
    return porcentaje;
  }

  public void setPorcentaje(BigDecimal porcentaje) {
    this.porcentaje = porcentaje;
  }

  public Garantia importe(BigDecimal importe) {
    this.importe = importe;
    return this;
  }

  /**
   * Importe.
   * @return importe
   **/
  @JsonProperty("importe")
  @ApiModelProperty(value = "Importe.")
  public BigDecimal getImporte() {
    return importe;
  }

  public void setImporte(BigDecimal importe) {
    this.importe = importe;
  }

  public Garantia tipo(TipoGarantia tipo) {
    this.tipo = tipo;
    return this;
  }

  /**
   * Get tipo
   * @return tipo
   **/
  @JsonProperty("tipo")
  @ApiModelProperty(value = "")
  public TipoGarantia getTipo() {
    return tipo;
  }

  public void setTipo(TipoGarantia tipo) {
    this.tipo = tipo;
  }

  public Garantia importeGravamen(BigDecimal importeGravamen) {
    this.importeGravamen = importeGravamen;
    return this;
  }

  /**
   * Importe del gravamen
   * @return importeGravamen
   **/
  @JsonProperty("importeGravamen")
  @ApiModelProperty(value = "Importe del gravamen")
  public BigDecimal getImporteGravamen() {
    return importeGravamen;
  }

  public void setImporteGravamen(BigDecimal importeGravamen) {
    this.importeGravamen = importeGravamen;
  }

  public Garantia vri(BigDecimal vri) {
    this.vri = vri;
    return this;
  }

  /**
   * VRI
   * @return vri
   **/
  @JsonProperty("vri")
  @ApiModelProperty(value = "VRI")
  public BigDecimal getVri() {
    return vri;
  }

  public void setVri(BigDecimal vri) {
    this.vri = vri;
  }

  public Garantia moneda(CodigosMonedas moneda) {
    this.moneda = moneda;
    return this;
  }

  /**
   * Get moneda
   * @return moneda
   **/
  @JsonProperty("moneda")
  @ApiModelProperty(value = "")
  public CodigosMonedas getMoneda() {
    return moneda;
  }

  public void setMoneda(CodigosMonedas moneda) {
    this.moneda = moneda;
  }

  public Garantia funciones(String funciones) {
    this.funciones = funciones;
    return this;
  }

  /**
   * Texto de FUNCIONES
   * @return funciones
   **/
  @JsonProperty("funciones")
  @ApiModelProperty(value = "Texto de FUNCIONES")
  public String getFunciones() {
    return funciones;
  }

  public void setFunciones(String funciones) {
    this.funciones = funciones;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Garantia garantia = (Garantia) o;
    return Objects.equals(this.numero, garantia.numero) &&
        Objects.equals(this.ambito, garantia.ambito) &&
        Objects.equals(this.porcentaje, garantia.porcentaje) &&
        Objects.equals(this.importe, garantia.importe) &&
        Objects.equals(this.tipo, garantia.tipo) &&
        Objects.equals(this.importeGravamen, garantia.importeGravamen) &&
        Objects.equals(this.vri, garantia.vri) &&
        Objects.equals(this.moneda, garantia.moneda) &&
        Objects.equals(this.funciones, garantia.funciones);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numero, ambito, porcentaje, importe, tipo, importeGravamen, vri, moneda, funciones);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Garantia {\n");
    
    sb.append("    numero: ").append(toIndentedString(numero)).append("\n");
    sb.append("    ambito: ").append(toIndentedString(ambito)).append("\n");
    sb.append("    porcentaje: ").append(toIndentedString(porcentaje)).append("\n");
    sb.append("    importe: ").append(toIndentedString(importe)).append("\n");
    sb.append("    tipo: ").append(toIndentedString(tipo)).append("\n");
    sb.append("    importeGravamen: ").append(toIndentedString(importeGravamen)).append("\n");
    sb.append("    vri: ").append(toIndentedString(vri)).append("\n");
    sb.append("    moneda: ").append(toIndentedString(moneda)).append("\n");
    sb.append("    funciones: ").append(toIndentedString(funciones)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

