/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;
import java.util.Objects;

/**
 * GestionCobranza
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class GestionCobranza   {
  @JsonProperty("fecha")
  private Date fecha = null;

  @JsonProperty("usuario")
  private Usuario usuario = null;

  @JsonProperty("accion")
  private String accion = null;

  @JsonProperty("efecto")
  private String efecto = null;

  @JsonProperty("contacto")
  private String contacto = null;

  @JsonProperty("motivoNoPago")
  private String motivoNoPago = null;

  @JsonProperty("fechaProximaAccion")
  private Date fechaProximaAccion = null;

  @JsonProperty("observaciones")
  private String observaciones = null;

  @JsonProperty("telefono")
  private String telefono = null;

  public GestionCobranza fecha(Date fecha) {
    this.fecha = fecha;
    return this;
  }

  /**
   * Fecha
   * @return fecha
   **/
  @JsonProperty("fecha")
  @ApiModelProperty(value = "Fecha")
  public Date getFecha() {
    return fecha;
  }

  public void setFecha(Date fecha) {
    this.fecha = fecha;
  }

  public GestionCobranza usuario(Usuario usuario) {
    this.usuario = usuario;
    return this;
  }

  /**
   * Usuario
   * @return usuario
   **/
  @JsonProperty("usuario")
  @ApiModelProperty(value = "Usuario")
  public Usuario getUsuario() {
    return usuario;
  }

  public void setUsuario(Usuario usuario) {
    this.usuario = usuario;
  }

  public GestionCobranza accion(String accion) {
    this.accion = accion;
    return this;
  }

  /**
   * Acción
   * @return accion
   **/
  @JsonProperty("accion")
  @ApiModelProperty(value = "Acción")
  public String getAccion() {
    return accion;
  }

  public void setAccion(String accion) {
    this.accion = accion;
  }

  public GestionCobranza efecto(String efecto) {
    this.efecto = efecto;
    return this;
  }

  /**
   * Efecto
   * @return efecto
   **/
  @JsonProperty("efecto")
  @ApiModelProperty(value = "Efecto")
  public String getEfecto() {
    return efecto;
  }

  public void setEfecto(String efecto) {
    this.efecto = efecto;
  }

  public GestionCobranza contacto(String contacto) {
    this.contacto = contacto;
    return this;
  }

  /**
   * Contacto
   * @return contacto
   **/
  @JsonProperty("contacto")
  @ApiModelProperty(value = "Contacto")
  public String getContacto() {
    return contacto;
  }

  public void setContacto(String contacto) {
    this.contacto = contacto;
  }

  public GestionCobranza motivoNoPago(String motivoNoPago) {
    this.motivoNoPago = motivoNoPago;
    return this;
  }

  /**
   * Motivo no pago
   * @return motivoNoPago
   **/
  @JsonProperty("motivoNoPago")
  @ApiModelProperty(value = "Motivo no pago")
  public String getMotivoNoPago() {
    return motivoNoPago;
  }

  public void setMotivoNoPago(String motivoNoPago) {
    this.motivoNoPago = motivoNoPago;
  }

  public GestionCobranza fechaProximaAccion(Date fechaProximaAccion) {
    this.fechaProximaAccion = fechaProximaAccion;
    return this;
  }

  /**
   * Fecha próxima acción
   * @return fechaProximaAccion
   **/
  @JsonProperty("fechaProximaAccion")
  @ApiModelProperty(value = "Fecha próxima acción")
  public Date getFechaProximaAccion() {
    return fechaProximaAccion;
  }

  public void setFechaProximaAccion(Date fechaProximaAccion) {
    this.fechaProximaAccion = fechaProximaAccion;
  }

  public GestionCobranza observaciones(String observaciones) {
    this.observaciones = observaciones;
    return this;
  }

  /**
   * Observaciones
   * @return observaciones
   **/
  @JsonProperty("observaciones")
  @ApiModelProperty(value = "Observaciones")
  public String getObservaciones() {
    return observaciones;
  }

  public void setObservaciones(String observaciones) {
    this.observaciones = observaciones;
  }

  public GestionCobranza telefono(String telefono) {
    this.telefono = telefono;
    return this;
  }

  /**
   * Telefono
   * @return telefono
   **/
  @JsonProperty("telefono")
  @ApiModelProperty(value = "Telefono")
  public String getTelefono() {
    return telefono;
  }

  public void setTelefono(String telefono) {
    this.telefono = telefono;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GestionCobranza gestionCobranza = (GestionCobranza) o;
    return Objects.equals(this.fecha, gestionCobranza.fecha) &&
        Objects.equals(this.usuario, gestionCobranza.usuario) &&
        Objects.equals(this.accion, gestionCobranza.accion) &&
        Objects.equals(this.efecto, gestionCobranza.efecto) &&
        Objects.equals(this.contacto, gestionCobranza.contacto) &&
        Objects.equals(this.motivoNoPago, gestionCobranza.motivoNoPago) &&
        Objects.equals(this.fechaProximaAccion, gestionCobranza.fechaProximaAccion) &&
        Objects.equals(this.observaciones, gestionCobranza.observaciones) &&
        Objects.equals(this.telefono, gestionCobranza.telefono);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fecha, usuario, accion, efecto, contacto, motivoNoPago, fechaProximaAccion, observaciones, telefono);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GestionCobranza {\n");
    
    sb.append("    fecha: ").append(toIndentedString(fecha)).append("\n");
    sb.append("    usuario: ").append(toIndentedString(usuario)).append("\n");
    sb.append("    accion: ").append(toIndentedString(accion)).append("\n");
    sb.append("    efecto: ").append(toIndentedString(efecto)).append("\n");
    sb.append("    contacto: ").append(toIndentedString(contacto)).append("\n");
    sb.append("    motivoNoPago: ").append(toIndentedString(motivoNoPago)).append("\n");
    sb.append("    fechaProximaAccion: ").append(toIndentedString(fechaProximaAccion)).append("\n");
    sb.append("    observaciones: ").append(toIndentedString(observaciones)).append("\n");
    sb.append("    telefono: ").append(toIndentedString(telefono)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

