/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Grupo de Producto
 */
@ApiModel(description = "Grupo de Producto")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class GrupoProducto   {
  @JsonProperty("codigo")
  private String codigo = null;

  @JsonProperty("descripcion")
  private String descripcion = null;

  @JsonProperty("saldoSoles")
  private BigDecimal saldoSoles = null;

  @JsonProperty("saldoDolares")
  private BigDecimal saldoDolares = null;

  @JsonProperty("totalSoles")
  private BigDecimal totalSoles = null;

  @JsonProperty("totalDolares")
  private BigDecimal totalDolares = null;

  @JsonProperty("calificacionSbs")
  private String calificacionSbs = null;

  @JsonProperty("calificacionBif")
  private String calificacionBif = null;

  @JsonProperty("productos")
  private List<Producto> productos = null;

  public GrupoProducto codigo(String codigo) {
    this.codigo = codigo;
    return this;
  }

  /**
   * Código
   * @return codigo
   **/
  @JsonProperty("codigo")
  @ApiModelProperty(value = "Código")
  public String getCodigo() {
    return codigo;
  }

  public void setCodigo(String codigo) {
    this.codigo = codigo;
  }

  public GrupoProducto descripcion(String descripcion) {
    this.descripcion = descripcion;
    return this;
  }

  /**
   * Descripción
   * @return descripcion
   **/
  @JsonProperty("descripcion")
  @ApiModelProperty(value = "Descripción")
  public String getDescripcion() {
    return descripcion;
  }

  public void setDescripcion(String descripcion) {
    this.descripcion = descripcion;
  }

  public GrupoProducto saldoSoles(BigDecimal saldoSoles) {
    this.saldoSoles = saldoSoles;
    return this;
  }

  /**
   * Saldo Soles
   * @return saldoSoles
   **/
  @JsonProperty("saldoSoles")
  @ApiModelProperty(value = "Saldo Soles")
  public BigDecimal getSaldoSoles() {
    return saldoSoles;
  }

  public void setSaldoSoles(BigDecimal saldoSoles) {
    this.saldoSoles = saldoSoles;
  }

  public GrupoProducto saldoDolares(BigDecimal saldoDolares) {
    this.saldoDolares = saldoDolares;
    return this;
  }

  /**
   * Saldo Dólares
   * @return saldoDolares
   **/
  @JsonProperty("saldoDolares")
  @ApiModelProperty(value = "Saldo Dólares")
  public BigDecimal getSaldoDolares() {
    return saldoDolares;
  }

  public void setSaldoDolares(BigDecimal saldoDolares) {
    this.saldoDolares = saldoDolares;
  }

  public GrupoProducto totalSoles(BigDecimal totalSoles) {
    this.totalSoles = totalSoles;
    return this;
  }

  /**
   * Total Soles
   * @return totalSoles
   **/
  @JsonProperty("totalSoles")
  @ApiModelProperty(value = "Total Soles")
  public BigDecimal getTotalSoles() {
    return totalSoles;
  }

  public void setTotalSoles(BigDecimal totalSoles) {
    this.totalSoles = totalSoles;
  }

  public GrupoProducto totalDolares(BigDecimal totalDolares) {
    this.totalDolares = totalDolares;
    return this;
  }

  /**
   * Total Dólares
   * @return totalDolares
   **/
  @JsonProperty("totalDolares")
  @ApiModelProperty(value = "Total Dólares")
  public BigDecimal getTotalDolares() {
    return totalDolares;
  }

  public void setTotalDolares(BigDecimal totalDolares) {
    this.totalDolares = totalDolares;
  }

  public GrupoProducto calificacionSbs(String calificacionSbs) {
    this.calificacionSbs = calificacionSbs;
    return this;
  }

  /**
   * Calificacion SBS
   * @return calificacionSbs
   **/
  @JsonProperty("calificacionSbs")
  @ApiModelProperty(value = "Calificacion SBS")
  public String getCalificacionSbs() {
    return calificacionSbs;
  }

  public void setCalificacionSbs(String calificacionSbs) {
    this.calificacionSbs = calificacionSbs;
  }

  public GrupoProducto calificacionBif(String calificacionBif) {
    this.calificacionBif = calificacionBif;
    return this;
  }

  /**
   * Calificacion BIF
   * @return calificacionBif
   **/
  @JsonProperty("calificacionBif")
  @ApiModelProperty(value = "Calificacion BIF")
  public String getCalificacionBif() {
    return calificacionBif;
  }

  public void setCalificacionBif(String calificacionBif) {
    this.calificacionBif = calificacionBif;
  }

  public GrupoProducto productos(List<Producto> productos) {
    this.productos = productos;
    return this;
  }

  public GrupoProducto addProductosItem(Producto productosItem) {
    if (this.productos == null) {
      this.productos = new ArrayList<Producto>();
    }
    this.productos.add(productosItem);
    return this;
  }

  /**
   * Get productos
   * @return productos
   **/
  @JsonProperty("productos")
  @ApiModelProperty(value = "")
  public List<Producto> getProductos() {
    return productos;
  }

  public void setProductos(List<Producto> productos) {
    this.productos = productos;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GrupoProducto grupoProducto = (GrupoProducto) o;
    return Objects.equals(this.codigo, grupoProducto.codigo) &&
        Objects.equals(this.descripcion, grupoProducto.descripcion) &&
        Objects.equals(this.saldoSoles, grupoProducto.saldoSoles) &&
        Objects.equals(this.saldoDolares, grupoProducto.saldoDolares) &&
        Objects.equals(this.totalSoles, grupoProducto.totalSoles) &&
        Objects.equals(this.totalDolares, grupoProducto.totalDolares) &&
        Objects.equals(this.calificacionSbs, grupoProducto.calificacionSbs) &&
        Objects.equals(this.calificacionBif, grupoProducto.calificacionBif) &&
        Objects.equals(this.productos, grupoProducto.productos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codigo, descripcion, saldoSoles, saldoDolares, totalSoles, totalDolares, calificacionSbs, calificacionBif, productos);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GrupoProducto {\n");
    
    sb.append("    codigo: ").append(toIndentedString(codigo)).append("\n");
    sb.append("    descripcion: ").append(toIndentedString(descripcion)).append("\n");
    sb.append("    saldoSoles: ").append(toIndentedString(saldoSoles)).append("\n");
    sb.append("    saldoDolares: ").append(toIndentedString(saldoDolares)).append("\n");
    sb.append("    totalSoles: ").append(toIndentedString(totalSoles)).append("\n");
    sb.append("    totalDolares: ").append(toIndentedString(totalDolares)).append("\n");
    sb.append("    calificacionSbs: ").append(toIndentedString(calificacionSbs)).append("\n");
    sb.append("    calificacionBif: ").append(toIndentedString(calificacionBif)).append("\n");
    sb.append("    productos: ").append(toIndentedString(productos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

