/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Objects;

/**
 * Solicitud comercial, Propuesta de credito por clientes. Interacciones con el banco.
 */
@ApiModel(description = "Solicitud comercial, Propuesta de credito por clientes. Interacciones con el banco.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class InteraccionComercial   {
  @JsonProperty("propuesta")
  private Propuesta propuesta = null;

  @JsonProperty("estado")
  private String estado = null;

  @JsonProperty("producto")
  private Producto producto = null;

  @JsonProperty("cliente")
  private Cliente cliente = null;

  @JsonProperty("nivelAprobacion")
  private String nivelAprobacion = null;

  @JsonProperty("fechaDeAprobacion")
  private Date fechaDeAprobacion = null;

  @JsonProperty("efl")
  private BigDecimal efl = null;

  @JsonProperty("equifax")
  private BigDecimal equifax = null;

  @JsonProperty("moneda")
  private CodigosMonedas moneda = null;

  @JsonProperty("monto")
  private BigDecimal monto = null;

  @JsonProperty("descIncrementoDeRiesgo")
  private String descIncrementoDeRiesgo = null;

  @JsonProperty("plazo")
  private BigDecimal plazo = null;

  @JsonProperty("periodoPlazo")
  private String periodoPlazo = null;

  @JsonProperty("condicionesTipo")
  private String condicionesTipo = null;

  @JsonProperty("condicionesDescripcion")
  private String condicionesDescripcion = null;

  @JsonProperty("tasaSoles")
  private BigDecimal tasaSoles = null;

  @JsonProperty("tasaDolares")
  private BigDecimal tasaDolares = null;

  @JsonProperty("agencia")
  private String agencia = null;

  @JsonProperty("agenciaApertura")
  private String agenciaApertura = null;

  @JsonProperty("comAval")
  private BigDecimal comAval = null;

  @JsonProperty("textoCondicionCredito")
  private String textoCondicionCredito = null;

  @JsonProperty("montoD")
  private BigDecimal montoD = null;

  @JsonProperty("condicionesTipoD")
  private String condicionesTipoD = null;

  @JsonProperty("condicionesDescripcionD")
  private String condicionesDescripcionD = null;

  @JsonProperty("tasaSolesD")
  private BigDecimal tasaSolesD = null;

  @JsonProperty("tasaDolaresD")
  private BigDecimal tasaDolaresD = null;

  @JsonProperty("comAvalD")
  private BigDecimal comAvalD = null;

  @JsonProperty("plazoD")
  private BigDecimal plazoD = null;

  @JsonProperty("periodoPlazoD")
  private String periodoPlazoD = null;

  @JsonProperty("estadoD")
  private String estadoD = null;

  @JsonProperty("avisoVencimientoD")
  private String avisoVencimientoD = null;

  @JsonProperty("situacionD")
  private String situacionD = null;

  @JsonProperty("analistaD")
  private String analistaD = null;

  @JsonProperty("fechaAsignacionD")
  private Date fechaAsignacionD = null;

  @JsonProperty("certDepoD")
  private String certDepoD = null;

  public InteraccionComercial propuesta(Propuesta propuesta) {
    this.propuesta = propuesta;
    return this;
  }

  /**
   * Get propuesta
   * @return propuesta
   **/
  @JsonProperty("propuesta")
  @ApiModelProperty(value = "")
  public Propuesta getPropuesta() {
    return propuesta;
  }

  public void setPropuesta(Propuesta propuesta) {
    this.propuesta = propuesta;
  }

  public InteraccionComercial estado(String estado) {
    this.estado = estado;
    return this;
  }

  /**
   * Estado
   * @return estado
   **/
  @JsonProperty("estado")
  @ApiModelProperty(value = "Estado")
  public String getEstado() {
    return estado;
  }

  public void setEstado(String estado) {
    this.estado = estado;
  }

  public InteraccionComercial producto(Producto producto) {
    this.producto = producto;
    return this;
  }

  /**
   * Get producto
   * @return producto
   **/
  @JsonProperty("producto")
  @ApiModelProperty(value = "")
  public Producto getProducto() {
    return producto;
  }

  public void setProducto(Producto producto) {
    this.producto = producto;
  }

  public InteraccionComercial cliente(Cliente cliente) {
    this.cliente = cliente;
    return this;
  }

  /**
   * Get cliente
   * @return cliente
   **/
  @JsonProperty("cliente")
  @ApiModelProperty(value = "")
  public Cliente getCliente() {
    return cliente;
  }

  public void setCliente(Cliente cliente) {
    this.cliente = cliente;
  }

  public InteraccionComercial nivelAprobacion(String nivelAprobacion) {
    this.nivelAprobacion = nivelAprobacion;
    return this;
  }

  /**
   * Nivel Aprobación
   * @return nivelAprobacion
   **/
  @JsonProperty("nivelAprobacion")
  @ApiModelProperty(value = "Nivel Aprobación")
  public String getNivelAprobacion() {
    return nivelAprobacion;
  }

  public void setNivelAprobacion(String nivelAprobacion) {
    this.nivelAprobacion = nivelAprobacion;
  }

  public InteraccionComercial fechaDeAprobacion(Date fechaDeAprobacion) {
    this.fechaDeAprobacion = fechaDeAprobacion;
    return this;
  }

  /**
   * Fecha de Aprobación
   * @return fechaDeAprobacion
   **/
  @JsonProperty("fechaDeAprobacion")
  @ApiModelProperty(value = "Fecha de Aprobación")
  public Date getFechaDeAprobacion() {
    return fechaDeAprobacion;
  }

  public void setFechaDeAprobacion(Date fechaDeAprobacion) {
    this.fechaDeAprobacion = fechaDeAprobacion;
  }

  public InteraccionComercial efl(BigDecimal efl) {
    this.efl = efl;
    return this;
  }

  /**
   * EFL
   * @return efl
   **/
  @JsonProperty("efl")
  @ApiModelProperty(value = "EFL")
  public BigDecimal getEfl() {
    return efl;
  }

  public void setEfl(BigDecimal efl) {
    this.efl = efl;
  }

  public InteraccionComercial equifax(BigDecimal equifax) {
    this.equifax = equifax;
    return this;
  }

  /**
   * Equifax
   * @return equifax
   **/
  @JsonProperty("equifax")
  @ApiModelProperty(value = "Equifax")
  public BigDecimal getEquifax() {
    return equifax;
  }

  public void setEquifax(BigDecimal equifax) {
    this.equifax = equifax;
  }

  public InteraccionComercial moneda(CodigosMonedas moneda) {
    this.moneda = moneda;
    return this;
  }

  /**
   * Get moneda
   * @return moneda
   **/
  @JsonProperty("moneda")
  @ApiModelProperty(value = "")
  public CodigosMonedas getMoneda() {
    return moneda;
  }

  public void setMoneda(CodigosMonedas moneda) {
    this.moneda = moneda;
  }

  public InteraccionComercial monto(BigDecimal monto) {
    this.monto = monto;
    return this;
  }

  /**
   * Monto
   * @return monto
   **/
  @JsonProperty("monto")
  @ApiModelProperty(value = "Monto")
  public BigDecimal getMonto() {
    return monto;
  }

  public void setMonto(BigDecimal monto) {
    this.monto = monto;
  }

  public InteraccionComercial descIncrementoDeRiesgo(String descIncrementoDeRiesgo) {
    this.descIncrementoDeRiesgo = descIncrementoDeRiesgo;
    return this;
  }

  /**
   * Desc. Incremento de Riesgo
   * @return descIncrementoDeRiesgo
   **/
  @JsonProperty("descIncrementoDeRiesgo")
  @ApiModelProperty(value = "Desc. Incremento de Riesgo")
  public String getDescIncrementoDeRiesgo() {
    return descIncrementoDeRiesgo;
  }

  public void setDescIncrementoDeRiesgo(String descIncrementoDeRiesgo) {
    this.descIncrementoDeRiesgo = descIncrementoDeRiesgo;
  }

  public InteraccionComercial plazo(BigDecimal plazo) {
    this.plazo = plazo;
    return this;
  }

  /**
   * Plazo
   * @return plazo
   **/
  @JsonProperty("plazo")
  @ApiModelProperty(value = "Plazo")
  public BigDecimal getPlazo() {
    return plazo;
  }

  public void setPlazo(BigDecimal plazo) {
    this.plazo = plazo;
  }

  public InteraccionComercial periodoPlazo(String periodoPlazo) {
    this.periodoPlazo = periodoPlazo;
    return this;
  }

  /**
   * Periodo (Plazo)
   * @return periodoPlazo
   **/
  @JsonProperty("periodoPlazo")
  @ApiModelProperty(value = "Periodo (Plazo)")
  public String getPeriodoPlazo() {
    return periodoPlazo;
  }

  public void setPeriodoPlazo(String periodoPlazo) {
    this.periodoPlazo = periodoPlazo;
  }

  public InteraccionComercial condicionesTipo(String condicionesTipo) {
    this.condicionesTipo = condicionesTipo;
    return this;
  }

  /**
   * Condiciones (Tipo)
   * @return condicionesTipo
   **/
  @JsonProperty("condicionesTipo")
  @ApiModelProperty(value = "Condiciones (Tipo)")
  public String getCondicionesTipo() {
    return condicionesTipo;
  }

  public void setCondicionesTipo(String condicionesTipo) {
    this.condicionesTipo = condicionesTipo;
  }

  public InteraccionComercial condicionesDescripcion(String condicionesDescripcion) {
    this.condicionesDescripcion = condicionesDescripcion;
    return this;
  }

  /**
   * Condiciones (Descripción)
   * @return condicionesDescripcion
   **/
  @JsonProperty("condicionesDescripcion")
  @ApiModelProperty(value = "Condiciones (Descripción)")
  public String getCondicionesDescripcion() {
    return condicionesDescripcion;
  }

  public void setCondicionesDescripcion(String condicionesDescripcion) {
    this.condicionesDescripcion = condicionesDescripcion;
  }

  public InteraccionComercial tasaSoles(BigDecimal tasaSoles) {
    this.tasaSoles = tasaSoles;
    return this;
  }

  /**
   * Tasa Soles
   * @return tasaSoles
   **/
  @JsonProperty("tasaSoles")
  @ApiModelProperty(value = "Tasa Soles")
  public BigDecimal getTasaSoles() {
    return tasaSoles;
  }

  public void setTasaSoles(BigDecimal tasaSoles) {
    this.tasaSoles = tasaSoles;
  }

  public InteraccionComercial tasaDolares(BigDecimal tasaDolares) {
    this.tasaDolares = tasaDolares;
    return this;
  }

  /**
   * Tasa Dolares
   * @return tasaDolares
   **/
  @JsonProperty("tasaDolares")
  @ApiModelProperty(value = "Tasa Dolares")
  public BigDecimal getTasaDolares() {
    return tasaDolares;
  }

  public void setTasaDolares(BigDecimal tasaDolares) {
    this.tasaDolares = tasaDolares;
  }

  public InteraccionComercial agencia(String agencia) {
    this.agencia = agencia;
    return this;
  }

  /**
   * Agencia
   * @return agencia
   **/
  @JsonProperty("agencia")
  @ApiModelProperty(value = "Agencia")
  public String getAgencia() {
    return agencia;
  }

  public void setAgencia(String agencia) {
    this.agencia = agencia;
  }

  public InteraccionComercial agenciaApertura(String agenciaApertura) {
    this.agenciaApertura = agenciaApertura;
    return this;
  }

  /**
   * Agencia de apertura de la cuenta
   * @return agenciaApertura
   **/
  @JsonProperty("agenciaApertura")
  @ApiModelProperty(value = "Agencia de apertura de la cuenta")
  public String getAgenciaApertura() {
    return agenciaApertura;
  }

  public void setAgenciaApertura(String agenciaApertura) {
    this.agenciaApertura = agenciaApertura;
  }

  public InteraccionComercial comAval(BigDecimal comAval) {
    this.comAval = comAval;
    return this;
  }

  /**
   * Com.Aval
   * @return comAval
   **/
  @JsonProperty("comAval")
  @ApiModelProperty(value = "Com.Aval")
  public BigDecimal getComAval() {
    return comAval;
  }

  public void setComAval(BigDecimal comAval) {
    this.comAval = comAval;
  }

  public InteraccionComercial textoCondicionCredito(String textoCondicionCredito) {
    this.textoCondicionCredito = textoCondicionCredito;
    return this;
  }

  /**
   * Texto de la Condición de Crédito
   * @return textoCondicionCredito
   **/
  @JsonProperty("textoCondicionCredito")
  @ApiModelProperty(value = "Texto de la Condición de Crédito")
  public String getTextoCondicionCredito() {
    return textoCondicionCredito;
  }

  public void setTextoCondicionCredito(String textoCondicionCredito) {
    this.textoCondicionCredito = textoCondicionCredito;
  }

  public InteraccionComercial montoD(BigDecimal montoD) {
    this.montoD = montoD;
    return this;
  }

  /**
   * MONTDE
   * @return montoD
   **/
  @JsonProperty("montoD")
  @ApiModelProperty(value = "MONTDE")
  public BigDecimal getMontoD() {
    return montoD;
  }

  public void setMontoD(BigDecimal montoD) {
    this.montoD = montoD;
  }

  public InteraccionComercial condicionesTipoD(String condicionesTipoD) {
    this.condicionesTipoD = condicionesTipoD;
    return this;
  }

  /**
   * PLPTDE
   * @return condicionesTipoD
   **/
  @JsonProperty("condicionesTipoD")
  @ApiModelProperty(value = "PLPTDE")
  public String getCondicionesTipoD() {
    return condicionesTipoD;
  }

  public void setCondicionesTipoD(String condicionesTipoD) {
    this.condicionesTipoD = condicionesTipoD;
  }

  public InteraccionComercial condicionesDescripcionD(String condicionesDescripcionD) {
    this.condicionesDescripcionD = condicionesDescripcionD;
    return this;
  }

  /**
   * DTASDE
   * @return condicionesDescripcionD
   **/
  @JsonProperty("condicionesDescripcionD")
  @ApiModelProperty(value = "DTASDE")
  public String getCondicionesDescripcionD() {
    return condicionesDescripcionD;
  }

  public void setCondicionesDescripcionD(String condicionesDescripcionD) {
    this.condicionesDescripcionD = condicionesDescripcionD;
  }

  public InteraccionComercial tasaSolesD(BigDecimal tasaSolesD) {
    this.tasaSolesD = tasaSolesD;
    return this;
  }

  /**
   * PLTRDE
   * @return tasaSolesD
   **/
  @JsonProperty("tasaSolesD")
  @ApiModelProperty(value = "PLTRDE")
  public BigDecimal getTasaSolesD() {
    return tasaSolesD;
  }

  public void setTasaSolesD(BigDecimal tasaSolesD) {
    this.tasaSolesD = tasaSolesD;
  }

  public InteraccionComercial tasaDolaresD(BigDecimal tasaDolaresD) {
    this.tasaDolaresD = tasaDolaresD;
    return this;
  }

  /**
   * PLTVDE
   * @return tasaDolaresD
   **/
  @JsonProperty("tasaDolaresD")
  @ApiModelProperty(value = "PLTVDE")
  public BigDecimal getTasaDolaresD() {
    return tasaDolaresD;
  }

  public void setTasaDolaresD(BigDecimal tasaDolaresD) {
    this.tasaDolaresD = tasaDolaresD;
  }

  public InteraccionComercial comAvalD(BigDecimal comAvalD) {
    this.comAvalD = comAvalD;
    return this;
  }

  /**
   * PLTCXA
   * @return comAvalD
   **/
  @JsonProperty("comAvalD")
  @ApiModelProperty(value = "PLTCXA")
  public BigDecimal getComAvalD() {
    return comAvalD;
  }

  public void setComAvalD(BigDecimal comAvalD) {
    this.comAvalD = comAvalD;
  }

  public InteraccionComercial plazoD(BigDecimal plazoD) {
    this.plazoD = plazoD;
    return this;
  }

  /**
   * PLTPDE
   * @return plazoD
   **/
  @JsonProperty("plazoD")
  @ApiModelProperty(value = "PLTPDE")
  public BigDecimal getPlazoD() {
    return plazoD;
  }

  public void setPlazoD(BigDecimal plazoD) {
    this.plazoD = plazoD;
  }

  public InteraccionComercial periodoPlazoD(String periodoPlazoD) {
    this.periodoPlazoD = periodoPlazoD;
    return this;
  }

  /**
   * PLTUDE
   * @return periodoPlazoD
   **/
  @JsonProperty("periodoPlazoD")
  @ApiModelProperty(value = "PLTUDE")
  public String getPeriodoPlazoD() {
    return periodoPlazoD;
  }

  public void setPeriodoPlazoD(String periodoPlazoD) {
    this.periodoPlazoD = periodoPlazoD;
  }

  public InteraccionComercial estadoD(String estadoD) {
    this.estadoD = estadoD;
    return this;
  }

  /**
   * PLTDXX
   * @return estadoD
   **/
  @JsonProperty("estadoD")
  @ApiModelProperty(value = "PLTDXX")
  public String getEstadoD() {
    return estadoD;
  }

  public void setEstadoD(String estadoD) {
    this.estadoD = estadoD;
  }

  public InteraccionComercial avisoVencimientoD(String avisoVencimientoD) {
    this.avisoVencimientoD = avisoVencimientoD;
    return this;
  }

  /**
   * PLTTRT
   * @return avisoVencimientoD
   **/
  @JsonProperty("avisoVencimientoD")
  @ApiModelProperty(value = "PLTTRT")
  public String getAvisoVencimientoD() {
    return avisoVencimientoD;
  }

  public void setAvisoVencimientoD(String avisoVencimientoD) {
    this.avisoVencimientoD = avisoVencimientoD;
  }

  public InteraccionComercial situacionD(String situacionD) {
    this.situacionD = situacionD;
    return this;
  }

  /**
   * SITPRO
   * @return situacionD
   **/
  @JsonProperty("situacionD")
  @ApiModelProperty(value = "SITPRO")
  public String getSituacionD() {
    return situacionD;
  }

  public void setSituacionD(String situacionD) {
    this.situacionD = situacionD;
  }

  public InteraccionComercial analistaD(String analistaD) {
    this.analistaD = analistaD;
    return this;
  }

  /**
   * DANALI
   * @return analistaD
   **/
  @JsonProperty("analistaD")
  @ApiModelProperty(value = "DANALI")
  public String getAnalistaD() {
    return analistaD;
  }

  public void setAnalistaD(String analistaD) {
    this.analistaD = analistaD;
  }

  public InteraccionComercial fechaAsignacionD(Date fechaAsignacionD) {
    this.fechaAsignacionD = fechaAsignacionD;
    return this;
  }

  /**
   * FECASG
   * @return fechaAsignacionD
   **/
  @JsonProperty("fechaAsignacionD")
  @ApiModelProperty(value = "FECASG")
  public Date getFechaAsignacionD() {
    return fechaAsignacionD;
  }

  public void setFechaAsignacionD(Date fechaAsignacionD) {
    this.fechaAsignacionD = fechaAsignacionD;
  }

  public InteraccionComercial certDepoD(String certDepoD) {
    this.certDepoD = certDepoD;
    return this;
  }

  /**
   * GL_PLGNDP
   * @return certDepoD
   **/
  @JsonProperty("certDepoD")
  @ApiModelProperty(value = "GL_PLGNDP")
  public String getCertDepoD() {
    return certDepoD;
  }

  public void setCertDepoD(String certDepoD) {
    this.certDepoD = certDepoD;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InteraccionComercial interaccionComercial = (InteraccionComercial) o;
    return Objects.equals(this.propuesta, interaccionComercial.propuesta) &&
        Objects.equals(this.estado, interaccionComercial.estado) &&
        Objects.equals(this.producto, interaccionComercial.producto) &&
        Objects.equals(this.cliente, interaccionComercial.cliente) &&
        Objects.equals(this.nivelAprobacion, interaccionComercial.nivelAprobacion) &&
        Objects.equals(this.fechaDeAprobacion, interaccionComercial.fechaDeAprobacion) &&
        Objects.equals(this.efl, interaccionComercial.efl) &&
        Objects.equals(this.equifax, interaccionComercial.equifax) &&
        Objects.equals(this.moneda, interaccionComercial.moneda) &&
        Objects.equals(this.monto, interaccionComercial.monto) &&
        Objects.equals(this.descIncrementoDeRiesgo, interaccionComercial.descIncrementoDeRiesgo) &&
        Objects.equals(this.plazo, interaccionComercial.plazo) &&
        Objects.equals(this.periodoPlazo, interaccionComercial.periodoPlazo) &&
        Objects.equals(this.condicionesTipo, interaccionComercial.condicionesTipo) &&
        Objects.equals(this.condicionesDescripcion, interaccionComercial.condicionesDescripcion) &&
        Objects.equals(this.tasaSoles, interaccionComercial.tasaSoles) &&
        Objects.equals(this.tasaDolares, interaccionComercial.tasaDolares) &&
        Objects.equals(this.agencia, interaccionComercial.agencia) &&
        Objects.equals(this.agenciaApertura, interaccionComercial.agenciaApertura) &&
        Objects.equals(this.comAval, interaccionComercial.comAval) &&
        Objects.equals(this.textoCondicionCredito, interaccionComercial.textoCondicionCredito) &&
        Objects.equals(this.montoD, interaccionComercial.montoD) &&
        Objects.equals(this.condicionesTipoD, interaccionComercial.condicionesTipoD) &&
        Objects.equals(this.condicionesDescripcionD, interaccionComercial.condicionesDescripcionD) &&
        Objects.equals(this.tasaSolesD, interaccionComercial.tasaSolesD) &&
        Objects.equals(this.tasaDolaresD, interaccionComercial.tasaDolaresD) &&
        Objects.equals(this.comAvalD, interaccionComercial.comAvalD) &&
        Objects.equals(this.plazoD, interaccionComercial.plazoD) &&
        Objects.equals(this.periodoPlazoD, interaccionComercial.periodoPlazoD) &&
        Objects.equals(this.estadoD, interaccionComercial.estadoD) &&
        Objects.equals(this.avisoVencimientoD, interaccionComercial.avisoVencimientoD) &&
        Objects.equals(this.situacionD, interaccionComercial.situacionD) &&
        Objects.equals(this.analistaD, interaccionComercial.analistaD) &&
        Objects.equals(this.fechaAsignacionD, interaccionComercial.fechaAsignacionD) &&
        Objects.equals(this.certDepoD, interaccionComercial.certDepoD);
  }

  @Override
  public int hashCode() {
    return Objects.hash(propuesta, estado, producto, cliente, nivelAprobacion, fechaDeAprobacion, efl, equifax, moneda, monto, descIncrementoDeRiesgo, plazo, periodoPlazo, condicionesTipo, condicionesDescripcion, tasaSoles, tasaDolares, agencia, agenciaApertura, comAval, textoCondicionCredito, montoD, condicionesTipoD, condicionesDescripcionD, tasaSolesD, tasaDolaresD, comAvalD, plazoD, periodoPlazoD, estadoD, avisoVencimientoD, situacionD, analistaD, fechaAsignacionD, certDepoD);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InteraccionComercial {\n");
    
    sb.append("    propuesta: ").append(toIndentedString(propuesta)).append("\n");
    sb.append("    estado: ").append(toIndentedString(estado)).append("\n");
    sb.append("    producto: ").append(toIndentedString(producto)).append("\n");
    sb.append("    cliente: ").append(toIndentedString(cliente)).append("\n");
    sb.append("    nivelAprobacion: ").append(toIndentedString(nivelAprobacion)).append("\n");
    sb.append("    fechaDeAprobacion: ").append(toIndentedString(fechaDeAprobacion)).append("\n");
    sb.append("    efl: ").append(toIndentedString(efl)).append("\n");
    sb.append("    equifax: ").append(toIndentedString(equifax)).append("\n");
    sb.append("    moneda: ").append(toIndentedString(moneda)).append("\n");
    sb.append("    monto: ").append(toIndentedString(monto)).append("\n");
    sb.append("    descIncrementoDeRiesgo: ").append(toIndentedString(descIncrementoDeRiesgo)).append("\n");
    sb.append("    plazo: ").append(toIndentedString(plazo)).append("\n");
    sb.append("    periodoPlazo: ").append(toIndentedString(periodoPlazo)).append("\n");
    sb.append("    condicionesTipo: ").append(toIndentedString(condicionesTipo)).append("\n");
    sb.append("    condicionesDescripcion: ").append(toIndentedString(condicionesDescripcion)).append("\n");
    sb.append("    tasaSoles: ").append(toIndentedString(tasaSoles)).append("\n");
    sb.append("    tasaDolares: ").append(toIndentedString(tasaDolares)).append("\n");
    sb.append("    agencia: ").append(toIndentedString(agencia)).append("\n");
    sb.append("    agenciaApertura: ").append(toIndentedString(agenciaApertura)).append("\n");
    sb.append("    comAval: ").append(toIndentedString(comAval)).append("\n");
    sb.append("    textoCondicionCredito: ").append(toIndentedString(textoCondicionCredito)).append("\n");
    sb.append("    montoD: ").append(toIndentedString(montoD)).append("\n");
    sb.append("    condicionesTipoD: ").append(toIndentedString(condicionesTipoD)).append("\n");
    sb.append("    condicionesDescripcionD: ").append(toIndentedString(condicionesDescripcionD)).append("\n");
    sb.append("    tasaSolesD: ").append(toIndentedString(tasaSolesD)).append("\n");
    sb.append("    tasaDolaresD: ").append(toIndentedString(tasaDolaresD)).append("\n");
    sb.append("    comAvalD: ").append(toIndentedString(comAvalD)).append("\n");
    sb.append("    plazoD: ").append(toIndentedString(plazoD)).append("\n");
    sb.append("    periodoPlazoD: ").append(toIndentedString(periodoPlazoD)).append("\n");
    sb.append("    estadoD: ").append(toIndentedString(estadoD)).append("\n");
    sb.append("    avisoVencimientoD: ").append(toIndentedString(avisoVencimientoD)).append("\n");
    sb.append("    situacionD: ").append(toIndentedString(situacionD)).append("\n");
    sb.append("    analistaD: ").append(toIndentedString(analistaD)).append("\n");
    sb.append("    fechaAsignacionD: ").append(toIndentedString(fechaAsignacionD)).append("\n");
    sb.append("    certDepoD: ").append(toIndentedString(certDepoD)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

