/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Item del catálogo de tablas del sistema (Departamentos, provincia, distrito, via, nivel de estudio,nacionalidad, cargo, profesiones, segmentos, productos del banco, sub productos del banco, estado civil, sexo, codigo de telefono, tipo de direccion)
 */
@ApiModel(description = "Item del catálogo de tablas del sistema (Departamentos, provincia, distrito, via, nivel de estudio,nacionalidad, cargo, profesiones, segmentos, productos del banco, sub productos del banco, estado civil, sexo, codigo de telefono, tipo de direccion)")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class ItemCatalogoTablas   {
  @JsonProperty("codigo")
  private String codigo = null;

  @JsonProperty("activo")
  private Boolean activo = null;

  @JsonProperty("descripcion")
  private String descripcion = null;

  public ItemCatalogoTablas codigo(String codigo) {
    this.codigo = codigo;
    return this;
  }

  /**
   * Código del ítem del catálogo
   * @return codigo
   **/
  @JsonProperty("codigo")
  @ApiModelProperty(value = "Código del ítem del catálogo")
  public String getCodigo() {
    return codigo;
  }

  public void setCodigo(String codigo) {
    this.codigo = codigo;
  }

  public ItemCatalogoTablas activo(Boolean activo) {
    this.activo = activo;
    return this;
  }

  /**
   * Indica si el ítem del catálogo está activo
   * @return activo
   **/
  @JsonProperty("activo")
  @ApiModelProperty(value = "Indica si el ítem del catálogo está activo")
  public Boolean isActivo() {
    return activo;
  }

  public void setActivo(Boolean activo) {
    this.activo = activo;
  }

  public ItemCatalogoTablas descripcion(String descripcion) {
    this.descripcion = descripcion;
    return this;
  }

  /**
   * Descripción del catálogo
   * @return descripcion
   **/
  @JsonProperty("descripcion")
  @ApiModelProperty(value = "Descripción del catálogo")
  public String getDescripcion() {
    return descripcion;
  }

  public void setDescripcion(String descripcion) {
    this.descripcion = descripcion;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemCatalogoTablas itemCatalogoTablas = (ItemCatalogoTablas) o;
    return Objects.equals(this.codigo, itemCatalogoTablas.codigo) &&
        Objects.equals(this.activo, itemCatalogoTablas.activo) &&
        Objects.equals(this.descripcion, itemCatalogoTablas.descripcion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codigo, activo, descripcion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemCatalogoTablas {\n");
    
    sb.append("    codigo: ").append(toIndentedString(codigo)).append("\n");
    sb.append("    activo: ").append(toIndentedString(activo)).append("\n");
    sb.append("    descripcion: ").append(toIndentedString(descripcion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

