/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Tipo de Producto
 */
public enum ModalidadesCheque {
  
  MISMO_BANCO("MISMO_BANCO"),
  
  BANCO_LOCAL("BANCO_LOCAL"),
  
  BANCO_EXTANJERO("BANCO_EXTANJERO");

  private String value;

  ModalidadesCheque(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ModalidadesCheque fromValue(String text) {
    for (ModalidadesCheque b : ModalidadesCheque.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

