/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Oficina
 */
@ApiModel(description = "Oficina")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class Oficina   {
  @JsonProperty("codigo")
  private String codigo = null;

  @JsonProperty("nombre")
  private String nombre = null;

  @JsonProperty("telefono")
  private Telefono telefono = null;

  public Oficina codigo(String codigo) {
    this.codigo = codigo;
    return this;
  }

  /**
   * Código de Oficina
   * @return codigo
   **/
  @JsonProperty("codigo")
  @ApiModelProperty(value = "Código de Oficina")
  public String getCodigo() {
    return codigo;
  }

  public void setCodigo(String codigo) {
    this.codigo = codigo;
  }

  public Oficina nombre(String nombre) {
    this.nombre = nombre;
    return this;
  }

  /**
   * Nombre de Oficina
   * @return nombre
   **/
  @JsonProperty("nombre")
  @ApiModelProperty(value = "Nombre de Oficina")
  public String getNombre() {
    return nombre;
  }

  public void setNombre(String nombre) {
    this.nombre = nombre;
  }

  public Oficina telefono(Telefono telefono) {
    this.telefono = telefono;
    return this;
  }

  /**
   * Get telefono
   * @return telefono
   **/
  @JsonProperty("telefono")
  @ApiModelProperty(value = "")
  public Telefono getTelefono() {
    return telefono;
  }

  public void setTelefono(Telefono telefono) {
    this.telefono = telefono;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Oficina oficina = (Oficina) o;
    return Objects.equals(this.codigo, oficina.codigo) &&
        Objects.equals(this.nombre, oficina.nombre) &&
        Objects.equals(this.telefono, oficina.telefono);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codigo, nombre, telefono);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Oficina {\n");
    
    sb.append("    codigo: ").append(toIndentedString(codigo)).append("\n");
    sb.append("    nombre: ").append(toIndentedString(nombre)).append("\n");
    sb.append("    telefono: ").append(toIndentedString(telefono)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

