/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Identifica si la Transacción es un Debito / Crédito u otra operación realizada (D&#x3D; Debito, C&#x3D;Crédito, O&#x3D;Otras)
 */
public enum OperacionTransaccion {
  
  DEBITO("Debito"),
  
  CR_DITO("Crédito"),
  
  OTRAS("Otras");

  private String value;

  OperacionTransaccion(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static OperacionTransaccion fromValue(String text) {
    for (OperacionTransaccion b : OperacionTransaccion.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

