/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Pago
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class Pago   {
  @JsonProperty("numeroSucursal")
  private String numeroSucursal = null;

  @JsonProperty("numeroCajero")
  private String numeroCajero = null;

  @JsonProperty("monto")
  private Double monto = null;

  @JsonProperty("montoCargado")
  private Double montoCargado = null;

  @JsonProperty("monedaMonto")
  private CodigosMonedas monedaMonto = null;

  @JsonProperty("concepto")
  private Concepto concepto = null;

  @JsonProperty("capitalTotal")
  private Double capitalTotal = null;

  @JsonProperty("itf")
  private Double itf = null;

  @JsonProperty("cuentaCargo")
  private Cuenta cuentaCargo = null;

  @JsonProperty("cuentaPagare")
  private Cuenta cuentaPagare = null;

  @JsonProperty("medioPago")
  private FormasPago medioPago = null;

  /**
   * Gets or Sets deudaAPagar
   */
  public enum DeudaAPagarEnum {
    TOTAL("TOTAL"),
    
    VENCIDO("VENCIDO"),
    
    SALDO("SALDO");

    private String value;

    DeudaAPagarEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DeudaAPagarEnum fromValue(String text) {
      for (DeudaAPagarEnum b : DeudaAPagarEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("deudaAPagar")
  private DeudaAPagarEnum deudaAPagar = null;

  @JsonProperty("deudas")
  private List<Deuda> deudas = null;

  @JsonProperty("tipo")
  private TiposPago tipo = null;

  @JsonProperty("tipoOperacion")
  private TiposOperacionPago tipoOperacion = null;

  @JsonProperty("tipoAfectacion")
  private TiposAfectacion tipoAfectacion = null;

  @JsonProperty("tipoTransaccionTeller")
  private BigDecimal tipoTransaccionTeller = null;

  @JsonProperty("cheque")
  private Cheque cheque = null;

  @JsonProperty("datosAdicionales")
  private List<DatoAdicional> datosAdicionales = null;

  @JsonProperty("tipoCambio")
  private BigDecimal tipoCambio = null;

  @JsonProperty("numeroLiquidacion")
  private String numeroLiquidacion = null;

  @JsonProperty("tarjeta")
  private Tarjeta tarjeta = null;

  @JsonProperty("comprobante")
  private String comprobante = null;

  @JsonProperty("numeroPago")
  private String numeroPago = null;

  @JsonProperty("numeroOperacion")
  private BigDecimal numeroOperacion = null;

  @JsonProperty("cuotas")
  private List<Cuota> cuotas = null;

  @JsonProperty("producto")
  private Producto producto = null;

  @JsonProperty("cliente")
  private Cliente cliente = null;

  @JsonProperty("prestamo")
  private Prestamo prestamo = null;

  @JsonProperty("leasing")
  private Leasing leasing = null;

  public Pago numeroSucursal(String numeroSucursal) {
    this.numeroSucursal = numeroSucursal;
    return this;
  }

  /**
   * Número Sucursal
   * @return numeroSucursal
   **/
  @JsonProperty("numeroSucursal")
  @ApiModelProperty(value = "Número Sucursal")
  public String getNumeroSucursal() {
    return numeroSucursal;
  }

  public void setNumeroSucursal(String numeroSucursal) {
    this.numeroSucursal = numeroSucursal;
  }

  public Pago numeroCajero(String numeroCajero) {
    this.numeroCajero = numeroCajero;
    return this;
  }

  /**
   * Número Cajero
   * @return numeroCajero
   **/
  @JsonProperty("numeroCajero")
  @ApiModelProperty(value = "Número Cajero")
  public String getNumeroCajero() {
    return numeroCajero;
  }

  public void setNumeroCajero(String numeroCajero) {
    this.numeroCajero = numeroCajero;
  }

  public Pago monto(Double monto) {
    this.monto = monto;
    return this;
  }

  /**
   * Monto a Pagar
   * @return monto
   **/
  @JsonProperty("monto")
  @ApiModelProperty(value = "Monto a Pagar")
  public Double getMonto() {
    return monto;
  }

  public void setMonto(Double monto) {
    this.monto = monto;
  }

  public Pago montoCargado(Double montoCargado) {
    this.montoCargado = montoCargado;
    return this;
  }

  /**
   * Monto cargado
   * @return montoCargado
   **/
  @JsonProperty("montoCargado")
  @ApiModelProperty(value = "Monto cargado")
  public Double getMontoCargado() {
    return montoCargado;
  }

  public void setMontoCargado(Double montoCargado) {
    this.montoCargado = montoCargado;
  }

  public Pago monedaMonto(CodigosMonedas monedaMonto) {
    this.monedaMonto = monedaMonto;
    return this;
  }

  /**
   * Get monedaMonto
   * @return monedaMonto
   **/
  @JsonProperty("monedaMonto")
  @ApiModelProperty(value = "")
  public CodigosMonedas getMonedaMonto() {
    return monedaMonto;
  }

  public void setMonedaMonto(CodigosMonedas monedaMonto) {
    this.monedaMonto = monedaMonto;
  }

  public Pago concepto(Concepto concepto) {
    this.concepto = concepto;
    return this;
  }

  /**
   * Get concepto
   * @return concepto
   **/
  @JsonProperty("concepto")
  @ApiModelProperty(value = "")
  public Concepto getConcepto() {
    return concepto;
  }

  public void setConcepto(Concepto concepto) {
    this.concepto = concepto;
  }

  public Pago capitalTotal(Double capitalTotal) {
    this.capitalTotal = capitalTotal;
    return this;
  }

  /**
   * Monto Capital Pagado
   * @return capitalTotal
   **/
  @JsonProperty("capitalTotal")
  @ApiModelProperty(value = "Monto Capital Pagado")
  public Double getCapitalTotal() {
    return capitalTotal;
  }

  public void setCapitalTotal(Double capitalTotal) {
    this.capitalTotal = capitalTotal;
  }

  public Pago itf(Double itf) {
    this.itf = itf;
    return this;
  }

  /**
   * Get itf
   * @return itf
   **/
  @JsonProperty("itf")
  @ApiModelProperty(value = "")
  public Double getItf() {
    return itf;
  }

  public void setItf(Double itf) {
    this.itf = itf;
  }

  public Pago cuentaCargo(Cuenta cuentaCargo) {
    this.cuentaCargo = cuentaCargo;
    return this;
  }

  /**
   * Get cuentaCargo
   * @return cuentaCargo
   **/
  @JsonProperty("cuentaCargo")
  @ApiModelProperty(value = "")
  public Cuenta getCuentaCargo() {
    return cuentaCargo;
  }

  public void setCuentaCargo(Cuenta cuentaCargo) {
    this.cuentaCargo = cuentaCargo;
  }

  public Pago cuentaPagare(Cuenta cuentaPagare) {
    this.cuentaPagare = cuentaPagare;
    return this;
  }

  /**
   * Get cuentaPagare
   * @return cuentaPagare
   **/
  @JsonProperty("cuentaPagare")
  @ApiModelProperty(value = "")
  public Cuenta getCuentaPagare() {
    return cuentaPagare;
  }

  public void setCuentaPagare(Cuenta cuentaPagare) {
    this.cuentaPagare = cuentaPagare;
  }

  public Pago medioPago(FormasPago medioPago) {
    this.medioPago = medioPago;
    return this;
  }

  /**
   * Get medioPago
   * @return medioPago
   **/
  @JsonProperty("medioPago")
  @ApiModelProperty(value = "")
  public FormasPago getMedioPago() {
    return medioPago;
  }

  public void setMedioPago(FormasPago medioPago) {
    this.medioPago = medioPago;
  }

  public Pago deudaAPagar(DeudaAPagarEnum deudaAPagar) {
    this.deudaAPagar = deudaAPagar;
    return this;
  }

  /**
   * Get deudaAPagar
   * @return deudaAPagar
   **/
  @JsonProperty("deudaAPagar")
  @ApiModelProperty(value = "")
  public DeudaAPagarEnum getDeudaAPagar() {
    return deudaAPagar;
  }

  public void setDeudaAPagar(DeudaAPagarEnum deudaAPagar) {
    this.deudaAPagar = deudaAPagar;
  }

  public Pago deudas(List<Deuda> deudas) {
    this.deudas = deudas;
    return this;
  }

  public Pago addDeudasItem(Deuda deudasItem) {
    if (this.deudas == null) {
      this.deudas = new ArrayList<Deuda>();
    }
    this.deudas.add(deudasItem);
    return this;
  }

  /**
   * Get deudas
   * @return deudas
   **/
  @JsonProperty("deudas")
  @ApiModelProperty(value = "")
  public List<Deuda> getDeudas() {
    return deudas;
  }

  public void setDeudas(List<Deuda> deudas) {
    this.deudas = deudas;
  }

  public Pago tipo(TiposPago tipo) {
    this.tipo = tipo;
    return this;
  }

  /**
   * Get tipo
   * @return tipo
   **/
  @JsonProperty("tipo")
  @ApiModelProperty(value = "")
  public TiposPago getTipo() {
    return tipo;
  }

  public void setTipo(TiposPago tipo) {
    this.tipo = tipo;
  }

  public Pago tipoOperacion(TiposOperacionPago tipoOperacion) {
    this.tipoOperacion = tipoOperacion;
    return this;
  }

  /**
   * Get tipoOperacion
   * @return tipoOperacion
   **/
  @JsonProperty("tipoOperacion")
  @ApiModelProperty(value = "")
  public TiposOperacionPago getTipoOperacion() {
    return tipoOperacion;
  }

  public void setTipoOperacion(TiposOperacionPago tipoOperacion) {
    this.tipoOperacion = tipoOperacion;
  }

  public Pago tipoAfectacion(TiposAfectacion tipoAfectacion) {
    this.tipoAfectacion = tipoAfectacion;
    return this;
  }

  /**
   * Get tipoAfectacion
   * @return tipoAfectacion
   **/
  @JsonProperty("tipoAfectacion")
  @ApiModelProperty(value = "")
  public TiposAfectacion getTipoAfectacion() {
    return tipoAfectacion;
  }

  public void setTipoAfectacion(TiposAfectacion tipoAfectacion) {
    this.tipoAfectacion = tipoAfectacion;
  }

  public Pago tipoTransaccionTeller(BigDecimal tipoTransaccionTeller) {
    this.tipoTransaccionTeller = tipoTransaccionTeller;
    return this;
  }

  /**
   * Tipo Transacción Teller
   * @return tipoTransaccionTeller
   **/
  @JsonProperty("tipoTransaccionTeller")
  @ApiModelProperty(value = "Tipo Transacción Teller")
  public BigDecimal getTipoTransaccionTeller() {
    return tipoTransaccionTeller;
  }

  public void setTipoTransaccionTeller(BigDecimal tipoTransaccionTeller) {
    this.tipoTransaccionTeller = tipoTransaccionTeller;
  }

  public Pago cheque(Cheque cheque) {
    this.cheque = cheque;
    return this;
  }

  /**
   * Get cheque
   * @return cheque
   **/
  @JsonProperty("cheque")
  @ApiModelProperty(value = "")
  public Cheque getCheque() {
    return cheque;
  }

  public void setCheque(Cheque cheque) {
    this.cheque = cheque;
  }

  public Pago datosAdicionales(List<DatoAdicional> datosAdicionales) {
    this.datosAdicionales = datosAdicionales;
    return this;
  }

  public Pago addDatosAdicionalesItem(DatoAdicional datosAdicionalesItem) {
    if (this.datosAdicionales == null) {
      this.datosAdicionales = new ArrayList<DatoAdicional>();
    }
    this.datosAdicionales.add(datosAdicionalesItem);
    return this;
  }

  /**
   * Get datosAdicionales
   * @return datosAdicionales
   **/
  @JsonProperty("datosAdicionales")
  @ApiModelProperty(value = "")
  public List<DatoAdicional> getDatosAdicionales() {
    return datosAdicionales;
  }

  public void setDatosAdicionales(List<DatoAdicional> datosAdicionales) {
    this.datosAdicionales = datosAdicionales;
  }

  public Pago tipoCambio(BigDecimal tipoCambio) {
    this.tipoCambio = tipoCambio;
    return this;
  }

  /**
   * Tipo de Cambio
   * @return tipoCambio
   **/
  @JsonProperty("tipoCambio")
  @ApiModelProperty(value = "Tipo de Cambio")
  public BigDecimal getTipoCambio() {
    return tipoCambio;
  }

  public void setTipoCambio(BigDecimal tipoCambio) {
    this.tipoCambio = tipoCambio;
  }

  public Pago numeroLiquidacion(String numeroLiquidacion) {
    this.numeroLiquidacion = numeroLiquidacion;
    return this;
  }

  /**
   * Nro de Liquidación
   * @return numeroLiquidacion
   **/
  @JsonProperty("numeroLiquidacion")
  @ApiModelProperty(value = "Nro de Liquidación")
  public String getNumeroLiquidacion() {
    return numeroLiquidacion;
  }

  public void setNumeroLiquidacion(String numeroLiquidacion) {
    this.numeroLiquidacion = numeroLiquidacion;
  }

  public Pago tarjeta(Tarjeta tarjeta) {
    this.tarjeta = tarjeta;
    return this;
  }

  /**
   * Get tarjeta
   * @return tarjeta
   **/
  @JsonProperty("tarjeta")
  @ApiModelProperty(value = "")
  public Tarjeta getTarjeta() {
    return tarjeta;
  }

  public void setTarjeta(Tarjeta tarjeta) {
    this.tarjeta = tarjeta;
  }

  public Pago comprobante(String comprobante) {
    this.comprobante = comprobante;
    return this;
  }

  /**
   * Get comprobante
   * @return comprobante
   **/
  @JsonProperty("comprobante")
  @ApiModelProperty(value = "")
  public String getComprobante() {
    return comprobante;
  }

  public void setComprobante(String comprobante) {
    this.comprobante = comprobante;
  }

  public Pago numeroPago(String numeroPago) {
    this.numeroPago = numeroPago;
    return this;
  }

  /**
   * Get numeroPago
   * @return numeroPago
   **/
  @JsonProperty("numeroPago")
  @ApiModelProperty(value = "")
  public String getNumeroPago() {
    return numeroPago;
  }

  public void setNumeroPago(String numeroPago) {
    this.numeroPago = numeroPago;
  }

  public Pago numeroOperacion(BigDecimal numeroOperacion) {
    this.numeroOperacion = numeroOperacion;
    return this;
  }

  /**
   * Número Operación
   * @return numeroOperacion
   **/
  @JsonProperty("numeroOperacion")
  @ApiModelProperty(value = "Número Operación")
  public BigDecimal getNumeroOperacion() {
    return numeroOperacion;
  }

  public void setNumeroOperacion(BigDecimal numeroOperacion) {
    this.numeroOperacion = numeroOperacion;
  }

  public Pago cuotas(List<Cuota> cuotas) {
    this.cuotas = cuotas;
    return this;
  }

  public Pago addCuotasItem(Cuota cuotasItem) {
    if (this.cuotas == null) {
      this.cuotas = new ArrayList<Cuota>();
    }
    this.cuotas.add(cuotasItem);
    return this;
  }

  /**
   * Get cuotas
   * @return cuotas
   **/
  @JsonProperty("cuotas")
  @ApiModelProperty(value = "")
  public List<Cuota> getCuotas() {
    return cuotas;
  }

  public void setCuotas(List<Cuota> cuotas) {
    this.cuotas = cuotas;
  }

  public Pago producto(Producto producto) {
    this.producto = producto;
    return this;
  }

  /**
   * Get producto
   * @return producto
   **/
  @JsonProperty("producto")
  @ApiModelProperty(value = "")
  public Producto getProducto() {
    return producto;
  }

  public void setProducto(Producto producto) {
    this.producto = producto;
  }

  public Pago cliente(Cliente cliente) {
    this.cliente = cliente;
    return this;
  }

  /**
   * Get cliente
   * @return cliente
   **/
  @JsonProperty("cliente")
  @ApiModelProperty(value = "")
  public Cliente getCliente() {
    return cliente;
  }

  public void setCliente(Cliente cliente) {
    this.cliente = cliente;
  }

  public Pago prestamo(Prestamo prestamo) {
    this.prestamo = prestamo;
    return this;
  }

  /**
   * Get prestamo
   * @return prestamo
   **/
  @JsonProperty("prestamo")
  @ApiModelProperty(value = "")
  public Prestamo getPrestamo() {
    return prestamo;
  }

  public void setPrestamo(Prestamo prestamo) {
    this.prestamo = prestamo;
  }

  public Pago leasing(Leasing leasing) {
    this.leasing = leasing;
    return this;
  }

  /**
   * Get leasing
   * @return leasing
   **/
  @JsonProperty("leasing")
  @ApiModelProperty(value = "")
  public Leasing getLeasing() {
    return leasing;
  }

  public void setLeasing(Leasing leasing) {
    this.leasing = leasing;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pago pago = (Pago) o;
    return Objects.equals(this.numeroSucursal, pago.numeroSucursal) &&
        Objects.equals(this.numeroCajero, pago.numeroCajero) &&
        Objects.equals(this.monto, pago.monto) &&
        Objects.equals(this.montoCargado, pago.montoCargado) &&
        Objects.equals(this.monedaMonto, pago.monedaMonto) &&
        Objects.equals(this.concepto, pago.concepto) &&
        Objects.equals(this.capitalTotal, pago.capitalTotal) &&
        Objects.equals(this.itf, pago.itf) &&
        Objects.equals(this.cuentaCargo, pago.cuentaCargo) &&
        Objects.equals(this.cuentaPagare, pago.cuentaPagare) &&
        Objects.equals(this.medioPago, pago.medioPago) &&
        Objects.equals(this.deudaAPagar, pago.deudaAPagar) &&
        Objects.equals(this.deudas, pago.deudas) &&
        Objects.equals(this.tipo, pago.tipo) &&
        Objects.equals(this.tipoOperacion, pago.tipoOperacion) &&
        Objects.equals(this.tipoAfectacion, pago.tipoAfectacion) &&
        Objects.equals(this.tipoTransaccionTeller, pago.tipoTransaccionTeller) &&
        Objects.equals(this.cheque, pago.cheque) &&
        Objects.equals(this.datosAdicionales, pago.datosAdicionales) &&
        Objects.equals(this.tipoCambio, pago.tipoCambio) &&
        Objects.equals(this.numeroLiquidacion, pago.numeroLiquidacion) &&
        Objects.equals(this.tarjeta, pago.tarjeta) &&
        Objects.equals(this.comprobante, pago.comprobante) &&
        Objects.equals(this.numeroPago, pago.numeroPago) &&
        Objects.equals(this.numeroOperacion, pago.numeroOperacion) &&
        Objects.equals(this.cuotas, pago.cuotas) &&
        Objects.equals(this.producto, pago.producto) &&
        Objects.equals(this.cliente, pago.cliente) &&
        Objects.equals(this.prestamo, pago.prestamo) &&
        Objects.equals(this.leasing, pago.leasing);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroSucursal, numeroCajero, monto, montoCargado, monedaMonto, concepto, capitalTotal, itf, cuentaCargo, cuentaPagare, medioPago, deudaAPagar, deudas, tipo, tipoOperacion, tipoAfectacion, tipoTransaccionTeller, cheque, datosAdicionales, tipoCambio, numeroLiquidacion, tarjeta, comprobante, numeroPago, numeroOperacion, cuotas, producto, cliente, prestamo, leasing);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pago {\n");
    
    sb.append("    numeroSucursal: ").append(toIndentedString(numeroSucursal)).append("\n");
    sb.append("    numeroCajero: ").append(toIndentedString(numeroCajero)).append("\n");
    sb.append("    monto: ").append(toIndentedString(monto)).append("\n");
    sb.append("    montoCargado: ").append(toIndentedString(montoCargado)).append("\n");
    sb.append("    monedaMonto: ").append(toIndentedString(monedaMonto)).append("\n");
    sb.append("    concepto: ").append(toIndentedString(concepto)).append("\n");
    sb.append("    capitalTotal: ").append(toIndentedString(capitalTotal)).append("\n");
    sb.append("    itf: ").append(toIndentedString(itf)).append("\n");
    sb.append("    cuentaCargo: ").append(toIndentedString(cuentaCargo)).append("\n");
    sb.append("    cuentaPagare: ").append(toIndentedString(cuentaPagare)).append("\n");
    sb.append("    medioPago: ").append(toIndentedString(medioPago)).append("\n");
    sb.append("    deudaAPagar: ").append(toIndentedString(deudaAPagar)).append("\n");
    sb.append("    deudas: ").append(toIndentedString(deudas)).append("\n");
    sb.append("    tipo: ").append(toIndentedString(tipo)).append("\n");
    sb.append("    tipoOperacion: ").append(toIndentedString(tipoOperacion)).append("\n");
    sb.append("    tipoAfectacion: ").append(toIndentedString(tipoAfectacion)).append("\n");
    sb.append("    tipoTransaccionTeller: ").append(toIndentedString(tipoTransaccionTeller)).append("\n");
    sb.append("    cheque: ").append(toIndentedString(cheque)).append("\n");
    sb.append("    datosAdicionales: ").append(toIndentedString(datosAdicionales)).append("\n");
    sb.append("    tipoCambio: ").append(toIndentedString(tipoCambio)).append("\n");
    sb.append("    numeroLiquidacion: ").append(toIndentedString(numeroLiquidacion)).append("\n");
    sb.append("    tarjeta: ").append(toIndentedString(tarjeta)).append("\n");
    sb.append("    comprobante: ").append(toIndentedString(comprobante)).append("\n");
    sb.append("    numeroPago: ").append(toIndentedString(numeroPago)).append("\n");
    sb.append("    numeroOperacion: ").append(toIndentedString(numeroOperacion)).append("\n");
    sb.append("    cuotas: ").append(toIndentedString(cuotas)).append("\n");
    sb.append("    producto: ").append(toIndentedString(producto)).append("\n");
    sb.append("    cliente: ").append(toIndentedString(cliente)).append("\n");
    sb.append("    prestamo: ").append(toIndentedString(prestamo)).append("\n");
    sb.append("    leasing: ").append(toIndentedString(leasing)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

