/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * ParametroValidacion
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class ParametroValidacion   {
  @JsonProperty("nombre")
  private String nombre = null;

  @JsonProperty("valor")
  private String valor = null;

  public ParametroValidacion nombre(String nombre) {
    this.nombre = nombre;
    return this;
  }

  /**
   * Nombre del parametro.
   * @return nombre
   **/
  @JsonProperty("nombre")
  @ApiModelProperty(value = "Nombre del parametro.")
  public String getNombre() {
    return nombre;
  }

  public void setNombre(String nombre) {
    this.nombre = nombre;
  }

  public ParametroValidacion valor(String valor) {
    this.valor = valor;
    return this;
  }

  /**
   * Valor del parametro.
   * @return valor
   **/
  @JsonProperty("valor")
  @ApiModelProperty(value = "Valor del parametro.")
  public String getValor() {
    return valor;
  }

  public void setValor(String valor) {
    this.valor = valor;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParametroValidacion parametroValidacion = (ParametroValidacion) o;
    return Objects.equals(this.nombre, parametroValidacion.nombre) &&
        Objects.equals(this.valor, parametroValidacion.valor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nombre, valor);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParametroValidacion {\n");
    
    sb.append("    nombre: ").append(toIndentedString(nombre)).append("\n");
    sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

