/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * Pŕestamo
 */
@ApiModel(description = "Pŕestamo")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class Prestamo   {
  @JsonProperty("numero")
  private String numero = null;

  @JsonProperty("deudaTotal")
  private BigDecimal deudaTotal = null;

  @JsonProperty("numeroCuotasPagar")
  private BigDecimal numeroCuotasPagar = null;

  @JsonProperty("numeroCuotasPagadas")
  private BigDecimal numeroCuotasPagadas = null;

  @JsonProperty("capital")
  private BigDecimal capital = null;

  @JsonProperty("interesCorriente")
  private BigDecimal interesCorriente = null;

  @JsonProperty("interesMoratorio")
  private BigDecimal interesMoratorio = null;

  @JsonProperty("interesCompensatorioVencido")
  private BigDecimal interesCompensatorioVencido = null;

  @JsonProperty("seguro")
  private BigDecimal seguro = null;

  @JsonProperty("comision")
  private BigDecimal comision = null;

  @JsonProperty("itf")
  private BigDecimal itf = null;

  @JsonProperty("itf2")
  private BigDecimal itf2 = null;

  @JsonProperty("tipoCambio")
  private BigDecimal tipoCambio = null;

  @JsonProperty("totalCancelado")
  private BigDecimal totalCancelado = null;

  @JsonProperty("hipotecado")
  private Boolean hipotecado = null;

  @JsonProperty("numeroUltimaCuotaPagada")
  private BigDecimal numeroUltimaCuotaPagada = null;

  @JsonProperty("comisionPj")
  private BigDecimal comisionPj = null;

  @JsonProperty("reducirCuotaPlazo")
  private String reducirCuotaPlazo = null;

  @JsonProperty("afectaCapitalInt")
  private String afectaCapitalInt = null;

  public Prestamo numero(String numero) {
    this.numero = numero;
    return this;
  }

  /**
   * Número Préstamo /Pagaré
   * @return numero
   **/
  @JsonProperty("numero")
  @ApiModelProperty(value = "Número Préstamo /Pagaré")
  public String getNumero() {
    return numero;
  }

  public void setNumero(String numero) {
    this.numero = numero;
  }

  public Prestamo deudaTotal(BigDecimal deudaTotal) {
    this.deudaTotal = deudaTotal;
    return this;
  }

  /**
   * Deuda Total
   * @return deudaTotal
   **/
  @JsonProperty("deudaTotal")
  @ApiModelProperty(value = "Deuda Total")
  public BigDecimal getDeudaTotal() {
    return deudaTotal;
  }

  public void setDeudaTotal(BigDecimal deudaTotal) {
    this.deudaTotal = deudaTotal;
  }

  public Prestamo numeroCuotasPagar(BigDecimal numeroCuotasPagar) {
    this.numeroCuotasPagar = numeroCuotasPagar;
    return this;
  }

  /**
   * Nro de Cuota o Cuotas a Pagar
   * @return numeroCuotasPagar
   **/
  @JsonProperty("numeroCuotasPagar")
  @ApiModelProperty(value = "Nro de Cuota o Cuotas a Pagar")
  public BigDecimal getNumeroCuotasPagar() {
    return numeroCuotasPagar;
  }

  public void setNumeroCuotasPagar(BigDecimal numeroCuotasPagar) {
    this.numeroCuotasPagar = numeroCuotasPagar;
  }

  public Prestamo numeroCuotasPagadas(BigDecimal numeroCuotasPagadas) {
    this.numeroCuotasPagadas = numeroCuotasPagadas;
    return this;
  }

  /**
   * Nro de Cuota o Cuotas Pagadas
   * @return numeroCuotasPagadas
   **/
  @JsonProperty("numeroCuotasPagadas")
  @ApiModelProperty(value = "Nro de Cuota o Cuotas Pagadas")
  public BigDecimal getNumeroCuotasPagadas() {
    return numeroCuotasPagadas;
  }

  public void setNumeroCuotasPagadas(BigDecimal numeroCuotasPagadas) {
    this.numeroCuotasPagadas = numeroCuotasPagadas;
  }

  public Prestamo capital(BigDecimal capital) {
    this.capital = capital;
    return this;
  }

  /**
   * Capital
   * @return capital
   **/
  @JsonProperty("capital")
  @ApiModelProperty(value = "Capital")
  public BigDecimal getCapital() {
    return capital;
  }

  public void setCapital(BigDecimal capital) {
    this.capital = capital;
  }

  public Prestamo interesCorriente(BigDecimal interesCorriente) {
    this.interesCorriente = interesCorriente;
    return this;
  }

  /**
   * Interés Corriente
   * @return interesCorriente
   **/
  @JsonProperty("interesCorriente")
  @ApiModelProperty(value = "Interés Corriente")
  public BigDecimal getInteresCorriente() {
    return interesCorriente;
  }

  public void setInteresCorriente(BigDecimal interesCorriente) {
    this.interesCorriente = interesCorriente;
  }

  public Prestamo interesMoratorio(BigDecimal interesMoratorio) {
    this.interesMoratorio = interesMoratorio;
    return this;
  }

  /**
   * Interés Moratorio
   * @return interesMoratorio
   **/
  @JsonProperty("interesMoratorio")
  @ApiModelProperty(value = "Interés Moratorio")
  public BigDecimal getInteresMoratorio() {
    return interesMoratorio;
  }

  public void setInteresMoratorio(BigDecimal interesMoratorio) {
    this.interesMoratorio = interesMoratorio;
  }

  public Prestamo interesCompensatorioVencido(BigDecimal interesCompensatorioVencido) {
    this.interesCompensatorioVencido = interesCompensatorioVencido;
    return this;
  }

  /**
   * Interés compensatorio Vencido
   * @return interesCompensatorioVencido
   **/
  @JsonProperty("interesCompensatorioVencido")
  @ApiModelProperty(value = "Interés compensatorio Vencido")
  public BigDecimal getInteresCompensatorioVencido() {
    return interesCompensatorioVencido;
  }

  public void setInteresCompensatorioVencido(BigDecimal interesCompensatorioVencido) {
    this.interesCompensatorioVencido = interesCompensatorioVencido;
  }

  public Prestamo seguro(BigDecimal seguro) {
    this.seguro = seguro;
    return this;
  }

  /**
   * Seguro
   * @return seguro
   **/
  @JsonProperty("seguro")
  @ApiModelProperty(value = "Seguro")
  public BigDecimal getSeguro() {
    return seguro;
  }

  public void setSeguro(BigDecimal seguro) {
    this.seguro = seguro;
  }

  public Prestamo comision(BigDecimal comision) {
    this.comision = comision;
    return this;
  }

  /**
   * Comisión
   * @return comision
   **/
  @JsonProperty("comision")
  @ApiModelProperty(value = "Comisión")
  public BigDecimal getComision() {
    return comision;
  }

  public void setComision(BigDecimal comision) {
    this.comision = comision;
  }

  public Prestamo itf(BigDecimal itf) {
    this.itf = itf;
    return this;
  }

  /**
   * ITF
   * @return itf
   **/
  @JsonProperty("itf")
  @ApiModelProperty(value = "ITF")
  public BigDecimal getItf() {
    return itf;
  }

  public void setItf(BigDecimal itf) {
    this.itf = itf;
  }

  public Prestamo itf2(BigDecimal itf2) {
    this.itf2 = itf2;
    return this;
  }

  /**
   * ITF2
   * @return itf2
   **/
  @JsonProperty("itf2")
  @ApiModelProperty(value = "ITF2")
  public BigDecimal getItf2() {
    return itf2;
  }

  public void setItf2(BigDecimal itf2) {
    this.itf2 = itf2;
  }

  public Prestamo tipoCambio(BigDecimal tipoCambio) {
    this.tipoCambio = tipoCambio;
    return this;
  }

  /**
   * Tipo de Cambio
   * @return tipoCambio
   **/
  @JsonProperty("tipoCambio")
  @ApiModelProperty(value = "Tipo de Cambio")
  public BigDecimal getTipoCambio() {
    return tipoCambio;
  }

  public void setTipoCambio(BigDecimal tipoCambio) {
    this.tipoCambio = tipoCambio;
  }

  public Prestamo totalCancelado(BigDecimal totalCancelado) {
    this.totalCancelado = totalCancelado;
    return this;
  }

  /**
   * Total cancelado (con ITF)
   * @return totalCancelado
   **/
  @JsonProperty("totalCancelado")
  @ApiModelProperty(value = "Total cancelado (con ITF)")
  public BigDecimal getTotalCancelado() {
    return totalCancelado;
  }

  public void setTotalCancelado(BigDecimal totalCancelado) {
    this.totalCancelado = totalCancelado;
  }

  public Prestamo hipotecado(Boolean hipotecado) {
    this.hipotecado = hipotecado;
    return this;
  }

  /**
   * Flag Hipotecario
   * @return hipotecado
   **/
  @JsonProperty("hipotecado")
  @ApiModelProperty(value = "Flag Hipotecario")
  public Boolean isHipotecado() {
    return hipotecado;
  }

  public void setHipotecado(Boolean hipotecado) {
    this.hipotecado = hipotecado;
  }

  public Prestamo numeroUltimaCuotaPagada(BigDecimal numeroUltimaCuotaPagada) {
    this.numeroUltimaCuotaPagada = numeroUltimaCuotaPagada;
    return this;
  }

  /**
   * Pagado hasta la Cuota
   * @return numeroUltimaCuotaPagada
   **/
  @JsonProperty("numeroUltimaCuotaPagada")
  @ApiModelProperty(value = "Pagado hasta la Cuota")
  public BigDecimal getNumeroUltimaCuotaPagada() {
    return numeroUltimaCuotaPagada;
  }

  public void setNumeroUltimaCuotaPagada(BigDecimal numeroUltimaCuotaPagada) {
    this.numeroUltimaCuotaPagada = numeroUltimaCuotaPagada;
  }

  public Prestamo comisionPj(BigDecimal comisionPj) {
    this.comisionPj = comisionPj;
    return this;
  }

  /**
   * Comisión PJ
   * @return comisionPj
   **/
  @JsonProperty("comisionPj")
  @ApiModelProperty(value = "Comisión PJ")
  public BigDecimal getComisionPj() {
    return comisionPj;
  }

  public void setComisionPj(BigDecimal comisionPj) {
    this.comisionPj = comisionPj;
  }

  public Prestamo reducirCuotaPlazo(String reducirCuotaPlazo) {
    this.reducirCuotaPlazo = reducirCuotaPlazo;
    return this;
  }

  /**
   * Reducir - Cuota o Plazo
   * @return reducirCuotaPlazo
   **/
  @JsonProperty("reducirCuotaPlazo")
  @ApiModelProperty(value = "Reducir - Cuota o Plazo")
  public String getReducirCuotaPlazo() {
    return reducirCuotaPlazo;
  }

  public void setReducirCuotaPlazo(String reducirCuotaPlazo) {
    this.reducirCuotaPlazo = reducirCuotaPlazo;
  }

  public Prestamo afectaCapitalInt(String afectaCapitalInt) {
    this.afectaCapitalInt = afectaCapitalInt;
    return this;
  }

  /**
   * Afecta - Capital o Cap + Int
   * @return afectaCapitalInt
   **/
  @JsonProperty("afectaCapitalInt")
  @ApiModelProperty(value = "Afecta - Capital o Cap + Int")
  public String getAfectaCapitalInt() {
    return afectaCapitalInt;
  }

  public void setAfectaCapitalInt(String afectaCapitalInt) {
    this.afectaCapitalInt = afectaCapitalInt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Prestamo prestamo = (Prestamo) o;
    return Objects.equals(this.numero, prestamo.numero) &&
        Objects.equals(this.deudaTotal, prestamo.deudaTotal) &&
        Objects.equals(this.numeroCuotasPagar, prestamo.numeroCuotasPagar) &&
        Objects.equals(this.numeroCuotasPagadas, prestamo.numeroCuotasPagadas) &&
        Objects.equals(this.capital, prestamo.capital) &&
        Objects.equals(this.interesCorriente, prestamo.interesCorriente) &&
        Objects.equals(this.interesMoratorio, prestamo.interesMoratorio) &&
        Objects.equals(this.interesCompensatorioVencido, prestamo.interesCompensatorioVencido) &&
        Objects.equals(this.seguro, prestamo.seguro) &&
        Objects.equals(this.comision, prestamo.comision) &&
        Objects.equals(this.itf, prestamo.itf) &&
        Objects.equals(this.itf2, prestamo.itf2) &&
        Objects.equals(this.tipoCambio, prestamo.tipoCambio) &&
        Objects.equals(this.totalCancelado, prestamo.totalCancelado) &&
        Objects.equals(this.hipotecado, prestamo.hipotecado) &&
        Objects.equals(this.numeroUltimaCuotaPagada, prestamo.numeroUltimaCuotaPagada) &&
        Objects.equals(this.comisionPj, prestamo.comisionPj) &&
        Objects.equals(this.reducirCuotaPlazo, prestamo.reducirCuotaPlazo) &&
        Objects.equals(this.afectaCapitalInt, prestamo.afectaCapitalInt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numero, deudaTotal, numeroCuotasPagar, numeroCuotasPagadas, capital, interesCorriente, interesMoratorio, interesCompensatorioVencido, seguro, comision, itf, itf2, tipoCambio, totalCancelado, hipotecado, numeroUltimaCuotaPagada, comisionPj, reducirCuotaPlazo, afectaCapitalInt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Prestamo {\n");
    
    sb.append("    numero: ").append(toIndentedString(numero)).append("\n");
    sb.append("    deudaTotal: ").append(toIndentedString(deudaTotal)).append("\n");
    sb.append("    numeroCuotasPagar: ").append(toIndentedString(numeroCuotasPagar)).append("\n");
    sb.append("    numeroCuotasPagadas: ").append(toIndentedString(numeroCuotasPagadas)).append("\n");
    sb.append("    capital: ").append(toIndentedString(capital)).append("\n");
    sb.append("    interesCorriente: ").append(toIndentedString(interesCorriente)).append("\n");
    sb.append("    interesMoratorio: ").append(toIndentedString(interesMoratorio)).append("\n");
    sb.append("    interesCompensatorioVencido: ").append(toIndentedString(interesCompensatorioVencido)).append("\n");
    sb.append("    seguro: ").append(toIndentedString(seguro)).append("\n");
    sb.append("    comision: ").append(toIndentedString(comision)).append("\n");
    sb.append("    itf: ").append(toIndentedString(itf)).append("\n");
    sb.append("    itf2: ").append(toIndentedString(itf2)).append("\n");
    sb.append("    tipoCambio: ").append(toIndentedString(tipoCambio)).append("\n");
    sb.append("    totalCancelado: ").append(toIndentedString(totalCancelado)).append("\n");
    sb.append("    hipotecado: ").append(toIndentedString(hipotecado)).append("\n");
    sb.append("    numeroUltimaCuotaPagada: ").append(toIndentedString(numeroUltimaCuotaPagada)).append("\n");
    sb.append("    comisionPj: ").append(toIndentedString(comisionPj)).append("\n");
    sb.append("    reducirCuotaPlazo: ").append(toIndentedString(reducirCuotaPlazo)).append("\n");
    sb.append("    afectaCapitalInt: ").append(toIndentedString(afectaCapitalInt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

