/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.DecimalMax;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Objects;

/**
 * Producto
 */
@ApiModel(description = "Producto")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class Producto   {
  @JsonProperty("codigo")
  private String codigo = null;

  @JsonProperty("tipo")
  private TipoProducto tipo = null;

  @JsonProperty("grupo")
  private GrupoProducto grupo = null;

  @JsonProperty("nombre")
  private String nombre = null;

  @JsonProperty("descripcion")
  private String descripcion = null;

  @JsonProperty("moneda")
  private CodigosMonedas moneda = null;

  @JsonProperty("cliente")
  private Cliente cliente = null;

  @JsonProperty("cuenta")
  private Cuenta cuenta = null;

  @JsonProperty("cuentaContable")
  private BigDecimal cuentaContable = null;

  @JsonProperty("montoLinea")
  private BigDecimal montoLinea = null;

  @JsonProperty("saldoDeuda")
  private BigDecimal saldoDeuda = null;

  @JsonProperty("bloqueosCuenta")
  private String bloqueosCuenta = null;

  @JsonProperty("fechaEmision")
  private Date fechaEmision = null;

  @JsonProperty("fechaVencimiento")
  private Date fechaVencimiento = null;

  @JsonProperty("totalSoles")
  private BigDecimal totalSoles = null;

  @JsonProperty("totalDolares")
  private BigDecimal totalDolares = null;

  @JsonProperty("diaExpiracion")
  private BigDecimal diaExpiracion = null;

  @JsonProperty("mesExpiracion")
  private BigDecimal mesExpiracion = null;

  @JsonProperty("anoExpiracion")
  private BigDecimal anoExpiracion = null;

  @JsonProperty("opcional")
  private String opcional = null;

  @JsonProperty("subProducto")
  private SubProducto subProducto = null;

  @JsonProperty("lineaCredito")
  private LineaCredito lineaCredito = null;

  public Producto codigo(String codigo) {
    this.codigo = codigo;
    return this;
  }

  /**
   * Código identificador del producto en sistema
   * @return codigo
   **/
  @JsonProperty("codigo")
  @ApiModelProperty(value = "Código identificador del producto en sistema")
  public String getCodigo() {
    return codigo;
  }

  public void setCodigo(String codigo) {
    this.codigo = codigo;
  }

  public Producto tipo(TipoProducto tipo) {
    this.tipo = tipo;
    return this;
  }

  /**
   * Get tipo
   * @return tipo
   **/
  @JsonProperty("tipo")
  @ApiModelProperty(value = "")
  public TipoProducto getTipo() {
    return tipo;
  }

  public void setTipo(TipoProducto tipo) {
    this.tipo = tipo;
  }

  public Producto grupo(GrupoProducto grupo) {
    this.grupo = grupo;
    return this;
  }

  /**
   * Get grupo
   * @return grupo
   **/
  @JsonProperty("grupo")
  @ApiModelProperty(value = "")
  public GrupoProducto getGrupo() {
    return grupo;
  }

  public void setGrupo(GrupoProducto grupo) {
    this.grupo = grupo;
  }

  public Producto nombre(String nombre) {
    this.nombre = nombre;
    return this;
  }

  /**
   * Nombre del producto en sistema
   * @return nombre
   **/
  @JsonProperty("nombre")
  @ApiModelProperty(value = "Nombre del producto en sistema")
  public String getNombre() {
    return nombre;
  }

  public void setNombre(String nombre) {
    this.nombre = nombre;
  }

  public Producto descripcion(String descripcion) {
    this.descripcion = descripcion;
    return this;
  }

  /**
   * Descripción del producto en sistema
   * @return descripcion
   **/
  @JsonProperty("descripcion")
  @ApiModelProperty(value = "Descripción del producto en sistema")
  public String getDescripcion() {
    return descripcion;
  }

  public void setDescripcion(String descripcion) {
    this.descripcion = descripcion;
  }

  public Producto moneda(CodigosMonedas moneda) {
    this.moneda = moneda;
    return this;
  }

  /**
   * Get moneda
   * @return moneda
   **/
  @JsonProperty("moneda")
  @ApiModelProperty(value = "")
  public CodigosMonedas getMoneda() {
    return moneda;
  }

  public void setMoneda(CodigosMonedas moneda) {
    this.moneda = moneda;
  }

  public Producto cliente(Cliente cliente) {
    this.cliente = cliente;
    return this;
  }

  /**
   * Get cliente
   * @return cliente
   **/
  @JsonProperty("cliente")
  @ApiModelProperty(value = "")
  public Cliente getCliente() {
    return cliente;
  }

  public void setCliente(Cliente cliente) {
    this.cliente = cliente;
  }

  public Producto cuenta(Cuenta cuenta) {
    this.cuenta = cuenta;
    return this;
  }

  /**
   * Get cuenta
   * @return cuenta
   **/
  @JsonProperty("cuenta")
  @ApiModelProperty(value = "")
  public Cuenta getCuenta() {
    return cuenta;
  }

  public void setCuenta(Cuenta cuenta) {
    this.cuenta = cuenta;
  }

  public Producto cuentaContable(BigDecimal cuentaContable) {
    this.cuentaContable = cuentaContable;
    return this;
  }

  /**
   * Cuenta Contable
   * @return cuentaContable
   **/
  @JsonProperty("cuentaContable")
  @ApiModelProperty(value = "Cuenta Contable")
  public BigDecimal getCuentaContable() {
    return cuentaContable;
  }

  public void setCuentaContable(BigDecimal cuentaContable) {
    this.cuentaContable = cuentaContable;
  }

  public Producto montoLinea(BigDecimal montoLinea) {
    this.montoLinea = montoLinea;
    return this;
  }

  /**
   * Monto Linea
   * @return montoLinea
   **/
  @JsonProperty("montoLinea")
  @ApiModelProperty(value = "Monto Linea")
  public BigDecimal getMontoLinea() {
    return montoLinea;
  }

  public void setMontoLinea(BigDecimal montoLinea) {
    this.montoLinea = montoLinea;
  }

  public Producto saldoDeuda(BigDecimal saldoDeuda) {
    this.saldoDeuda = saldoDeuda;
    return this;
  }

  /**
   * Saldo Deuda
   * @return saldoDeuda
   **/
  @JsonProperty("saldoDeuda")
  @ApiModelProperty(value = "Saldo Deuda")
  public BigDecimal getSaldoDeuda() {
    return saldoDeuda;
  }

  public void setSaldoDeuda(BigDecimal saldoDeuda) {
    this.saldoDeuda = saldoDeuda;
  }

  public Producto bloqueosCuenta(String bloqueosCuenta) {
    this.bloqueosCuenta = bloqueosCuenta;
    return this;
  }

  /**
   * Bloqueos Cuenta
   * @return bloqueosCuenta
   **/
  @JsonProperty("bloqueosCuenta")
  @ApiModelProperty(value = "Bloqueos Cuenta")
  public String getBloqueosCuenta() {
    return bloqueosCuenta;
  }

  public void setBloqueosCuenta(String bloqueosCuenta) {
    this.bloqueosCuenta = bloqueosCuenta;
  }

  public Producto fechaEmision(Date fechaEmision) {
    this.fechaEmision = fechaEmision;
    return this;
  }

  /**
   * Fecha Emisión
   * @return fechaEmision
   **/
  @JsonProperty("fechaEmision")
  @ApiModelProperty(value = "Fecha Emisión")
  public Date getFechaEmision() {
    return fechaEmision;
  }

  public void setFechaEmision(Date fechaEmision) {
    this.fechaEmision = fechaEmision;
  }

  public Producto fechaVencimiento(Date fechaVencimiento) {
    this.fechaVencimiento = fechaVencimiento;
    return this;
  }

  /**
   * Fecha Vencimiento
   * @return fechaVencimiento
   **/
  @JsonProperty("fechaVencimiento")
  @ApiModelProperty(value = "Fecha Vencimiento")
  public Date getFechaVencimiento() {
    return fechaVencimiento;
  }

  public void setFechaVencimiento(Date fechaVencimiento) {
    this.fechaVencimiento = fechaVencimiento;
  }

  public Producto totalSoles(BigDecimal totalSoles) {
    this.totalSoles = totalSoles;
    return this;
  }

  /**
   * Total Soles
   * @return totalSoles
   **/
  @JsonProperty("totalSoles")
  @ApiModelProperty(value = "Total Soles")
  public BigDecimal getTotalSoles() {
    return totalSoles;
  }

  public void setTotalSoles(BigDecimal totalSoles) {
    this.totalSoles = totalSoles;
  }

  public Producto totalDolares(BigDecimal totalDolares) {
    this.totalDolares = totalDolares;
    return this;
  }

  /**
   * Total Dólares
   * @return totalDolares
   **/
  @JsonProperty("totalDolares")
  @ApiModelProperty(value = "Total Dólares")
  public BigDecimal getTotalDolares() {
    return totalDolares;
  }

  public void setTotalDolares(BigDecimal totalDolares) {
    this.totalDolares = totalDolares;
  }

  public Producto diaExpiracion(BigDecimal diaExpiracion) {
    this.diaExpiracion = diaExpiracion;
    return this;
  }

  /**
   * Día de expiración de lo producto.
   * maximum: 2
   * @return diaExpiracion
   **/
  @JsonProperty("diaExpiracion")
  @ApiModelProperty(value = "Día de expiración de lo producto.")
 @DecimalMax("2")  public BigDecimal getDiaExpiracion() {
    return diaExpiracion;
  }

  public void setDiaExpiracion(BigDecimal diaExpiracion) {
    this.diaExpiracion = diaExpiracion;
  }

  public Producto mesExpiracion(BigDecimal mesExpiracion) {
    this.mesExpiracion = mesExpiracion;
    return this;
  }

  /**
   * Més de expiración de lo producto.
   * maximum: 2
   * @return mesExpiracion
   **/
  @JsonProperty("mesExpiracion")
  @ApiModelProperty(value = "Més de expiración de lo producto.")
 @DecimalMax("2")  public BigDecimal getMesExpiracion() {
    return mesExpiracion;
  }

  public void setMesExpiracion(BigDecimal mesExpiracion) {
    this.mesExpiracion = mesExpiracion;
  }

  public Producto anoExpiracion(BigDecimal anoExpiracion) {
    this.anoExpiracion = anoExpiracion;
    return this;
  }

  /**
   * Ano de expiración de lo producto.
   * maximum: 4
   * @return anoExpiracion
   **/
  @JsonProperty("anoExpiracion")
  @ApiModelProperty(value = "Ano de expiración de lo producto.")
 @DecimalMax("4")  public BigDecimal getAnoExpiracion() {
    return anoExpiracion;
  }

  public void setAnoExpiracion(BigDecimal anoExpiracion) {
    this.anoExpiracion = anoExpiracion;
  }

  public Producto opcional(String opcional) {
    this.opcional = opcional;
    return this;
  }

  /**
   * Opc. (Detalle por Grupo)
   * @return opcional
   **/
  @JsonProperty("opcional")
  @ApiModelProperty(value = "Opc. (Detalle por Grupo)")
  public String getOpcional() {
    return opcional;
  }

  public void setOpcional(String opcional) {
    this.opcional = opcional;
  }

  public Producto subProducto(SubProducto subProducto) {
    this.subProducto = subProducto;
    return this;
  }

  /**
   * Get subProducto
   * @return subProducto
   **/
  @JsonProperty("subProducto")
  @ApiModelProperty(value = "")
  public SubProducto getSubProducto() {
    return subProducto;
  }

  public void setSubProducto(SubProducto subProducto) {
    this.subProducto = subProducto;
  }

  public Producto lineaCredito(LineaCredito lineaCredito) {
    this.lineaCredito = lineaCredito;
    return this;
  }

  /**
   * Get lineaCredito
   * @return lineaCredito
   **/
  @JsonProperty("lineaCredito")
  @ApiModelProperty(value = "")
  public LineaCredito getLineaCredito() {
    return lineaCredito;
  }

  public void setLineaCredito(LineaCredito lineaCredito) {
    this.lineaCredito = lineaCredito;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Producto producto = (Producto) o;
    return Objects.equals(this.codigo, producto.codigo) &&
        Objects.equals(this.tipo, producto.tipo) &&
        Objects.equals(this.grupo, producto.grupo) &&
        Objects.equals(this.nombre, producto.nombre) &&
        Objects.equals(this.descripcion, producto.descripcion) &&
        Objects.equals(this.moneda, producto.moneda) &&
        Objects.equals(this.cliente, producto.cliente) &&
        Objects.equals(this.cuenta, producto.cuenta) &&
        Objects.equals(this.cuentaContable, producto.cuentaContable) &&
        Objects.equals(this.montoLinea, producto.montoLinea) &&
        Objects.equals(this.saldoDeuda, producto.saldoDeuda) &&
        Objects.equals(this.bloqueosCuenta, producto.bloqueosCuenta) &&
        Objects.equals(this.fechaEmision, producto.fechaEmision) &&
        Objects.equals(this.fechaVencimiento, producto.fechaVencimiento) &&
        Objects.equals(this.totalSoles, producto.totalSoles) &&
        Objects.equals(this.totalDolares, producto.totalDolares) &&
        Objects.equals(this.diaExpiracion, producto.diaExpiracion) &&
        Objects.equals(this.mesExpiracion, producto.mesExpiracion) &&
        Objects.equals(this.anoExpiracion, producto.anoExpiracion) &&
        Objects.equals(this.opcional, producto.opcional) &&
        Objects.equals(this.subProducto, producto.subProducto) &&
        Objects.equals(this.lineaCredito, producto.lineaCredito);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codigo, tipo, grupo, nombre, descripcion, moneda, cliente, cuenta, cuentaContable, montoLinea, saldoDeuda, bloqueosCuenta, fechaEmision, fechaVencimiento, totalSoles, totalDolares, diaExpiracion, mesExpiracion, anoExpiracion, opcional, subProducto, lineaCredito);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Producto {\n");
    
    sb.append("    codigo: ").append(toIndentedString(codigo)).append("\n");
    sb.append("    tipo: ").append(toIndentedString(tipo)).append("\n");
    sb.append("    grupo: ").append(toIndentedString(grupo)).append("\n");
    sb.append("    nombre: ").append(toIndentedString(nombre)).append("\n");
    sb.append("    descripcion: ").append(toIndentedString(descripcion)).append("\n");
    sb.append("    moneda: ").append(toIndentedString(moneda)).append("\n");
    sb.append("    cliente: ").append(toIndentedString(cliente)).append("\n");
    sb.append("    cuenta: ").append(toIndentedString(cuenta)).append("\n");
    sb.append("    cuentaContable: ").append(toIndentedString(cuentaContable)).append("\n");
    sb.append("    montoLinea: ").append(toIndentedString(montoLinea)).append("\n");
    sb.append("    saldoDeuda: ").append(toIndentedString(saldoDeuda)).append("\n");
    sb.append("    bloqueosCuenta: ").append(toIndentedString(bloqueosCuenta)).append("\n");
    sb.append("    fechaEmision: ").append(toIndentedString(fechaEmision)).append("\n");
    sb.append("    fechaVencimiento: ").append(toIndentedString(fechaVencimiento)).append("\n");
    sb.append("    totalSoles: ").append(toIndentedString(totalSoles)).append("\n");
    sb.append("    totalDolares: ").append(toIndentedString(totalDolares)).append("\n");
    sb.append("    diaExpiracion: ").append(toIndentedString(diaExpiracion)).append("\n");
    sb.append("    mesExpiracion: ").append(toIndentedString(mesExpiracion)).append("\n");
    sb.append("    anoExpiracion: ").append(toIndentedString(anoExpiracion)).append("\n");
    sb.append("    opcional: ").append(toIndentedString(opcional)).append("\n");
    sb.append("    subProducto: ").append(toIndentedString(subProducto)).append("\n");
    sb.append("    lineaCredito: ").append(toIndentedString(lineaCredito)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

