/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Objects;

/**
 * Promesa
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class Promesa   {
  @JsonProperty("producto")
  private Producto producto = null;

  @JsonProperty("obligacion")
  private String obligacion = null;

  @JsonProperty("fechaPacto")
  private Date fechaPacto = null;

  @JsonProperty("fechaVencimiento")
  private Date fechaVencimiento = null;

  @JsonProperty("cantidadAPagar")
  private BigDecimal cantidadAPagar = null;

  @JsonProperty("diasMora")
  private BigDecimal diasMora = null;

  @JsonProperty("moneda")
  private CodigosMonedas moneda = null;

  public Promesa producto(Producto producto) {
    this.producto = producto;
    return this;
  }

  /**
   * Get producto
   * @return producto
   **/
  @JsonProperty("producto")
  @ApiModelProperty(value = "")
  public Producto getProducto() {
    return producto;
  }

  public void setProducto(Producto producto) {
    this.producto = producto;
  }

  public Promesa obligacion(String obligacion) {
    this.obligacion = obligacion;
    return this;
  }

  /**
   * Obligación
   * @return obligacion
   **/
  @JsonProperty("obligacion")
  @ApiModelProperty(value = "Obligación")
  public String getObligacion() {
    return obligacion;
  }

  public void setObligacion(String obligacion) {
    this.obligacion = obligacion;
  }

  public Promesa fechaPacto(Date fechaPacto) {
    this.fechaPacto = fechaPacto;
    return this;
  }

  /**
   * Fecha Pacto
   * @return fechaPacto
   **/
  @JsonProperty("fechaPacto")
  @ApiModelProperty(value = "Fecha Pacto")
  public Date getFechaPacto() {
    return fechaPacto;
  }

  public void setFechaPacto(Date fechaPacto) {
    this.fechaPacto = fechaPacto;
  }

  public Promesa fechaVencimiento(Date fechaVencimiento) {
    this.fechaVencimiento = fechaVencimiento;
    return this;
  }

  /**
   * Fecha Vencimiento
   * @return fechaVencimiento
   **/
  @JsonProperty("fechaVencimiento")
  @ApiModelProperty(value = "Fecha Vencimiento")
  public Date getFechaVencimiento() {
    return fechaVencimiento;
  }

  public void setFechaVencimiento(Date fechaVencimiento) {
    this.fechaVencimiento = fechaVencimiento;
  }

  public Promesa cantidadAPagar(BigDecimal cantidadAPagar) {
    this.cantidadAPagar = cantidadAPagar;
    return this;
  }

  /**
   * Cantidad a Pagar
   * @return cantidadAPagar
   **/
  @JsonProperty("cantidadAPagar")
  @ApiModelProperty(value = "Cantidad a Pagar")
  public BigDecimal getCantidadAPagar() {
    return cantidadAPagar;
  }

  public void setCantidadAPagar(BigDecimal cantidadAPagar) {
    this.cantidadAPagar = cantidadAPagar;
  }

  public Promesa diasMora(BigDecimal diasMora) {
    this.diasMora = diasMora;
    return this;
  }

  /**
   * Dias de Mora
   * @return diasMora
   **/
  @JsonProperty("diasMora")
  @ApiModelProperty(value = "Dias de Mora")
  public BigDecimal getDiasMora() {
    return diasMora;
  }

  public void setDiasMora(BigDecimal diasMora) {
    this.diasMora = diasMora;
  }

  public Promesa moneda(CodigosMonedas moneda) {
    this.moneda = moneda;
    return this;
  }

  /**
   * Get moneda
   * @return moneda
   **/
  @JsonProperty("moneda")
  @ApiModelProperty(value = "")
  public CodigosMonedas getMoneda() {
    return moneda;
  }

  public void setMoneda(CodigosMonedas moneda) {
    this.moneda = moneda;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Promesa promesa = (Promesa) o;
    return Objects.equals(this.producto, promesa.producto) &&
        Objects.equals(this.obligacion, promesa.obligacion) &&
        Objects.equals(this.fechaPacto, promesa.fechaPacto) &&
        Objects.equals(this.fechaVencimiento, promesa.fechaVencimiento) &&
        Objects.equals(this.cantidadAPagar, promesa.cantidadAPagar) &&
        Objects.equals(this.diasMora, promesa.diasMora) &&
        Objects.equals(this.moneda, promesa.moneda);
  }

  @Override
  public int hashCode() {
    return Objects.hash(producto, obligacion, fechaPacto, fechaVencimiento, cantidadAPagar, diasMora, moneda);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Promesa {\n");
    
    sb.append("    producto: ").append(toIndentedString(producto)).append("\n");
    sb.append("    obligacion: ").append(toIndentedString(obligacion)).append("\n");
    sb.append("    fechaPacto: ").append(toIndentedString(fechaPacto)).append("\n");
    sb.append("    fechaVencimiento: ").append(toIndentedString(fechaVencimiento)).append("\n");
    sb.append("    cantidadAPagar: ").append(toIndentedString(cantidadAPagar)).append("\n");
    sb.append("    diasMora: ").append(toIndentedString(diasMora)).append("\n");
    sb.append("    moneda: ").append(toIndentedString(moneda)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

