/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotNull;
import java.util.Objects;

/**
 * Recaudador
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class Recaudador   {
  @JsonProperty("codigo")
  private String codigo = null;

  @JsonProperty("documento")
  private String documento = null;

  @JsonProperty("nombre")
  private String nombre = null;

  @JsonProperty("estado")
  private String estado = null;

  public Recaudador codigo(String codigo) {
    this.codigo = codigo;
    return this;
  }

  /**
   * Código identificador del recaudador en el sistema
   * @return codigo
   **/
  @JsonProperty("codigo")
  @ApiModelProperty(required = true, value = "Código identificador del recaudador en el sistema")
  @NotNull
  public String getCodigo() {
    return codigo;
  }

  public void setCodigo(String codigo) {
    this.codigo = codigo;
  }

  public Recaudador documento(String documento) {
    this.documento = documento;
    return this;
  }

  /**
   * Identificador legal del recaudador en el sistema.
   * @return documento
   **/
  @JsonProperty("documento")
  @ApiModelProperty(value = "Identificador legal del recaudador en el sistema.")
  public String getDocumento() {
    return documento;
  }

  public void setDocumento(String documento) {
    this.documento = documento;
  }

  public Recaudador nombre(String nombre) {
    this.nombre = nombre;
    return this;
  }

  /**
   * Nombre de fantasía del recaudador.
   * @return nombre
   **/
  @JsonProperty("nombre")
  @ApiModelProperty(value = "Nombre de fantasía del recaudador.")
  public String getNombre() {
    return nombre;
  }

  public void setNombre(String nombre) {
    this.nombre = nombre;
  }

  public Recaudador estado(String estado) {
    this.estado = estado;
    return this;
  }

  /**
   * Estado asociado al recaudador, ver apartado con códigos de estado.
   * @return estado
   **/
  @JsonProperty("estado")
  @ApiModelProperty(value = "Estado asociado al recaudador, ver apartado con códigos de estado.")
  public String getEstado() {
    return estado;
  }

  public void setEstado(String estado) {
    this.estado = estado;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Recaudador recaudador = (Recaudador) o;
    return Objects.equals(this.codigo, recaudador.codigo) &&
        Objects.equals(this.documento, recaudador.documento) &&
        Objects.equals(this.nombre, recaudador.nombre) &&
        Objects.equals(this.estado, recaudador.estado);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codigo, documento, nombre, estado);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Recaudador {\n");
    
    sb.append("    codigo: ").append(toIndentedString(codigo)).append("\n");
    sb.append("    documento: ").append(toIndentedString(documento)).append("\n");
    sb.append("    nombre: ").append(toIndentedString(nombre)).append("\n");
    sb.append("    estado: ").append(toIndentedString(estado)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

