/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.DecimalMax;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Objects;

/**
 * Reclamo
 */
@ApiModel(description = "Reclamo")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class Reclamo   {
  @JsonProperty("numero")
  private BigDecimal numero = null;

  @JsonProperty("cliente")
  private Cliente cliente = null;

  @JsonProperty("subTipo")
  private SubTipoReclamo subTipo = null;

  @JsonProperty("estado")
  private EstadoReclamo estado = null;

  @JsonProperty("fechaIngreso")
  private Date fechaIngreso = null;

  @JsonProperty("fechaCambioEstado")
  private Date fechaCambioEstado = null;

  @JsonProperty("responsable")
  private ResponsableReclamo responsable = null;

  @JsonProperty("sectorResponsable")
  private Sector sectorResponsable = null;

  public Reclamo numero(BigDecimal numero) {
    this.numero = numero;
    return this;
  }

  /**
   * Número de reclamo.
   * maximum: 10
   * @return numero
   **/
  @JsonProperty("numero")
  @ApiModelProperty(value = "Número de reclamo.")
 @DecimalMax("10")  public BigDecimal getNumero() {
    return numero;
  }

  public void setNumero(BigDecimal numero) {
    this.numero = numero;
  }

  public Reclamo cliente(Cliente cliente) {
    this.cliente = cliente;
    return this;
  }

  /**
   * Get cliente
   * @return cliente
   **/
  @JsonProperty("cliente")
  @ApiModelProperty(value = "")
  public Cliente getCliente() {
    return cliente;
  }

  public void setCliente(Cliente cliente) {
    this.cliente = cliente;
  }

  public Reclamo subTipo(SubTipoReclamo subTipo) {
    this.subTipo = subTipo;
    return this;
  }

  /**
   * Get subTipo
   * @return subTipo
   **/
  @JsonProperty("subTipo")
  @ApiModelProperty(value = "")
  public SubTipoReclamo getSubTipo() {
    return subTipo;
  }

  public void setSubTipo(SubTipoReclamo subTipo) {
    this.subTipo = subTipo;
  }

  public Reclamo estado(EstadoReclamo estado) {
    this.estado = estado;
    return this;
  }

  /**
   * Get estado
   * @return estado
   **/
  @JsonProperty("estado")
  @ApiModelProperty(value = "")
  public EstadoReclamo getEstado() {
    return estado;
  }

  public void setEstado(EstadoReclamo estado) {
    this.estado = estado;
  }

  public Reclamo fechaIngreso(Date fechaIngreso) {
    this.fechaIngreso = fechaIngreso;
    return this;
  }

  /**
   * Fecha de Alta del reclamo
   * @return fechaIngreso
   **/
  @JsonProperty("fechaIngreso")
  @ApiModelProperty(value = "Fecha de Alta del reclamo")
  public Date getFechaIngreso() {
    return fechaIngreso;
  }

  public void setFechaIngreso(Date fechaIngreso) {
    this.fechaIngreso = fechaIngreso;
  }

  public Reclamo fechaCambioEstado(Date fechaCambioEstado) {
    this.fechaCambioEstado = fechaCambioEstado;
    return this;
  }

  /**
   * Fecha de último cambio de estado
   * @return fechaCambioEstado
   **/
  @JsonProperty("fechaCambioEstado")
  @ApiModelProperty(value = "Fecha de último cambio de estado")
  public Date getFechaCambioEstado() {
    return fechaCambioEstado;
  }

  public void setFechaCambioEstado(Date fechaCambioEstado) {
    this.fechaCambioEstado = fechaCambioEstado;
  }

  public Reclamo responsable(ResponsableReclamo responsable) {
    this.responsable = responsable;
    return this;
  }

  /**
   * Get responsable
   * @return responsable
   **/
  @JsonProperty("responsable")
  @ApiModelProperty(value = "")
  public ResponsableReclamo getResponsable() {
    return responsable;
  }

  public void setResponsable(ResponsableReclamo responsable) {
    this.responsable = responsable;
  }

  public Reclamo sectorResponsable(Sector sectorResponsable) {
    this.sectorResponsable = sectorResponsable;
    return this;
  }

  /**
   * Get sectorResponsable
   * @return sectorResponsable
   **/
  @JsonProperty("sectorResponsable")
  @ApiModelProperty(value = "")
  public Sector getSectorResponsable() {
    return sectorResponsable;
  }

  public void setSectorResponsable(Sector sectorResponsable) {
    this.sectorResponsable = sectorResponsable;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Reclamo reclamo = (Reclamo) o;
    return Objects.equals(this.numero, reclamo.numero) &&
        Objects.equals(this.cliente, reclamo.cliente) &&
        Objects.equals(this.subTipo, reclamo.subTipo) &&
        Objects.equals(this.estado, reclamo.estado) &&
        Objects.equals(this.fechaIngreso, reclamo.fechaIngreso) &&
        Objects.equals(this.fechaCambioEstado, reclamo.fechaCambioEstado) &&
        Objects.equals(this.responsable, reclamo.responsable) &&
        Objects.equals(this.sectorResponsable, reclamo.sectorResponsable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numero, cliente, subTipo, estado, fechaIngreso, fechaCambioEstado, responsable, sectorResponsable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Reclamo {\n");
    
    sb.append("    numero: ").append(toIndentedString(numero)).append("\n");
    sb.append("    cliente: ").append(toIndentedString(cliente)).append("\n");
    sb.append("    subTipo: ").append(toIndentedString(subTipo)).append("\n");
    sb.append("    estado: ").append(toIndentedString(estado)).append("\n");
    sb.append("    fechaIngreso: ").append(toIndentedString(fechaIngreso)).append("\n");
    sb.append("    fechaCambioEstado: ").append(toIndentedString(fechaCambioEstado)).append("\n");
    sb.append("    responsable: ").append(toIndentedString(responsable)).append("\n");
    sb.append("    sectorResponsable: ").append(toIndentedString(sectorResponsable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

