/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Objects;

/**
 * Informaciones de Monitor
 */
@ApiModel(description = "Informaciones de Monitor")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class RegistroMonitor   {
  @JsonProperty("fechaSistema")
  private Date fechaSistema = null;

  @JsonProperty("estado")
  private BigDecimal estado = null;

  @JsonProperty("transaccion")
  private Transaccion transaccion = null;

  @JsonProperty("documentoCliente")
  private DocumentoCliente documentoCliente = null;

  @JsonProperty("proveedorServiciosInternet")
  private ProveedorServiciosInternet proveedorServiciosInternet = null;

  @JsonProperty("codigoRespuestaIBS")
  private String codigoRespuestaIBS = null;

  @JsonProperty("codigoDestinoClienteInstitucion")
  private String codigoDestinoClienteInstitucion = null;

  @JsonProperty("cuentaOrigemTransaccion")
  private Cuenta cuentaOrigemTransaccion = null;

  @JsonProperty("claveControlTransferenciaInterbancaria")
  private String claveControlTransferenciaInterbancaria = null;

  @JsonProperty("segmentacionGeograficaSucursales")
  private String segmentacionGeograficaSucursales = null;

  @JsonProperty("numeroOperacion")
  private String numeroOperacion = null;

  @JsonProperty("codigoIdentificacionOperacion")
  private String codigoIdentificacionOperacion = null;

  @JsonProperty("codigoRecarga")
  private String codigoRecarga = null;

  @JsonProperty("fechaTransaccionDepositoChequeAjeno")
  private Date fechaTransaccionDepositoChequeAjeno = null;

  @JsonProperty("numeroOficinaReceptoraTransferencia")
  private String numeroOficinaReceptoraTransferencia = null;

  @JsonProperty("usuarioBanca")
  private Usuario usuarioBanca = null;

  @JsonProperty("codigoAgrupacionTransacciones")
  private String codigoAgrupacionTransacciones = null;

  @JsonProperty("numeroInicialHojaLibretaAhorro")
  private BigDecimal numeroInicialHojaLibretaAhorro = null;

  @JsonProperty("numeroFinalHojaLibretaAhorro")
  private BigDecimal numeroFinalHojaLibretaAhorro = null;

  @JsonProperty("numeroUltimaHojaTalonario")
  private BigDecimal numeroUltimaHojaTalonario = null;

  @JsonProperty("signoSaldoDisponible")
  private String signoSaldoDisponible = null;

  @JsonProperty("valorCampoAnteriorCambio")
  private String valorCampoAnteriorCambio = null;

  @JsonProperty("valorCampoPosteriorCambio")
  private String valorCampoPosteriorCambio = null;

  @JsonProperty("codigoTipoNovedad")
  private String codigoTipoNovedad = null;

  @JsonProperty("codigoTipoSucursalRealizacionTransaccion")
  private String codigoTipoSucursalRealizacionTransaccion = null;

  @JsonProperty("codigoSegmentacionInstitucionalClientes")
  private String codigoSegmentacionInstitucionalClientes = null;

  @JsonProperty("lgrClienConstEmpr")
  private String lgrClienConstEmpr = null;

  @JsonProperty("numeroPersonalEmpleado")
  private String numeroPersonalEmpleado = null;

  @JsonProperty("numeroCuentaAcreditanInteresses")
  private String numeroCuentaAcreditanInteresses = null;

  @JsonProperty("numeroIndentificacionPersonalBeneficiario")
  private String numeroIndentificacionPersonalBeneficiario = null;

  @JsonProperty("formaPagamentoInteres")
  private FormaPagamento formaPagamentoInteres = null;

  @JsonProperty("fechaAperturaPlazo")
  private String fechaAperturaPlazo = null;

  @JsonProperty("codigoEmpresaRealizaTransaccion")
  private String codigoEmpresaRealizaTransaccion = null;

  @JsonProperty("cantidadCuotasAbono")
  private Double cantidadCuotasAbono = null;

  @JsonProperty("numeroPixelsPantalla")
  private String numeroPixelsPantalla = null;

  @JsonProperty("numeroColoresPantalla")
  private BigDecimal numeroColoresPantalla = null;

  @JsonProperty("valorTamanoVentanaNavegador")
  private String valorTamanoVentanaNavegador = null;

  @JsonProperty("codigoNavegadorUtilizado")
  private String codigoNavegadorUtilizado = null;

  @JsonProperty("numeroReleaseNavegadorCapturado")
  private BigDecimal numeroReleaseNavegadorCapturado = null;

  @JsonProperty("suministroPago")
  private String suministroPago = null;

  @JsonProperty("reciboPago")
  private String reciboPago = null;

  @JsonProperty("tipoServicioPago")
  private String tipoServicioPago = null;

  @JsonProperty("numeroVersionNavegador")
  private BigDecimal numeroVersionNavegador = null;

  @JsonProperty("sistemaOperativo")
  private String sistemaOperativo = null;

  @JsonProperty("codigoLenguageUtilizado")
  private String codigoLenguageUtilizado = null;

  @JsonProperty("montoAbonarCuentaAbono")
  private Double montoAbonarCuentaAbono = null;

  @JsonProperty("montoRetirarCuentaCargo")
  private Double montoRetirarCuentaCargo = null;

  @JsonProperty("numeroCuentaAbono")
  private String numeroCuentaAbono = null;

  @JsonProperty("numeroCuentaRetira")
  private String numeroCuentaRetira = null;

  @JsonProperty("monedaAbono")
  private CodigosMonedas monedaAbono = null;

  @JsonProperty("monedaCargo")
  private CodigosMonedas monedaCargo = null;

  public RegistroMonitor fechaSistema(Date fechaSistema) {
    this.fechaSistema = fechaSistema;
    return this;
  }

  /**
   * fecha de insercion del registro
   * @return fechaSistema
   **/
  @JsonProperty("fechaSistema")
  @ApiModelProperty(value = "fecha de insercion del registro")
  public Date getFechaSistema() {
    return fechaSistema;
  }

  public void setFechaSistema(Date fechaSistema) {
    this.fechaSistema = fechaSistema;
  }

  public RegistroMonitor estado(BigDecimal estado) {
    this.estado = estado;
    return this;
  }

  /**
   * 1 Almacena el estado al iniciar el proceso monitor
   * @return estado
   **/
  @JsonProperty("estado")
  @ApiModelProperty(value = "1 Almacena el estado al iniciar el proceso monitor")
  public BigDecimal getEstado() {
    return estado;
  }

  public void setEstado(BigDecimal estado) {
    this.estado = estado;
  }

  public RegistroMonitor transaccion(Transaccion transaccion) {
    this.transaccion = transaccion;
    return this;
  }

  /**
   * Get transaccion
   * @return transaccion
   **/
  @JsonProperty("transaccion")
  @ApiModelProperty(value = "")
  public Transaccion getTransaccion() {
    return transaccion;
  }

  public void setTransaccion(Transaccion transaccion) {
    this.transaccion = transaccion;
  }

  public RegistroMonitor documentoCliente(DocumentoCliente documentoCliente) {
    this.documentoCliente = documentoCliente;
    return this;
  }

  /**
   * Get documentoCliente
   * @return documentoCliente
   **/
  @JsonProperty("documentoCliente")
  @ApiModelProperty(value = "")
  public DocumentoCliente getDocumentoCliente() {
    return documentoCliente;
  }

  public void setDocumentoCliente(DocumentoCliente documentoCliente) {
    this.documentoCliente = documentoCliente;
  }

  public RegistroMonitor proveedorServiciosInternet(ProveedorServiciosInternet proveedorServiciosInternet) {
    this.proveedorServiciosInternet = proveedorServiciosInternet;
    return this;
  }

  /**
   * Get proveedorServiciosInternet
   * @return proveedorServiciosInternet
   **/
  @JsonProperty("proveedorServiciosInternet")
  @ApiModelProperty(value = "")
  public ProveedorServiciosInternet getProveedorServiciosInternet() {
    return proveedorServiciosInternet;
  }

  public void setProveedorServiciosInternet(ProveedorServiciosInternet proveedorServiciosInternet) {
    this.proveedorServiciosInternet = proveedorServiciosInternet;
  }

  public RegistroMonitor codigoRespuestaIBS(String codigoRespuestaIBS) {
    this.codigoRespuestaIBS = codigoRespuestaIBS;
    return this;
  }

  /**
   * Codigo de respuesta IBS
   * @return codigoRespuestaIBS
   **/
  @JsonProperty("codigoRespuestaIBS")
  @ApiModelProperty(value = "Codigo de respuesta IBS")
  public String getCodigoRespuestaIBS() {
    return codigoRespuestaIBS;
  }

  public void setCodigoRespuestaIBS(String codigoRespuestaIBS) {
    this.codigoRespuestaIBS = codigoRespuestaIBS;
  }

  public RegistroMonitor codigoDestinoClienteInstitucion(String codigoDestinoClienteInstitucion) {
    this.codigoDestinoClienteInstitucion = codigoDestinoClienteInstitucion;
    return this;
  }

  /**
   * Código interno Destino que identifica al Cliente en la Institución
   * @return codigoDestinoClienteInstitucion
   **/
  @JsonProperty("codigoDestinoClienteInstitucion")
  @ApiModelProperty(value = "Código interno Destino que identifica al Cliente en la Institución")
  public String getCodigoDestinoClienteInstitucion() {
    return codigoDestinoClienteInstitucion;
  }

  public void setCodigoDestinoClienteInstitucion(String codigoDestinoClienteInstitucion) {
    this.codigoDestinoClienteInstitucion = codigoDestinoClienteInstitucion;
  }

  public RegistroMonitor cuentaOrigemTransaccion(Cuenta cuentaOrigemTransaccion) {
    this.cuentaOrigemTransaccion = cuentaOrigemTransaccion;
    return this;
  }

  /**
   * Get cuentaOrigemTransaccion
   * @return cuentaOrigemTransaccion
   **/
  @JsonProperty("cuentaOrigemTransaccion")
  @ApiModelProperty(value = "")
  public Cuenta getCuentaOrigemTransaccion() {
    return cuentaOrigemTransaccion;
  }

  public void setCuentaOrigemTransaccion(Cuenta cuentaOrigemTransaccion) {
    this.cuentaOrigemTransaccion = cuentaOrigemTransaccion;
  }

  public RegistroMonitor claveControlTransferenciaInterbancaria(String claveControlTransferenciaInterbancaria) {
    this.claveControlTransferenciaInterbancaria = claveControlTransferenciaInterbancaria;
    return this;
  }

  /**
   * Clave que se genera como llave de control en una transferencia Interbancaria
   * @return claveControlTransferenciaInterbancaria
   **/
  @JsonProperty("claveControlTransferenciaInterbancaria")
  @ApiModelProperty(value = "Clave que se genera como llave de control en una transferencia Interbancaria")
  public String getClaveControlTransferenciaInterbancaria() {
    return claveControlTransferenciaInterbancaria;
  }

  public void setClaveControlTransferenciaInterbancaria(String claveControlTransferenciaInterbancaria) {
    this.claveControlTransferenciaInterbancaria = claveControlTransferenciaInterbancaria;
  }

  public RegistroMonitor segmentacionGeograficaSucursales(String segmentacionGeograficaSucursales) {
    this.segmentacionGeograficaSucursales = segmentacionGeograficaSucursales;
    return this;
  }

  /**
   * Segmentación Geográfica, Institucional, etc. De las sucursales dentro de la Institución
   * @return segmentacionGeograficaSucursales
   **/
  @JsonProperty("segmentacionGeograficaSucursales")
  @ApiModelProperty(value = "Segmentación Geográfica, Institucional, etc. De las sucursales dentro de la Institución")
  public String getSegmentacionGeograficaSucursales() {
    return segmentacionGeograficaSucursales;
  }

  public void setSegmentacionGeograficaSucursales(String segmentacionGeograficaSucursales) {
    this.segmentacionGeograficaSucursales = segmentacionGeograficaSucursales;
  }

  public RegistroMonitor numeroOperacion(String numeroOperacion) {
    this.numeroOperacion = numeroOperacion;
    return this;
  }

  /**
   * Número de operación (respuesta de programa de disposición)
   * @return numeroOperacion
   **/
  @JsonProperty("numeroOperacion")
  @ApiModelProperty(value = "Número de operación (respuesta de programa de disposición)")
  public String getNumeroOperacion() {
    return numeroOperacion;
  }

  public void setNumeroOperacion(String numeroOperacion) {
    this.numeroOperacion = numeroOperacion;
  }

  public RegistroMonitor codigoIdentificacionOperacion(String codigoIdentificacionOperacion) {
    this.codigoIdentificacionOperacion = codigoIdentificacionOperacion;
    return this;
  }

  /**
   * Código de Tipo de Mensaje de la Operación Realizada.
   * @return codigoIdentificacionOperacion
   **/
  @JsonProperty("codigoIdentificacionOperacion")
  @ApiModelProperty(value = "Código de Tipo de Mensaje de la Operación Realizada.")
  public String getCodigoIdentificacionOperacion() {
    return codigoIdentificacionOperacion;
  }

  public void setCodigoIdentificacionOperacion(String codigoIdentificacionOperacion) {
    this.codigoIdentificacionOperacion = codigoIdentificacionOperacion;
  }

  public RegistroMonitor codigoRecarga(String codigoRecarga) {
    this.codigoRecarga = codigoRecarga;
    return this;
  }

  /**
   * Campo que Identifica un Código de Recargas (Internet, Audio en Línea, Etc.)
   * @return codigoRecarga
   **/
  @JsonProperty("codigoRecarga")
  @ApiModelProperty(value = "Campo que Identifica un Código de Recargas (Internet, Audio en Línea, Etc.)")
  public String getCodigoRecarga() {
    return codigoRecarga;
  }

  public void setCodigoRecarga(String codigoRecarga) {
    this.codigoRecarga = codigoRecarga;
  }

  public RegistroMonitor fechaTransaccionDepositoChequeAjeno(Date fechaTransaccionDepositoChequeAjeno) {
    this.fechaTransaccionDepositoChequeAjeno = fechaTransaccionDepositoChequeAjeno;
    return this;
  }

  /**
   * Fecha que se realizara la Compensación si la Transacción es un Deposito con Cheques Ajenos. Formato AAAAMMDD
   * @return fechaTransaccionDepositoChequeAjeno
   **/
  @JsonProperty("fechaTransaccionDepositoChequeAjeno")
  @ApiModelProperty(value = "Fecha que se realizara la Compensación si la Transacción es un Deposito con Cheques Ajenos. Formato AAAAMMDD")
  public Date getFechaTransaccionDepositoChequeAjeno() {
    return fechaTransaccionDepositoChequeAjeno;
  }

  public void setFechaTransaccionDepositoChequeAjeno(Date fechaTransaccionDepositoChequeAjeno) {
    this.fechaTransaccionDepositoChequeAjeno = fechaTransaccionDepositoChequeAjeno;
  }

  public RegistroMonitor numeroOficinaReceptoraTransferencia(String numeroOficinaReceptoraTransferencia) {
    this.numeroOficinaReceptoraTransferencia = numeroOficinaReceptoraTransferencia;
    return this;
  }

  /**
   * Número de Agencia, Oficina o Sucursal que es la receptora de Transferencias.
   * @return numeroOficinaReceptoraTransferencia
   **/
  @JsonProperty("numeroOficinaReceptoraTransferencia")
  @ApiModelProperty(value = "Número de Agencia, Oficina o Sucursal que es la receptora de Transferencias.")
  public String getNumeroOficinaReceptoraTransferencia() {
    return numeroOficinaReceptoraTransferencia;
  }

  public void setNumeroOficinaReceptoraTransferencia(String numeroOficinaReceptoraTransferencia) {
    this.numeroOficinaReceptoraTransferencia = numeroOficinaReceptoraTransferencia;
  }

  public RegistroMonitor usuarioBanca(Usuario usuarioBanca) {
    this.usuarioBanca = usuarioBanca;
    return this;
  }

  /**
   * Get usuarioBanca
   * @return usuarioBanca
   **/
  @JsonProperty("usuarioBanca")
  @ApiModelProperty(value = "")
  public Usuario getUsuarioBanca() {
    return usuarioBanca;
  }

  public void setUsuarioBanca(Usuario usuarioBanca) {
    this.usuarioBanca = usuarioBanca;
  }

  public RegistroMonitor codigoAgrupacionTransacciones(String codigoAgrupacionTransacciones) {
    this.codigoAgrupacionTransacciones = codigoAgrupacionTransacciones;
    return this;
  }

  /**
   * Código que indica una Agrupación de las Transacciones
   * @return codigoAgrupacionTransacciones
   **/
  @JsonProperty("codigoAgrupacionTransacciones")
  @ApiModelProperty(value = "Código que indica una Agrupación de las Transacciones")
  public String getCodigoAgrupacionTransacciones() {
    return codigoAgrupacionTransacciones;
  }

  public void setCodigoAgrupacionTransacciones(String codigoAgrupacionTransacciones) {
    this.codigoAgrupacionTransacciones = codigoAgrupacionTransacciones;
  }

  public RegistroMonitor numeroInicialHojaLibretaAhorro(BigDecimal numeroInicialHojaLibretaAhorro) {
    this.numeroInicialHojaLibretaAhorro = numeroInicialHojaLibretaAhorro;
    return this;
  }

  /**
   * Número de Hoja o Talón Inicial de la Libreta de Ahorros que actualmente se esta usando.
   * @return numeroInicialHojaLibretaAhorro
   **/
  @JsonProperty("numeroInicialHojaLibretaAhorro")
  @ApiModelProperty(value = "Número de Hoja o Talón Inicial de la Libreta de Ahorros que actualmente se esta usando.")
  public BigDecimal getNumeroInicialHojaLibretaAhorro() {
    return numeroInicialHojaLibretaAhorro;
  }

  public void setNumeroInicialHojaLibretaAhorro(BigDecimal numeroInicialHojaLibretaAhorro) {
    this.numeroInicialHojaLibretaAhorro = numeroInicialHojaLibretaAhorro;
  }

  public RegistroMonitor numeroFinalHojaLibretaAhorro(BigDecimal numeroFinalHojaLibretaAhorro) {
    this.numeroFinalHojaLibretaAhorro = numeroFinalHojaLibretaAhorro;
    return this;
  }

  /**
   * Número de Hoja o Talón Final de la Libreta de Ahorros que actualmente se esta usando.
   * @return numeroFinalHojaLibretaAhorro
   **/
  @JsonProperty("numeroFinalHojaLibretaAhorro")
  @ApiModelProperty(value = "Número de Hoja o Talón Final de la Libreta de Ahorros que actualmente se esta usando.")
  public BigDecimal getNumeroFinalHojaLibretaAhorro() {
    return numeroFinalHojaLibretaAhorro;
  }

  public void setNumeroFinalHojaLibretaAhorro(BigDecimal numeroFinalHojaLibretaAhorro) {
    this.numeroFinalHojaLibretaAhorro = numeroFinalHojaLibretaAhorro;
  }

  public RegistroMonitor numeroUltimaHojaTalonario(BigDecimal numeroUltimaHojaTalonario) {
    this.numeroUltimaHojaTalonario = numeroUltimaHojaTalonario;
    return this;
  }

  /**
   * Número del Ultima Hoja del Talonario Usada
   * @return numeroUltimaHojaTalonario
   **/
  @JsonProperty("numeroUltimaHojaTalonario")
  @ApiModelProperty(value = "Número del Ultima Hoja del Talonario Usada")
  public BigDecimal getNumeroUltimaHojaTalonario() {
    return numeroUltimaHojaTalonario;
  }

  public void setNumeroUltimaHojaTalonario(BigDecimal numeroUltimaHojaTalonario) {
    this.numeroUltimaHojaTalonario = numeroUltimaHojaTalonario;
  }

  public RegistroMonitor signoSaldoDisponible(String signoSaldoDisponible) {
    this.signoSaldoDisponible = signoSaldoDisponible;
    return this;
  }

  /**
   * Signo del Saldo Disponible  (+&#x3D; Positivo, -&#x3D; Negativo)
   * @return signoSaldoDisponible
   **/
  @JsonProperty("signoSaldoDisponible")
  @ApiModelProperty(value = "Signo del Saldo Disponible  (+= Positivo, -= Negativo)")
  public String getSignoSaldoDisponible() {
    return signoSaldoDisponible;
  }

  public void setSignoSaldoDisponible(String signoSaldoDisponible) {
    this.signoSaldoDisponible = signoSaldoDisponible;
  }

  public RegistroMonitor valorCampoAnteriorCambio(String valorCampoAnteriorCambio) {
    this.valorCampoAnteriorCambio = valorCampoAnteriorCambio;
    return this;
  }

  /**
   * Valor que tenia el Campo Anterior al Cambio realizado.
   * @return valorCampoAnteriorCambio
   **/
  @JsonProperty("valorCampoAnteriorCambio")
  @ApiModelProperty(value = "Valor que tenia el Campo Anterior al Cambio realizado.")
  public String getValorCampoAnteriorCambio() {
    return valorCampoAnteriorCambio;
  }

  public void setValorCampoAnteriorCambio(String valorCampoAnteriorCambio) {
    this.valorCampoAnteriorCambio = valorCampoAnteriorCambio;
  }

  public RegistroMonitor valorCampoPosteriorCambio(String valorCampoPosteriorCambio) {
    this.valorCampoPosteriorCambio = valorCampoPosteriorCambio;
    return this;
  }

  /**
   * Valor que tenia el Campo Posterior al Cambio realizado.
   * @return valorCampoPosteriorCambio
   **/
  @JsonProperty("valorCampoPosteriorCambio")
  @ApiModelProperty(value = "Valor que tenia el Campo Posterior al Cambio realizado.")
  public String getValorCampoPosteriorCambio() {
    return valorCampoPosteriorCambio;
  }

  public void setValorCampoPosteriorCambio(String valorCampoPosteriorCambio) {
    this.valorCampoPosteriorCambio = valorCampoPosteriorCambio;
  }

  public RegistroMonitor codigoTipoNovedad(String codigoTipoNovedad) {
    this.codigoTipoNovedad = codigoTipoNovedad;
    return this;
  }

  /**
   * Código del Tipo Novedad que se esta realizando.
   * @return codigoTipoNovedad
   **/
  @JsonProperty("codigoTipoNovedad")
  @ApiModelProperty(value = "Código del Tipo Novedad que se esta realizando.")
  public String getCodigoTipoNovedad() {
    return codigoTipoNovedad;
  }

  public void setCodigoTipoNovedad(String codigoTipoNovedad) {
    this.codigoTipoNovedad = codigoTipoNovedad;
  }

  public RegistroMonitor codigoTipoSucursalRealizacionTransaccion(String codigoTipoSucursalRealizacionTransaccion) {
    this.codigoTipoSucursalRealizacionTransaccion = codigoTipoSucursalRealizacionTransaccion;
    return this;
  }

  /**
   * Código del Tipo de Sucursal donde se esta realizando la Transacción
   * @return codigoTipoSucursalRealizacionTransaccion
   **/
  @JsonProperty("codigoTipoSucursalRealizacionTransaccion")
  @ApiModelProperty(value = "Código del Tipo de Sucursal donde se esta realizando la Transacción")
  public String getCodigoTipoSucursalRealizacionTransaccion() {
    return codigoTipoSucursalRealizacionTransaccion;
  }

  public void setCodigoTipoSucursalRealizacionTransaccion(String codigoTipoSucursalRealizacionTransaccion) {
    this.codigoTipoSucursalRealizacionTransaccion = codigoTipoSucursalRealizacionTransaccion;
  }

  public RegistroMonitor codigoSegmentacionInstitucionalClientes(String codigoSegmentacionInstitucionalClientes) {
    this.codigoSegmentacionInstitucionalClientes = codigoSegmentacionInstitucionalClientes;
    return this;
  }

  /**
   * Código de Segmentación Institucional de los Clientes
   * @return codigoSegmentacionInstitucionalClientes
   **/
  @JsonProperty("codigoSegmentacionInstitucionalClientes")
  @ApiModelProperty(value = "Código de Segmentación Institucional de los Clientes")
  public String getCodigoSegmentacionInstitucionalClientes() {
    return codigoSegmentacionInstitucionalClientes;
  }

  public void setCodigoSegmentacionInstitucionalClientes(String codigoSegmentacionInstitucionalClientes) {
    this.codigoSegmentacionInstitucionalClientes = codigoSegmentacionInstitucionalClientes;
  }

  public RegistroMonitor lgrClienConstEmpr(String lgrClienConstEmpr) {
    this.lgrClienConstEmpr = lgrClienConstEmpr;
    return this;
  }

  /**
   * Lugar de Nacimiento del Cliente o Lugar de Constitución de la Empresa
   * @return lgrClienConstEmpr
   **/
  @JsonProperty("lgrClienConstEmpr")
  @ApiModelProperty(value = "Lugar de Nacimiento del Cliente o Lugar de Constitución de la Empresa")
  public String getLgrClienConstEmpr() {
    return lgrClienConstEmpr;
  }

  public void setLgrClienConstEmpr(String lgrClienConstEmpr) {
    this.lgrClienConstEmpr = lgrClienConstEmpr;
  }

  public RegistroMonitor numeroPersonalEmpleado(String numeroPersonalEmpleado) {
    this.numeroPersonalEmpleado = numeroPersonalEmpleado;
    return this;
  }

  /**
   * Número de Identificación Personal del Empleado (Cédula, Pasaporte, NIT, RUT,etc.)
   * @return numeroPersonalEmpleado
   **/
  @JsonProperty("numeroPersonalEmpleado")
  @ApiModelProperty(value = "Número de Identificación Personal del Empleado (Cédula, Pasaporte, NIT, RUT,etc.)")
  public String getNumeroPersonalEmpleado() {
    return numeroPersonalEmpleado;
  }

  public void setNumeroPersonalEmpleado(String numeroPersonalEmpleado) {
    this.numeroPersonalEmpleado = numeroPersonalEmpleado;
  }

  public RegistroMonitor numeroCuentaAcreditanInteresses(String numeroCuentaAcreditanInteresses) {
    this.numeroCuentaAcreditanInteresses = numeroCuentaAcreditanInteresses;
    return this;
  }

  /**
   * Número de Cuenta donde se Acreditan los intereses
   * @return numeroCuentaAcreditanInteresses
   **/
  @JsonProperty("numeroCuentaAcreditanInteresses")
  @ApiModelProperty(value = "Número de Cuenta donde se Acreditan los intereses")
  public String getNumeroCuentaAcreditanInteresses() {
    return numeroCuentaAcreditanInteresses;
  }

  public void setNumeroCuentaAcreditanInteresses(String numeroCuentaAcreditanInteresses) {
    this.numeroCuentaAcreditanInteresses = numeroCuentaAcreditanInteresses;
  }

  public RegistroMonitor numeroIndentificacionPersonalBeneficiario(String numeroIndentificacionPersonalBeneficiario) {
    this.numeroIndentificacionPersonalBeneficiario = numeroIndentificacionPersonalBeneficiario;
    return this;
  }

  /**
   * Número de Identificación Personal del Beneficiario (Cédula, Pasaporte, NIT, RUT,etc.)
   * @return numeroIndentificacionPersonalBeneficiario
   **/
  @JsonProperty("numeroIndentificacionPersonalBeneficiario")
  @ApiModelProperty(value = "Número de Identificación Personal del Beneficiario (Cédula, Pasaporte, NIT, RUT,etc.)")
  public String getNumeroIndentificacionPersonalBeneficiario() {
    return numeroIndentificacionPersonalBeneficiario;
  }

  public void setNumeroIndentificacionPersonalBeneficiario(String numeroIndentificacionPersonalBeneficiario) {
    this.numeroIndentificacionPersonalBeneficiario = numeroIndentificacionPersonalBeneficiario;
  }

  public RegistroMonitor formaPagamentoInteres(FormaPagamento formaPagamentoInteres) {
    this.formaPagamentoInteres = formaPagamentoInteres;
    return this;
  }

  /**
   * Get formaPagamentoInteres
   * @return formaPagamentoInteres
   **/
  @JsonProperty("formaPagamentoInteres")
  @ApiModelProperty(value = "")
  public FormaPagamento getFormaPagamentoInteres() {
    return formaPagamentoInteres;
  }

  public void setFormaPagamentoInteres(FormaPagamento formaPagamentoInteres) {
    this.formaPagamentoInteres = formaPagamentoInteres;
  }

  public RegistroMonitor fechaAperturaPlazo(String fechaAperturaPlazo) {
    this.fechaAperturaPlazo = fechaAperturaPlazo;
    return this;
  }

  /**
   * Fecha cuando se Aperturo Originalmente el Plazo.
   * @return fechaAperturaPlazo
   **/
  @JsonProperty("fechaAperturaPlazo")
  @ApiModelProperty(value = "Fecha cuando se Aperturo Originalmente el Plazo.")
  public String getFechaAperturaPlazo() {
    return fechaAperturaPlazo;
  }

  public void setFechaAperturaPlazo(String fechaAperturaPlazo) {
    this.fechaAperturaPlazo = fechaAperturaPlazo;
  }

  public RegistroMonitor codigoEmpresaRealizaTransaccion(String codigoEmpresaRealizaTransaccion) {
    this.codigoEmpresaRealizaTransaccion = codigoEmpresaRealizaTransaccion;
    return this;
  }

  /**
   * Codigo de la empresa que realiza la transaccion
   * @return codigoEmpresaRealizaTransaccion
   **/
  @JsonProperty("codigoEmpresaRealizaTransaccion")
  @ApiModelProperty(value = "Codigo de la empresa que realiza la transaccion")
  public String getCodigoEmpresaRealizaTransaccion() {
    return codigoEmpresaRealizaTransaccion;
  }

  public void setCodigoEmpresaRealizaTransaccion(String codigoEmpresaRealizaTransaccion) {
    this.codigoEmpresaRealizaTransaccion = codigoEmpresaRealizaTransaccion;
  }

  public RegistroMonitor cantidadCuotasAbono(Double cantidadCuotasAbono) {
    this.cantidadCuotasAbono = cantidadCuotasAbono;
    return this;
  }

  /**
   * Describe la cantidad de cuotas o abonos
   * @return cantidadCuotasAbono
   **/
  @JsonProperty("cantidadCuotasAbono")
  @ApiModelProperty(value = "Describe la cantidad de cuotas o abonos")
  public Double getCantidadCuotasAbono() {
    return cantidadCuotasAbono;
  }

  public void setCantidadCuotasAbono(Double cantidadCuotasAbono) {
    this.cantidadCuotasAbono = cantidadCuotasAbono;
  }

  public RegistroMonitor numeroPixelsPantalla(String numeroPixelsPantalla) {
    this.numeroPixelsPantalla = numeroPixelsPantalla;
    return this;
  }

  /**
   * Número de Pixeles que pueden ser mostrados en la Pantalla (320 x 800, 1280 x 800, etc.)
   * @return numeroPixelsPantalla
   **/
  @JsonProperty("numeroPixelsPantalla")
  @ApiModelProperty(value = "Número de Pixeles que pueden ser mostrados en la Pantalla (320 x 800, 1280 x 800, etc.)")
  public String getNumeroPixelsPantalla() {
    return numeroPixelsPantalla;
  }

  public void setNumeroPixelsPantalla(String numeroPixelsPantalla) {
    this.numeroPixelsPantalla = numeroPixelsPantalla;
  }

  public RegistroMonitor numeroColoresPantalla(BigDecimal numeroColoresPantalla) {
    this.numeroColoresPantalla = numeroColoresPantalla;
    return this;
  }

  /**
   * Número de colores que tenia la Pantalla ( 16 Bits, 32 Bits, Etc.)
   * @return numeroColoresPantalla
   **/
  @JsonProperty("numeroColoresPantalla")
  @ApiModelProperty(value = "Número de colores que tenia la Pantalla ( 16 Bits, 32 Bits, Etc.)")
  public BigDecimal getNumeroColoresPantalla() {
    return numeroColoresPantalla;
  }

  public void setNumeroColoresPantalla(BigDecimal numeroColoresPantalla) {
    this.numeroColoresPantalla = numeroColoresPantalla;
  }

  public RegistroMonitor valorTamanoVentanaNavegador(String valorTamanoVentanaNavegador) {
    this.valorTamanoVentanaNavegador = valorTamanoVentanaNavegador;
    return this;
  }

  /**
   * Valor del tamaño de la Ventana del Browser
   * @return valorTamanoVentanaNavegador
   **/
  @JsonProperty("valorTamanoVentanaNavegador")
  @ApiModelProperty(value = "Valor del tamaño de la Ventana del Browser")
  public String getValorTamanoVentanaNavegador() {
    return valorTamanoVentanaNavegador;
  }

  public void setValorTamanoVentanaNavegador(String valorTamanoVentanaNavegador) {
    this.valorTamanoVentanaNavegador = valorTamanoVentanaNavegador;
  }

  public RegistroMonitor codigoNavegadorUtilizado(String codigoNavegadorUtilizado) {
    this.codigoNavegadorUtilizado = codigoNavegadorUtilizado;
    return this;
  }

  /**
   * Código asignado al Browser que se esta utilizando
   * @return codigoNavegadorUtilizado
   **/
  @JsonProperty("codigoNavegadorUtilizado")
  @ApiModelProperty(value = "Código asignado al Browser que se esta utilizando")
  public String getCodigoNavegadorUtilizado() {
    return codigoNavegadorUtilizado;
  }

  public void setCodigoNavegadorUtilizado(String codigoNavegadorUtilizado) {
    this.codigoNavegadorUtilizado = codigoNavegadorUtilizado;
  }

  public RegistroMonitor numeroReleaseNavegadorCapturado(BigDecimal numeroReleaseNavegadorCapturado) {
    this.numeroReleaseNavegadorCapturado = numeroReleaseNavegadorCapturado;
    return this;
  }

  /**
   * Número del Reléase del Browser Capturado
   * @return numeroReleaseNavegadorCapturado
   **/
  @JsonProperty("numeroReleaseNavegadorCapturado")
  @ApiModelProperty(value = "Número del Reléase del Browser Capturado")
  public BigDecimal getNumeroReleaseNavegadorCapturado() {
    return numeroReleaseNavegadorCapturado;
  }

  public void setNumeroReleaseNavegadorCapturado(BigDecimal numeroReleaseNavegadorCapturado) {
    this.numeroReleaseNavegadorCapturado = numeroReleaseNavegadorCapturado;
  }

  public RegistroMonitor suministroPago(String suministroPago) {
    this.suministroPago = suministroPago;
    return this;
  }

  /**
   * Suministro de Pago
   * @return suministroPago
   **/
  @JsonProperty("suministroPago")
  @ApiModelProperty(value = "Suministro de Pago")
  public String getSuministroPago() {
    return suministroPago;
  }

  public void setSuministroPago(String suministroPago) {
    this.suministroPago = suministroPago;
  }

  public RegistroMonitor reciboPago(String reciboPago) {
    this.reciboPago = reciboPago;
    return this;
  }

  /**
   * Recibo de Pago
   * @return reciboPago
   **/
  @JsonProperty("reciboPago")
  @ApiModelProperty(value = "Recibo de Pago")
  public String getReciboPago() {
    return reciboPago;
  }

  public void setReciboPago(String reciboPago) {
    this.reciboPago = reciboPago;
  }

  public RegistroMonitor tipoServicioPago(String tipoServicioPago) {
    this.tipoServicioPago = tipoServicioPago;
    return this;
  }

  /**
   * Tipo de Servicio de Pago
   * @return tipoServicioPago
   **/
  @JsonProperty("tipoServicioPago")
  @ApiModelProperty(value = "Tipo de Servicio de Pago")
  public String getTipoServicioPago() {
    return tipoServicioPago;
  }

  public void setTipoServicioPago(String tipoServicioPago) {
    this.tipoServicioPago = tipoServicioPago;
  }

  public RegistroMonitor numeroVersionNavegador(BigDecimal numeroVersionNavegador) {
    this.numeroVersionNavegador = numeroVersionNavegador;
    return this;
  }

  /**
   * Número de la Versión del Browser
   * @return numeroVersionNavegador
   **/
  @JsonProperty("numeroVersionNavegador")
  @ApiModelProperty(value = "Número de la Versión del Browser")
  public BigDecimal getNumeroVersionNavegador() {
    return numeroVersionNavegador;
  }

  public void setNumeroVersionNavegador(BigDecimal numeroVersionNavegador) {
    this.numeroVersionNavegador = numeroVersionNavegador;
  }

  public RegistroMonitor sistemaOperativo(String sistemaOperativo) {
    this.sistemaOperativo = sistemaOperativo;
    return this;
  }

  /**
   * Sistema Operativo
   * @return sistemaOperativo
   **/
  @JsonProperty("sistemaOperativo")
  @ApiModelProperty(value = "Sistema Operativo")
  public String getSistemaOperativo() {
    return sistemaOperativo;
  }

  public void setSistemaOperativo(String sistemaOperativo) {
    this.sistemaOperativo = sistemaOperativo;
  }

  public RegistroMonitor codigoLenguageUtilizado(String codigoLenguageUtilizado) {
    this.codigoLenguageUtilizado = codigoLenguageUtilizado;
    return this;
  }

  /**
   * Código de Lenguaje utilizado.
   * @return codigoLenguageUtilizado
   **/
  @JsonProperty("codigoLenguageUtilizado")
  @ApiModelProperty(value = "Código de Lenguaje utilizado.")
  public String getCodigoLenguageUtilizado() {
    return codigoLenguageUtilizado;
  }

  public void setCodigoLenguageUtilizado(String codigoLenguageUtilizado) {
    this.codigoLenguageUtilizado = codigoLenguageUtilizado;
  }

  public RegistroMonitor montoAbonarCuentaAbono(Double montoAbonarCuentaAbono) {
    this.montoAbonarCuentaAbono = montoAbonarCuentaAbono;
    return this;
  }

  /**
   * Monto a abonar en cuenta abono
   * @return montoAbonarCuentaAbono
   **/
  @JsonProperty("montoAbonarCuentaAbono")
  @ApiModelProperty(value = "Monto a abonar en cuenta abono")
  public Double getMontoAbonarCuentaAbono() {
    return montoAbonarCuentaAbono;
  }

  public void setMontoAbonarCuentaAbono(Double montoAbonarCuentaAbono) {
    this.montoAbonarCuentaAbono = montoAbonarCuentaAbono;
  }

  public RegistroMonitor montoRetirarCuentaCargo(Double montoRetirarCuentaCargo) {
    this.montoRetirarCuentaCargo = montoRetirarCuentaCargo;
    return this;
  }

  /**
   * Monto a retirar de cuenta cargo
   * @return montoRetirarCuentaCargo
   **/
  @JsonProperty("montoRetirarCuentaCargo")
  @ApiModelProperty(value = "Monto a retirar de cuenta cargo")
  public Double getMontoRetirarCuentaCargo() {
    return montoRetirarCuentaCargo;
  }

  public void setMontoRetirarCuentaCargo(Double montoRetirarCuentaCargo) {
    this.montoRetirarCuentaCargo = montoRetirarCuentaCargo;
  }

  public RegistroMonitor numeroCuentaAbono(String numeroCuentaAbono) {
    this.numeroCuentaAbono = numeroCuentaAbono;
    return this;
  }

  /**
   * Numero de cuenta donde se abona el monto
   * @return numeroCuentaAbono
   **/
  @JsonProperty("numeroCuentaAbono")
  @ApiModelProperty(value = "Numero de cuenta donde se abona el monto")
  public String getNumeroCuentaAbono() {
    return numeroCuentaAbono;
  }

  public void setNumeroCuentaAbono(String numeroCuentaAbono) {
    this.numeroCuentaAbono = numeroCuentaAbono;
  }

  public RegistroMonitor numeroCuentaRetira(String numeroCuentaRetira) {
    this.numeroCuentaRetira = numeroCuentaRetira;
    return this;
  }

  /**
   * numero de cuenta donde se retira el monto
   * @return numeroCuentaRetira
   **/
  @JsonProperty("numeroCuentaRetira")
  @ApiModelProperty(value = "numero de cuenta donde se retira el monto")
  public String getNumeroCuentaRetira() {
    return numeroCuentaRetira;
  }

  public void setNumeroCuentaRetira(String numeroCuentaRetira) {
    this.numeroCuentaRetira = numeroCuentaRetira;
  }

  public RegistroMonitor monedaAbono(CodigosMonedas monedaAbono) {
    this.monedaAbono = monedaAbono;
    return this;
  }

  /**
   * Get monedaAbono
   * @return monedaAbono
   **/
  @JsonProperty("monedaAbono")
  @ApiModelProperty(value = "")
  public CodigosMonedas getMonedaAbono() {
    return monedaAbono;
  }

  public void setMonedaAbono(CodigosMonedas monedaAbono) {
    this.monedaAbono = monedaAbono;
  }

  public RegistroMonitor monedaCargo(CodigosMonedas monedaCargo) {
    this.monedaCargo = monedaCargo;
    return this;
  }

  /**
   * Get monedaCargo
   * @return monedaCargo
   **/
  @JsonProperty("monedaCargo")
  @ApiModelProperty(value = "")
  public CodigosMonedas getMonedaCargo() {
    return monedaCargo;
  }

  public void setMonedaCargo(CodigosMonedas monedaCargo) {
    this.monedaCargo = monedaCargo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegistroMonitor registroMonitor = (RegistroMonitor) o;
    return Objects.equals(this.fechaSistema, registroMonitor.fechaSistema) &&
        Objects.equals(this.estado, registroMonitor.estado) &&
        Objects.equals(this.transaccion, registroMonitor.transaccion) &&
        Objects.equals(this.documentoCliente, registroMonitor.documentoCliente) &&
        Objects.equals(this.proveedorServiciosInternet, registroMonitor.proveedorServiciosInternet) &&
        Objects.equals(this.codigoRespuestaIBS, registroMonitor.codigoRespuestaIBS) &&
        Objects.equals(this.codigoDestinoClienteInstitucion, registroMonitor.codigoDestinoClienteInstitucion) &&
        Objects.equals(this.cuentaOrigemTransaccion, registroMonitor.cuentaOrigemTransaccion) &&
        Objects.equals(this.claveControlTransferenciaInterbancaria, registroMonitor.claveControlTransferenciaInterbancaria) &&
        Objects.equals(this.segmentacionGeograficaSucursales, registroMonitor.segmentacionGeograficaSucursales) &&
        Objects.equals(this.numeroOperacion, registroMonitor.numeroOperacion) &&
        Objects.equals(this.codigoIdentificacionOperacion, registroMonitor.codigoIdentificacionOperacion) &&
        Objects.equals(this.codigoRecarga, registroMonitor.codigoRecarga) &&
        Objects.equals(this.fechaTransaccionDepositoChequeAjeno, registroMonitor.fechaTransaccionDepositoChequeAjeno) &&
        Objects.equals(this.numeroOficinaReceptoraTransferencia, registroMonitor.numeroOficinaReceptoraTransferencia) &&
        Objects.equals(this.usuarioBanca, registroMonitor.usuarioBanca) &&
        Objects.equals(this.codigoAgrupacionTransacciones, registroMonitor.codigoAgrupacionTransacciones) &&
        Objects.equals(this.numeroInicialHojaLibretaAhorro, registroMonitor.numeroInicialHojaLibretaAhorro) &&
        Objects.equals(this.numeroFinalHojaLibretaAhorro, registroMonitor.numeroFinalHojaLibretaAhorro) &&
        Objects.equals(this.numeroUltimaHojaTalonario, registroMonitor.numeroUltimaHojaTalonario) &&
        Objects.equals(this.signoSaldoDisponible, registroMonitor.signoSaldoDisponible) &&
        Objects.equals(this.valorCampoAnteriorCambio, registroMonitor.valorCampoAnteriorCambio) &&
        Objects.equals(this.valorCampoPosteriorCambio, registroMonitor.valorCampoPosteriorCambio) &&
        Objects.equals(this.codigoTipoNovedad, registroMonitor.codigoTipoNovedad) &&
        Objects.equals(this.codigoTipoSucursalRealizacionTransaccion, registroMonitor.codigoTipoSucursalRealizacionTransaccion) &&
        Objects.equals(this.codigoSegmentacionInstitucionalClientes, registroMonitor.codigoSegmentacionInstitucionalClientes) &&
        Objects.equals(this.lgrClienConstEmpr, registroMonitor.lgrClienConstEmpr) &&
        Objects.equals(this.numeroPersonalEmpleado, registroMonitor.numeroPersonalEmpleado) &&
        Objects.equals(this.numeroCuentaAcreditanInteresses, registroMonitor.numeroCuentaAcreditanInteresses) &&
        Objects.equals(this.numeroIndentificacionPersonalBeneficiario, registroMonitor.numeroIndentificacionPersonalBeneficiario) &&
        Objects.equals(this.formaPagamentoInteres, registroMonitor.formaPagamentoInteres) &&
        Objects.equals(this.fechaAperturaPlazo, registroMonitor.fechaAperturaPlazo) &&
        Objects.equals(this.codigoEmpresaRealizaTransaccion, registroMonitor.codigoEmpresaRealizaTransaccion) &&
        Objects.equals(this.cantidadCuotasAbono, registroMonitor.cantidadCuotasAbono) &&
        Objects.equals(this.numeroPixelsPantalla, registroMonitor.numeroPixelsPantalla) &&
        Objects.equals(this.numeroColoresPantalla, registroMonitor.numeroColoresPantalla) &&
        Objects.equals(this.valorTamanoVentanaNavegador, registroMonitor.valorTamanoVentanaNavegador) &&
        Objects.equals(this.codigoNavegadorUtilizado, registroMonitor.codigoNavegadorUtilizado) &&
        Objects.equals(this.numeroReleaseNavegadorCapturado, registroMonitor.numeroReleaseNavegadorCapturado) &&
        Objects.equals(this.suministroPago, registroMonitor.suministroPago) &&
        Objects.equals(this.reciboPago, registroMonitor.reciboPago) &&
        Objects.equals(this.tipoServicioPago, registroMonitor.tipoServicioPago) &&
        Objects.equals(this.numeroVersionNavegador, registroMonitor.numeroVersionNavegador) &&
        Objects.equals(this.sistemaOperativo, registroMonitor.sistemaOperativo) &&
        Objects.equals(this.codigoLenguageUtilizado, registroMonitor.codigoLenguageUtilizado) &&
        Objects.equals(this.montoAbonarCuentaAbono, registroMonitor.montoAbonarCuentaAbono) &&
        Objects.equals(this.montoRetirarCuentaCargo, registroMonitor.montoRetirarCuentaCargo) &&
        Objects.equals(this.numeroCuentaAbono, registroMonitor.numeroCuentaAbono) &&
        Objects.equals(this.numeroCuentaRetira, registroMonitor.numeroCuentaRetira) &&
        Objects.equals(this.monedaAbono, registroMonitor.monedaAbono) &&
        Objects.equals(this.monedaCargo, registroMonitor.monedaCargo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fechaSistema, estado, transaccion, documentoCliente, proveedorServiciosInternet, codigoRespuestaIBS, codigoDestinoClienteInstitucion, cuentaOrigemTransaccion, claveControlTransferenciaInterbancaria, segmentacionGeograficaSucursales, numeroOperacion, codigoIdentificacionOperacion, codigoRecarga, fechaTransaccionDepositoChequeAjeno, numeroOficinaReceptoraTransferencia, usuarioBanca, codigoAgrupacionTransacciones, numeroInicialHojaLibretaAhorro, numeroFinalHojaLibretaAhorro, numeroUltimaHojaTalonario, signoSaldoDisponible, valorCampoAnteriorCambio, valorCampoPosteriorCambio, codigoTipoNovedad, codigoTipoSucursalRealizacionTransaccion, codigoSegmentacionInstitucionalClientes, lgrClienConstEmpr, numeroPersonalEmpleado, numeroCuentaAcreditanInteresses, numeroIndentificacionPersonalBeneficiario, formaPagamentoInteres, fechaAperturaPlazo, codigoEmpresaRealizaTransaccion, cantidadCuotasAbono, numeroPixelsPantalla, numeroColoresPantalla, valorTamanoVentanaNavegador, codigoNavegadorUtilizado, numeroReleaseNavegadorCapturado, suministroPago, reciboPago, tipoServicioPago, numeroVersionNavegador, sistemaOperativo, codigoLenguageUtilizado, montoAbonarCuentaAbono, montoRetirarCuentaCargo, numeroCuentaAbono, numeroCuentaRetira, monedaAbono, monedaCargo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegistroMonitor {\n");
    
    sb.append("    fechaSistema: ").append(toIndentedString(fechaSistema)).append("\n");
    sb.append("    estado: ").append(toIndentedString(estado)).append("\n");
    sb.append("    transaccion: ").append(toIndentedString(transaccion)).append("\n");
    sb.append("    documentoCliente: ").append(toIndentedString(documentoCliente)).append("\n");
    sb.append("    proveedorServiciosInternet: ").append(toIndentedString(proveedorServiciosInternet)).append("\n");
    sb.append("    codigoRespuestaIBS: ").append(toIndentedString(codigoRespuestaIBS)).append("\n");
    sb.append("    codigoDestinoClienteInstitucion: ").append(toIndentedString(codigoDestinoClienteInstitucion)).append("\n");
    sb.append("    cuentaOrigemTransaccion: ").append(toIndentedString(cuentaOrigemTransaccion)).append("\n");
    sb.append("    claveControlTransferenciaInterbancaria: ").append(toIndentedString(claveControlTransferenciaInterbancaria)).append("\n");
    sb.append("    segmentacionGeograficaSucursales: ").append(toIndentedString(segmentacionGeograficaSucursales)).append("\n");
    sb.append("    numeroOperacion: ").append(toIndentedString(numeroOperacion)).append("\n");
    sb.append("    codigoIdentificacionOperacion: ").append(toIndentedString(codigoIdentificacionOperacion)).append("\n");
    sb.append("    codigoRecarga: ").append(toIndentedString(codigoRecarga)).append("\n");
    sb.append("    fechaTransaccionDepositoChequeAjeno: ").append(toIndentedString(fechaTransaccionDepositoChequeAjeno)).append("\n");
    sb.append("    numeroOficinaReceptoraTransferencia: ").append(toIndentedString(numeroOficinaReceptoraTransferencia)).append("\n");
    sb.append("    usuarioBanca: ").append(toIndentedString(usuarioBanca)).append("\n");
    sb.append("    codigoAgrupacionTransacciones: ").append(toIndentedString(codigoAgrupacionTransacciones)).append("\n");
    sb.append("    numeroInicialHojaLibretaAhorro: ").append(toIndentedString(numeroInicialHojaLibretaAhorro)).append("\n");
    sb.append("    numeroFinalHojaLibretaAhorro: ").append(toIndentedString(numeroFinalHojaLibretaAhorro)).append("\n");
    sb.append("    numeroUltimaHojaTalonario: ").append(toIndentedString(numeroUltimaHojaTalonario)).append("\n");
    sb.append("    signoSaldoDisponible: ").append(toIndentedString(signoSaldoDisponible)).append("\n");
    sb.append("    valorCampoAnteriorCambio: ").append(toIndentedString(valorCampoAnteriorCambio)).append("\n");
    sb.append("    valorCampoPosteriorCambio: ").append(toIndentedString(valorCampoPosteriorCambio)).append("\n");
    sb.append("    codigoTipoNovedad: ").append(toIndentedString(codigoTipoNovedad)).append("\n");
    sb.append("    codigoTipoSucursalRealizacionTransaccion: ").append(toIndentedString(codigoTipoSucursalRealizacionTransaccion)).append("\n");
    sb.append("    codigoSegmentacionInstitucionalClientes: ").append(toIndentedString(codigoSegmentacionInstitucionalClientes)).append("\n");
    sb.append("    lgrClienConstEmpr: ").append(toIndentedString(lgrClienConstEmpr)).append("\n");
    sb.append("    numeroPersonalEmpleado: ").append(toIndentedString(numeroPersonalEmpleado)).append("\n");
    sb.append("    numeroCuentaAcreditanInteresses: ").append(toIndentedString(numeroCuentaAcreditanInteresses)).append("\n");
    sb.append("    numeroIndentificacionPersonalBeneficiario: ").append(toIndentedString(numeroIndentificacionPersonalBeneficiario)).append("\n");
    sb.append("    formaPagamentoInteres: ").append(toIndentedString(formaPagamentoInteres)).append("\n");
    sb.append("    fechaAperturaPlazo: ").append(toIndentedString(fechaAperturaPlazo)).append("\n");
    sb.append("    codigoEmpresaRealizaTransaccion: ").append(toIndentedString(codigoEmpresaRealizaTransaccion)).append("\n");
    sb.append("    cantidadCuotasAbono: ").append(toIndentedString(cantidadCuotasAbono)).append("\n");
    sb.append("    numeroPixelsPantalla: ").append(toIndentedString(numeroPixelsPantalla)).append("\n");
    sb.append("    numeroColoresPantalla: ").append(toIndentedString(numeroColoresPantalla)).append("\n");
    sb.append("    valorTamanoVentanaNavegador: ").append(toIndentedString(valorTamanoVentanaNavegador)).append("\n");
    sb.append("    codigoNavegadorUtilizado: ").append(toIndentedString(codigoNavegadorUtilizado)).append("\n");
    sb.append("    numeroReleaseNavegadorCapturado: ").append(toIndentedString(numeroReleaseNavegadorCapturado)).append("\n");
    sb.append("    suministroPago: ").append(toIndentedString(suministroPago)).append("\n");
    sb.append("    reciboPago: ").append(toIndentedString(reciboPago)).append("\n");
    sb.append("    tipoServicioPago: ").append(toIndentedString(tipoServicioPago)).append("\n");
    sb.append("    numeroVersionNavegador: ").append(toIndentedString(numeroVersionNavegador)).append("\n");
    sb.append("    sistemaOperativo: ").append(toIndentedString(sistemaOperativo)).append("\n");
    sb.append("    codigoLenguageUtilizado: ").append(toIndentedString(codigoLenguageUtilizado)).append("\n");
    sb.append("    montoAbonarCuentaAbono: ").append(toIndentedString(montoAbonarCuentaAbono)).append("\n");
    sb.append("    montoRetirarCuentaCargo: ").append(toIndentedString(montoRetirarCuentaCargo)).append("\n");
    sb.append("    numeroCuentaAbono: ").append(toIndentedString(numeroCuentaAbono)).append("\n");
    sb.append("    numeroCuentaRetira: ").append(toIndentedString(numeroCuentaRetira)).append("\n");
    sb.append("    monedaAbono: ").append(toIndentedString(monedaAbono)).append("\n");
    sb.append("    monedaCargo: ").append(toIndentedString(monedaCargo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

