/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Resultado del login
 */
public enum ResultadoLogin {
  
  OK("OK"),
  
  ERROR("ERROR"),
  
  USUARIO_BLOQUEADO("USUARIO_BLOQUEADO"),
  
  USUARIO_NO_EXISTE("USUARIO_NO_EXISTE");

  private String value;

  ResultadoLogin(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ResultadoLogin fromValue(String text) {
    for (ResultadoLogin b : ResultadoLogin.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

