/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;

/**
 * SituacionCobranza
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class SituacionCobranza   {
  @JsonProperty("cliente")
  private Cliente cliente = null;

  @JsonProperty("estado")
  private String estado = null;

  @JsonProperty("fechaEntradaEstado")
  private Date fechaEntradaEstado = null;

  @JsonProperty("fechaUltimoContacto")
  private Date fechaUltimoContacto = null;

  @JsonProperty("grupo")
  private String grupo = null;

  @JsonProperty("obligaciones")
  private List<Obligacion> obligaciones = null;

  @JsonProperty("promesas")
  private List<Promesa> promesas = null;

  @JsonProperty("gestiones")
  private List<GestionCobranza> gestiones = null;

  @JsonProperty("direcciones")
  private List<Direccion> direcciones = null;

  @JsonProperty("telefonos")
  private List<Telefono> telefonos = null;

  public SituacionCobranza cliente(Cliente cliente) {
    this.cliente = cliente;
    return this;
  }

  /**
   * Get cliente
   * @return cliente
   **/
  @JsonProperty("cliente")
  @ApiModelProperty(value = "")
  public Cliente getCliente() {
    return cliente;
  }

  public void setCliente(Cliente cliente) {
    this.cliente = cliente;
  }

  public SituacionCobranza estado(String estado) {
    this.estado = estado;
    return this;
  }

  /**
   * Estado del cliente en el sistema de cobranzas
   * @return estado
   **/
  @JsonProperty("estado")
  @ApiModelProperty(value = "Estado del cliente en el sistema de cobranzas")
  public String getEstado() {
    return estado;
  }

  public void setEstado(String estado) {
    this.estado = estado;
  }

  public SituacionCobranza fechaEntradaEstado(Date fechaEntradaEstado) {
    this.fechaEntradaEstado = fechaEntradaEstado;
    return this;
  }

  /**
   * Fecha de entrada en el estado de cobranza
   * @return fechaEntradaEstado
   **/
  @JsonProperty("fechaEntradaEstado")
  @ApiModelProperty(value = "Fecha de entrada en el estado de cobranza")
  public Date getFechaEntradaEstado() {
    return fechaEntradaEstado;
  }

  public void setFechaEntradaEstado(Date fechaEntradaEstado) {
    this.fechaEntradaEstado = fechaEntradaEstado;
  }

  public SituacionCobranza fechaUltimoContacto(Date fechaUltimoContacto) {
    this.fechaUltimoContacto = fechaUltimoContacto;
    return this;
  }

  /**
   * Fecha del último contacto de cobranza
   * @return fechaUltimoContacto
   **/
  @JsonProperty("fechaUltimoContacto")
  @ApiModelProperty(value = "Fecha del último contacto de cobranza")
  public Date getFechaUltimoContacto() {
    return fechaUltimoContacto;
  }

  public void setFechaUltimoContacto(Date fechaUltimoContacto) {
    this.fechaUltimoContacto = fechaUltimoContacto;
  }

  public SituacionCobranza grupo(String grupo) {
    this.grupo = grupo;
    return this;
  }

  /**
   * Grupo de cobranza
   * @return grupo
   **/
  @JsonProperty("grupo")
  @ApiModelProperty(value = "Grupo de cobranza")
  public String getGrupo() {
    return grupo;
  }

  public void setGrupo(String grupo) {
    this.grupo = grupo;
  }

  public SituacionCobranza obligaciones(List<Obligacion> obligaciones) {
    this.obligaciones = obligaciones;
    return this;
  }

  public SituacionCobranza addObligacionesItem(Obligacion obligacionesItem) {
    if (this.obligaciones == null) {
      this.obligaciones = new ArrayList<Obligacion>();
    }
    this.obligaciones.add(obligacionesItem);
    return this;
  }

  /**
   * Get obligaciones
   * @return obligaciones
   **/
  @JsonProperty("obligaciones")
  @ApiModelProperty(value = "")
  public List<Obligacion> getObligaciones() {
    return obligaciones;
  }

  public void setObligaciones(List<Obligacion> obligaciones) {
    this.obligaciones = obligaciones;
  }

  public SituacionCobranza promesas(List<Promesa> promesas) {
    this.promesas = promesas;
    return this;
  }

  public SituacionCobranza addPromesasItem(Promesa promesasItem) {
    if (this.promesas == null) {
      this.promesas = new ArrayList<Promesa>();
    }
    this.promesas.add(promesasItem);
    return this;
  }

  /**
   * Get promesas
   * @return promesas
   **/
  @JsonProperty("promesas")
  @ApiModelProperty(value = "")
  public List<Promesa> getPromesas() {
    return promesas;
  }

  public void setPromesas(List<Promesa> promesas) {
    this.promesas = promesas;
  }

  public SituacionCobranza gestiones(List<GestionCobranza> gestiones) {
    this.gestiones = gestiones;
    return this;
  }

  public SituacionCobranza addGestionesItem(GestionCobranza gestionesItem) {
    if (this.gestiones == null) {
      this.gestiones = new ArrayList<GestionCobranza>();
    }
    this.gestiones.add(gestionesItem);
    return this;
  }

  /**
   * Get gestiones
   * @return gestiones
   **/
  @JsonProperty("gestiones")
  @ApiModelProperty(value = "")
  public List<GestionCobranza> getGestiones() {
    return gestiones;
  }

  public void setGestiones(List<GestionCobranza> gestiones) {
    this.gestiones = gestiones;
  }

  public SituacionCobranza direcciones(List<Direccion> direcciones) {
    this.direcciones = direcciones;
    return this;
  }

  public SituacionCobranza addDireccionesItem(Direccion direccionesItem) {
    if (this.direcciones == null) {
      this.direcciones = new ArrayList<Direccion>();
    }
    this.direcciones.add(direccionesItem);
    return this;
  }

  /**
   * Get direcciones
   * @return direcciones
   **/
  @JsonProperty("direcciones")
  @ApiModelProperty(value = "")
  public List<Direccion> getDirecciones() {
    return direcciones;
  }

  public void setDirecciones(List<Direccion> direcciones) {
    this.direcciones = direcciones;
  }

  public SituacionCobranza telefonos(List<Telefono> telefonos) {
    this.telefonos = telefonos;
    return this;
  }

  public SituacionCobranza addTelefonosItem(Telefono telefonosItem) {
    if (this.telefonos == null) {
      this.telefonos = new ArrayList<Telefono>();
    }
    this.telefonos.add(telefonosItem);
    return this;
  }

  /**
   * Get telefonos
   * @return telefonos
   **/
  @JsonProperty("telefonos")
  @ApiModelProperty(value = "")
  public List<Telefono> getTelefonos() {
    return telefonos;
  }

  public void setTelefonos(List<Telefono> telefonos) {
    this.telefonos = telefonos;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SituacionCobranza situacionCobranza = (SituacionCobranza) o;
    return Objects.equals(this.cliente, situacionCobranza.cliente) &&
        Objects.equals(this.estado, situacionCobranza.estado) &&
        Objects.equals(this.fechaEntradaEstado, situacionCobranza.fechaEntradaEstado) &&
        Objects.equals(this.fechaUltimoContacto, situacionCobranza.fechaUltimoContacto) &&
        Objects.equals(this.grupo, situacionCobranza.grupo) &&
        Objects.equals(this.obligaciones, situacionCobranza.obligaciones) &&
        Objects.equals(this.promesas, situacionCobranza.promesas) &&
        Objects.equals(this.gestiones, situacionCobranza.gestiones) &&
        Objects.equals(this.direcciones, situacionCobranza.direcciones) &&
        Objects.equals(this.telefonos, situacionCobranza.telefonos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cliente, estado, fechaEntradaEstado, fechaUltimoContacto, grupo, obligaciones, promesas, gestiones, direcciones, telefonos);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SituacionCobranza {\n");
    
    sb.append("    cliente: ").append(toIndentedString(cliente)).append("\n");
    sb.append("    estado: ").append(toIndentedString(estado)).append("\n");
    sb.append("    fechaEntradaEstado: ").append(toIndentedString(fechaEntradaEstado)).append("\n");
    sb.append("    fechaUltimoContacto: ").append(toIndentedString(fechaUltimoContacto)).append("\n");
    sb.append("    grupo: ").append(toIndentedString(grupo)).append("\n");
    sb.append("    obligaciones: ").append(toIndentedString(obligaciones)).append("\n");
    sb.append("    promesas: ").append(toIndentedString(promesas)).append("\n");
    sb.append("    gestiones: ").append(toIndentedString(gestiones)).append("\n");
    sb.append("    direcciones: ").append(toIndentedString(direcciones)).append("\n");
    sb.append("    telefonos: ").append(toIndentedString(telefonos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

