/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * TagCorreo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class TagCorreo   {
  @JsonProperty("clave")
  private String clave = null;

  @JsonProperty("descripicion")
  private String descripicion = null;

  public TagCorreo clave(String clave) {
    this.clave = clave;
    return this;
  }

  /**
   * Etiqueta configurada como parámetro
   * @return clave
   **/
  @JsonProperty("clave")
  @ApiModelProperty(value = "Etiqueta configurada como parámetro")
  public String getClave() {
    return clave;
  }

  public void setClave(String clave) {
    this.clave = clave;
  }

  public TagCorreo descripicion(String descripicion) {
    this.descripicion = descripicion;
    return this;
  }

  /**
   * Contenido que se enviará en el correo electrónico através de la clave
   * @return descripicion
   **/
  @JsonProperty("descripicion")
  @ApiModelProperty(value = "Contenido que se enviará en el correo electrónico através de la clave")
  public String getDescripicion() {
    return descripicion;
  }

  public void setDescripicion(String descripicion) {
    this.descripicion = descripicion;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TagCorreo tagCorreo = (TagCorreo) o;
    return Objects.equals(this.clave, tagCorreo.clave) &&
        Objects.equals(this.descripicion, tagCorreo.descripicion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clave, descripicion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TagCorreo {\n");
    
    sb.append("    clave: ").append(toIndentedString(clave)).append("\n");
    sb.append("    descripicion: ").append(toIndentedString(descripicion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

