/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets TiposBusquedaCatalogos
 */
public enum TiposBusquedaCatalogos {
  
  PROFESIONES("PROFESIONES"),
  
  SEGMENTOS("SEGMENTOS"),
  
  PRODUCTOS_BANCO("PRODUCTOS_BANCO"),
  
  SUBPRODUCTO_BANCO("SUBPRODUCTO_BANCO"),
  
  SECTORISTA("SECTORISTA"),
  
  AGENCIAS("AGENCIAS");

  private String value;

  TiposBusquedaCatalogos(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TiposBusquedaCatalogos fromValue(String text) {
    for (TiposBusquedaCatalogos b : TiposBusquedaCatalogos.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

