/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets TipoFrecuenciaAhorro
 */
public enum TipoFrecuenciaAhorro {
  
  DIARIO("DIARIO"),
  
  SEMANAL("SEMANAL"),
  
  MENSUAL("MENSUAL"),
  
  ANUAL("ANUAL");

  private String value;

  TipoFrecuenciaAhorro(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TipoFrecuenciaAhorro fromValue(String text) {
    for (TipoFrecuenciaAhorro b : TipoFrecuenciaAhorro.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

