/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets TipoAhorro
 */
public enum TipoAhorro {
  
  SERVICIO_AHORRO_PROGRAMADO("SERVICIO_AHORRO_PROGRAMADO"),
  
  SERVICIO_AHORRO_VUELTO("SERVICIO_AHORRO_VUELTO"),
  
  MANTENIMIENTO("MANTENIMIENTO");

  private String value;

  TipoAhorro(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TipoAhorro fromValue(String text) {
    for (TipoAhorro b : TipoAhorro.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

