/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets TiposCorreos
 */
public enum TiposCorreos {
  
  CONTROL_LOGIN_NOTIFICACION_IP_MALICIOSO("CONTROL_LOGIN_NOTIFICACION_IP_MALICIOSO"),
  
  CONTROL_LOGIN_BLOQUEO_MAS_DE_UN_CANAL("CONTROL_LOGIN_BLOQUEO_MAS_DE_UN_CANAL"),
  
  AHORRO_PROGRAMADO_OPERACION_NO_PUDO_SER_COMPLETADA("AHORRO_PROGRAMADO_OPERACION_NO_PUDO_SER_COMPLETADA"),
  
  AHORRO_PROGRAMADO_SERVICIO_DE_AHORRO_DESACTIVADO("AHORRO_PROGRAMADO_SERVICIO_DE_AHORRO_DESACTIVADO"),
  
  AHORRO_PROGRAMADO_AHORRO_PROGRAMADO("AHORRO_PROGRAMADO_AHORRO_PROGRAMADO"),

  AHORRO_VUELTO_AHORRO_PROGRAMADO("AHORRO_VUELTO_AHORRO_PROGRAMADO"),
  
  AHORRO_PROGRAMADO_AHORRO_PROGRAMADO_EJECUTADO("AHORRO_PROGRAMADO_AHORRO_PROGRAMADO_EJECUTADO"),
  
  AHORRO_PROGRAMADO_EDICION_DE_AHORRO("AHORRO_PROGRAMADO_EDICION_DE_AHORRO"),

  AHORRO_VUELTO_EDICION_DE_AHORRO("AHORRO_VUELTO_EDICION_DE_AHORRO"),
  
  DISPOSICION_EFECTIVO_OPERACION_COMPLETADA("DISPOSICION_EFECTIVO_OPERACION_COMPLETADA");

  private String value;

  TiposCorreos(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TiposCorreos fromValue(String text) {
    for (TiposCorreos b : TiposCorreos.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

