/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets TiposTagsCorreos
 */
public enum TiposTagsCorreos {
  
  CANTIDAD_BLOQUEO("CANTIDAD_BLOQUEO"),
  
  LISTA_IP("LISTA_IP"),
  
  LISTA_CANALES("LISTA_CANALES"),
  
  NOMBRE_AHORRO("NOMBRE_AHORRO"),
  
  CUENTA_ORIGEN("CUENTA_ORIGEN"),
  
  CUENTA_DESTINO("CUENTA_DESTINO"),
  
  MONTO_POR_AHORRA("MONTO_POR_AHORRA"),
  
  SALDO_DISPONIBLE("SALDO_DISPONIBLE"),
  
  FRECUENCIA_AHORRO("FRECUENCIA_AHORRO"),
  
  CICLO_VIDA("CICLO_VIDA"),
  
  MONTO_POR_AHORRO("MONTO_POR_AHORRO"),
  
  FECHA_FIN("FECHA_FIN"),
  
  NOMEBRE_CLIENTE("NOMEBRE_CLIENTE"),
  
  NUMERO_CONFIMACION("NUMERO_CONFIMACION"),
  
  TARJETA_CREDITO("TARJETA_CREDITO"),
  
  MONTO_CARGO("MONTO_CARGO"),
  
  CUENTA_ABONO("CUENTA_ABONO"),
  
  MONTO_ABONO("MONTO_ABONO"),
  
  ITF("ITF"),
  
  FECHA_HORA("FECHA_HORA"),
  
  DESCRIPCION("DESCRIPCION");

  private String value;

  TiposTagsCorreos(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TiposTagsCorreos fromValue(String text) {
    for (TiposTagsCorreos b : TiposTagsCorreos.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

