/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Identifica el Tipo de Persona del Cliente (J &#x3D; Jurídico, N &#x3D; Natural)
 */
public enum TipoPersona {
  
  JURIDICO("JURIDICO"),
  
  NATURAL("NATURAL");

  private String value;

  TipoPersona(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TipoPersona fromValue(String text) {
    for (TipoPersona b : TipoPersona.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

