/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Gets or Sets TipoAhorroVuelto
 */
public enum TipoAhorroVuelto {
  
  APOXIMACION_SIGUIENTE_UNIDAD("APOXIMACION_SIGUIENTE_UNIDAD"),
  
  APROXIMACION_5_SUPERIOR("APROXIMACION_5_SUPERIOR");

  private String value;

  TipoAhorroVuelto(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TipoAhorroVuelto fromValue(String text) {
    for (TipoAhorroVuelto b : TipoAhorroVuelto.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

