/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Tipos de los procesos
 */
public enum TiposProcesos {
  
  VALIDA("VALIDA"),
  
  EJECUTA("EJECUTA"),
  
  PROCESAR("PROCESAR");

  private String value;

  TiposProcesos(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TiposProcesos fromValue(String text) {
    for (TiposProcesos b : TiposProcesos.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

