/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Tipos de documento
 */
public enum TiposDocumentos {
  
  DNI_LE("DNI_LE"),
  
  CARNET_DE_EXTRANJERIA("CARNET_DE_EXTRANJERIA"),
  
  CARNET_MILITAR("CARNET_MILITAR"),
  
  PASAPORTE("PASAPORTE"),
  
  TEMPORAL("TEMPORAL"),
  
  REGISTRO_UNICO_DEL_CONTRIBUYENTE("REGISTRO_UNICO_DEL_CONTRIBUYENTE"),
  
  AUTOGENERADO("AUTOGENERADO");

  private String value;

  TiposDocumentos(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TiposDocumentos fromValue(String text) {
    for (TiposDocumentos b : TiposDocumentos.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

