/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Tipos de afectación de los pagos
 */
public enum TiposAfectacion {
  
  CAPITAL("CAPITAL"),
  
  CAPITAL_Y_INTERES("CAPITAL_Y_INTERES");

  private String value;

  TiposAfectacion(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TiposAfectacion fromValue(String text) {
    for (TiposAfectacion b : TiposAfectacion.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

