/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Entrante / Saliente
 */
public enum TiposContactoCliente {
  
  ENTRANTE("ENTRANTE"),
  
  SALIENTE("SALIENTE");

  private String value;

  TiposContactoCliente(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TiposContactoCliente fromValue(String text) {
    for (TiposContactoCliente b : TiposContactoCliente.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

