/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Tipos de las transaciones
 */
public enum TiposTransaciones {
  
  CUENTAS_PROPIAS("CUENTAS_PROPIAS"),
  
  CUENTAS_TERCEROS("CUENTAS_TERCEROS"),
  
  OTROS_BANCOS("OTROS BANCOS");

  private String value;

  TiposTransaciones(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TiposTransaciones fromValue(String text) {
    for (TiposTransaciones b : TiposTransaciones.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

