/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Objects;

/**
 * Informaciones de la Transaccion
 */
@ApiModel(description = "Informaciones de la Transaccion")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class Transaccion   {
  @JsonProperty("codigo")
  private String codigo = null;

  @JsonProperty("cuentaAsociada")
  private Cuenta cuentaAsociada = null;

  @JsonProperty("canal")
  private Canal canal = null;

  @JsonProperty("chequera")
  private Chequera chequera = null;

  @JsonProperty("cuentaDestino")
  private Cuenta cuentaDestino = null;

  @JsonProperty("cuentaOrigem")
  private Cuenta cuentaOrigem = null;

  @JsonProperty("montoTotal")
  private Double montoTotal = null;

  @JsonProperty("fecha")
  private Date fecha = null;

  @JsonProperty("transaccionReverso")
  private Boolean transaccionReverso = null;

  @JsonProperty("cheque")
  private Cheque cheque = null;

  @JsonProperty("moneda")
  private CodigosMonedas moneda = null;

  @JsonProperty("usuario")
  private Usuario usuario = null;

  @JsonProperty("atmOrigem")
  private Atm atmOrigem = null;

  @JsonProperty("local")
  private String local = null;

  @JsonProperty("transaccionFraudulenta")
  private Boolean transaccionFraudulenta = null;

  @JsonProperty("origemAlertaFraude")
  private BigDecimal origemAlertaFraude = null;

  @JsonProperty("idTransaccionFraudulenta")
  private String idTransaccionFraudulenta = null;

  @JsonProperty("codigoFuncionarioAutoriza")
  private String codigoFuncionarioAutoriza = null;

  @JsonProperty("operacion")
  private OperacionTransaccion operacion = null;

  @JsonProperty("montoTotalChequesTransaccion")
  private Double montoTotalChequesTransaccion = null;

  @JsonProperty("montoTotalChequesAjenos")
  private Double montoTotalChequesAjenos = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("ip")
  private String ip = null;

  @JsonProperty("numeroReferencia")
  private String numeroReferencia = null;

  @JsonProperty("codigoTipoPago")
  private String codigoTipoPago = null;

  @JsonProperty("montoTotalEfectivoTransaccion")
  private Double montoTotalEfectivoTransaccion = null;

  @JsonProperty("numeroSequencial")
  private String numeroSequencial = null;

  public Transaccion codigo(String codigo) {
    this.codigo = codigo;
    return this;
  }

  /**
   * DISPEFEC - Código que identifica la Transacción que se esta realizando (Cambio algún dato, consulta, etc.)
   * @return codigo
   **/
  @JsonProperty("codigo")
  @ApiModelProperty(value = "DISPEFEC - Código que identifica la Transacción que se esta realizando (Cambio algún dato, consulta, etc.)")
  public String getCodigo() {
    return codigo;
  }

  public void setCodigo(String codigo) {
    this.codigo = codigo;
  }

  public Transaccion cuentaAsociada(Cuenta cuentaAsociada) {
    this.cuentaAsociada = cuentaAsociada;
    return this;
  }

  /**
   * Get cuentaAsociada
   * @return cuentaAsociada
   **/
  @JsonProperty("cuentaAsociada")
  @ApiModelProperty(value = "")
  public Cuenta getCuentaAsociada() {
    return cuentaAsociada;
  }

  public void setCuentaAsociada(Cuenta cuentaAsociada) {
    this.cuentaAsociada = cuentaAsociada;
  }

  public Transaccion canal(Canal canal) {
    this.canal = canal;
    return this;
  }

  /**
   * Get canal
   * @return canal
   **/
  @JsonProperty("canal")
  @ApiModelProperty(value = "")
  public Canal getCanal() {
    return canal;
  }

  public void setCanal(Canal canal) {
    this.canal = canal;
  }

  public Transaccion chequera(Chequera chequera) {
    this.chequera = chequera;
    return this;
  }

  /**
   * Get chequera
   * @return chequera
   **/
  @JsonProperty("chequera")
  @ApiModelProperty(value = "")
  public Chequera getChequera() {
    return chequera;
  }

  public void setChequera(Chequera chequera) {
    this.chequera = chequera;
  }

  public Transaccion cuentaDestino(Cuenta cuentaDestino) {
    this.cuentaDestino = cuentaDestino;
    return this;
  }

  /**
   * Get cuentaDestino
   * @return cuentaDestino
   **/
  @JsonProperty("cuentaDestino")
  @ApiModelProperty(value = "")
  public Cuenta getCuentaDestino() {
    return cuentaDestino;
  }

  public void setCuentaDestino(Cuenta cuentaDestino) {
    this.cuentaDestino = cuentaDestino;
  }

  public Transaccion cuentaOrigem(Cuenta cuentaOrigem) {
    this.cuentaOrigem = cuentaOrigem;
    return this;
  }

  /**
   * Get cuentaOrigem
   * @return cuentaOrigem
   **/
  @JsonProperty("cuentaOrigem")
  @ApiModelProperty(value = "")
  public Cuenta getCuentaOrigem() {
    return cuentaOrigem;
  }

  public void setCuentaOrigem(Cuenta cuentaOrigem) {
    this.cuentaOrigem = cuentaOrigem;
  }

  public Transaccion montoTotal(Double montoTotal) {
    this.montoTotal = montoTotal;
    return this;
  }

  /**
   * Monto de la disposición
   * @return montoTotal
   **/
  @JsonProperty("montoTotal")
  @ApiModelProperty(value = "Monto de la disposición")
  public Double getMontoTotal() {
    return montoTotal;
  }

  public void setMontoTotal(Double montoTotal) {
    this.montoTotal = montoTotal;
  }

  public Transaccion fecha(Date fecha) {
    this.fecha = fecha;
    return this;
  }

  /**
   * Fecha Transacción
   * @return fecha
   **/
  @JsonProperty("fecha")
  @ApiModelProperty(value = "Fecha Transacción")
  public Date getFecha() {
    return fecha;
  }

  public void setFecha(Date fecha) {
    this.fecha = fecha;
  }

  public Transaccion transaccionReverso(Boolean transaccionReverso) {
    this.transaccionReverso = transaccionReverso;
    return this;
  }

  /**
   * identifica si la transacción es un Reverso
   * @return transaccionReverso
   **/
  @JsonProperty("transaccionReverso")
  @ApiModelProperty(value = "identifica si la transacción es un Reverso")
  public Boolean isTransaccionReverso() {
    return transaccionReverso;
  }

  public void setTransaccionReverso(Boolean transaccionReverso) {
    this.transaccionReverso = transaccionReverso;
  }

  public Transaccion cheque(Cheque cheque) {
    this.cheque = cheque;
    return this;
  }

  /**
   * Get cheque
   * @return cheque
   **/
  @JsonProperty("cheque")
  @ApiModelProperty(value = "")
  public Cheque getCheque() {
    return cheque;
  }

  public void setCheque(Cheque cheque) {
    this.cheque = cheque;
  }

  public Transaccion moneda(CodigosMonedas moneda) {
    this.moneda = moneda;
    return this;
  }

  /**
   * Get moneda
   * @return moneda
   **/
  @JsonProperty("moneda")
  @ApiModelProperty(value = "")
  public CodigosMonedas getMoneda() {
    return moneda;
  }

  public void setMoneda(CodigosMonedas moneda) {
    this.moneda = moneda;
  }

  public Transaccion usuario(Usuario usuario) {
    this.usuario = usuario;
    return this;
  }

  /**
   * Get usuario
   * @return usuario
   **/
  @JsonProperty("usuario")
  @ApiModelProperty(value = "")
  public Usuario getUsuario() {
    return usuario;
  }

  public void setUsuario(Usuario usuario) {
    this.usuario = usuario;
  }

  public Transaccion atmOrigem(Atm atmOrigem) {
    this.atmOrigem = atmOrigem;
    return this;
  }

  /**
   * Get atmOrigem
   * @return atmOrigem
   **/
  @JsonProperty("atmOrigem")
  @ApiModelProperty(value = "")
  public Atm getAtmOrigem() {
    return atmOrigem;
  }

  public void setAtmOrigem(Atm atmOrigem) {
    this.atmOrigem = atmOrigem;
  }

  public Transaccion local(String local) {
    this.local = local;
    return this;
  }

  /**
   * Localidad donde se realizo la Transacción
   * @return local
   **/
  @JsonProperty("local")
  @ApiModelProperty(value = "Localidad donde se realizo la Transacción")
  public String getLocal() {
    return local;
  }

  public void setLocal(String local) {
    this.local = local;
  }

  public Transaccion transaccionFraudulenta(Boolean transaccionFraudulenta) {
    this.transaccionFraudulenta = transaccionFraudulenta;
    return this;
  }

  /**
   * Indica que la Transacción es un Fraude (true&#x3D;fraude false&#x3D;normal)
   * @return transaccionFraudulenta
   **/
  @JsonProperty("transaccionFraudulenta")
  @ApiModelProperty(value = "Indica que la Transacción es un Fraude (true=fraude false=normal)")
  public Boolean isTransaccionFraudulenta() {
    return transaccionFraudulenta;
  }

  public void setTransaccionFraudulenta(Boolean transaccionFraudulenta) {
    this.transaccionFraudulenta = transaccionFraudulenta;
  }

  public Transaccion origemAlertaFraude(BigDecimal origemAlertaFraude) {
    this.origemAlertaFraude = origemAlertaFraude;
    return this;
  }

  /**
   * Indica de donde se origino la Alerta si la Transacción ya fue Marcada como Fraude
   * @return origemAlertaFraude
   **/
  @JsonProperty("origemAlertaFraude")
  @ApiModelProperty(value = "Indica de donde se origino la Alerta si la Transacción ya fue Marcada como Fraude")
  public BigDecimal getOrigemAlertaFraude() {
    return origemAlertaFraude;
  }

  public void setOrigemAlertaFraude(BigDecimal origemAlertaFraude) {
    this.origemAlertaFraude = origemAlertaFraude;
  }

  public Transaccion idTransaccionFraudulenta(String idTransaccionFraudulenta) {
    this.idTransaccionFraudulenta = idTransaccionFraudulenta;
    return this;
  }

  /**
   * Número o Valor de Identificación de la Transacción de Fraude.
   * @return idTransaccionFraudulenta
   **/
  @JsonProperty("idTransaccionFraudulenta")
  @ApiModelProperty(value = "Número o Valor de Identificación de la Transacción de Fraude.")
  public String getIdTransaccionFraudulenta() {
    return idTransaccionFraudulenta;
  }

  public void setIdTransaccionFraudulenta(String idTransaccionFraudulenta) {
    this.idTransaccionFraudulenta = idTransaccionFraudulenta;
  }

  public Transaccion codigoFuncionarioAutoriza(String codigoFuncionarioAutoriza) {
    this.codigoFuncionarioAutoriza = codigoFuncionarioAutoriza;
    return this;
  }

  /**
   * Código de Funcionario o Empleado que Autoriza la Transacción.
   * @return codigoFuncionarioAutoriza
   **/
  @JsonProperty("codigoFuncionarioAutoriza")
  @ApiModelProperty(value = "Código de Funcionario o Empleado que Autoriza la Transacción.")
  public String getCodigoFuncionarioAutoriza() {
    return codigoFuncionarioAutoriza;
  }

  public void setCodigoFuncionarioAutoriza(String codigoFuncionarioAutoriza) {
    this.codigoFuncionarioAutoriza = codigoFuncionarioAutoriza;
  }

  public Transaccion operacion(OperacionTransaccion operacion) {
    this.operacion = operacion;
    return this;
  }

  /**
   * Get operacion
   * @return operacion
   **/
  @JsonProperty("operacion")
  @ApiModelProperty(value = "")
  public OperacionTransaccion getOperacion() {
    return operacion;
  }

  public void setOperacion(OperacionTransaccion operacion) {
    this.operacion = operacion;
  }

  public Transaccion montoTotalChequesTransaccion(Double montoTotalChequesTransaccion) {
    this.montoTotalChequesTransaccion = montoTotalChequesTransaccion;
    return this;
  }

  /**
   * Monto Total en Cheques Propios que fue utilizado en la Transacción
   * @return montoTotalChequesTransaccion
   **/
  @JsonProperty("montoTotalChequesTransaccion")
  @ApiModelProperty(value = "Monto Total en Cheques Propios que fue utilizado en la Transacción")
  public Double getMontoTotalChequesTransaccion() {
    return montoTotalChequesTransaccion;
  }

  public void setMontoTotalChequesTransaccion(Double montoTotalChequesTransaccion) {
    this.montoTotalChequesTransaccion = montoTotalChequesTransaccion;
  }

  public Transaccion montoTotalChequesAjenos(Double montoTotalChequesAjenos) {
    this.montoTotalChequesAjenos = montoTotalChequesAjenos;
    return this;
  }

  /**
   * Monto Total en Cheques de Bancos Ajenos que fue utilizado en la Transacción
   * @return montoTotalChequesAjenos
   **/
  @JsonProperty("montoTotalChequesAjenos")
  @ApiModelProperty(value = "Monto Total en Cheques de Bancos Ajenos que fue utilizado en la Transacción")
  public Double getMontoTotalChequesAjenos() {
    return montoTotalChequesAjenos;
  }

  public void setMontoTotalChequesAjenos(Double montoTotalChequesAjenos) {
    this.montoTotalChequesAjenos = montoTotalChequesAjenos;
  }

  public Transaccion id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Identificación que se genera en una transferencia y sirve para rastrearla a través de los Sistemas.
   * @return id
   **/
  @JsonProperty("id")
  @ApiModelProperty(value = "Identificación que se genera en una transferencia y sirve para rastrearla a través de los Sistemas.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Transaccion ip(String ip) {
    this.ip = ip;
    return this;
  }

  /**
   * Dirección IP del cliente
   * @return ip
   **/
  @JsonProperty("ip")
  @ApiModelProperty(value = "Dirección IP del cliente")
  public String getIp() {
    return ip;
  }

  public void setIp(String ip) {
    this.ip = ip;
  }

  public Transaccion numeroReferencia(String numeroReferencia) {
    this.numeroReferencia = numeroReferencia;
    return this;
  }

  /**
   * Número de operación (respuesta de programa de disposición)
   * @return numeroReferencia
   **/
  @JsonProperty("numeroReferencia")
  @ApiModelProperty(value = "Número de operación (respuesta de programa de disposición)")
  public String getNumeroReferencia() {
    return numeroReferencia;
  }

  public void setNumeroReferencia(String numeroReferencia) {
    this.numeroReferencia = numeroReferencia;
  }

  public Transaccion codigoTipoPago(String codigoTipoPago) {
    this.codigoTipoPago = codigoTipoPago;
    return this;
  }

  /**
   * Código de Tipo de Pago de Servicio que se esta realizando en la Transacción (Pago Luz, Agua, Tel. Celular, etc.)
   * @return codigoTipoPago
   **/
  @JsonProperty("codigoTipoPago")
  @ApiModelProperty(value = "Código de Tipo de Pago de Servicio que se esta realizando en la Transacción (Pago Luz, Agua, Tel. Celular, etc.)")
  public String getCodigoTipoPago() {
    return codigoTipoPago;
  }

  public void setCodigoTipoPago(String codigoTipoPago) {
    this.codigoTipoPago = codigoTipoPago;
  }

  public Transaccion montoTotalEfectivoTransaccion(Double montoTotalEfectivoTransaccion) {
    this.montoTotalEfectivoTransaccion = montoTotalEfectivoTransaccion;
    return this;
  }

  /**
   * Monto Total de la transaccion
   * @return montoTotalEfectivoTransaccion
   **/
  @JsonProperty("montoTotalEfectivoTransaccion")
  @ApiModelProperty(value = "Monto Total de la transaccion")
  public Double getMontoTotalEfectivoTransaccion() {
    return montoTotalEfectivoTransaccion;
  }

  public void setMontoTotalEfectivoTransaccion(Double montoTotalEfectivoTransaccion) {
    this.montoTotalEfectivoTransaccion = montoTotalEfectivoTransaccion;
  }

  public Transaccion numeroSequencial(String numeroSequencial) {
    this.numeroSequencial = numeroSequencial;
    return this;
  }

  /**
   * Numero secuencial generado por la transaccion
   * @return numeroSequencial
   **/
  @JsonProperty("numeroSequencial")
  @ApiModelProperty(value = "Numero secuencial generado por la transaccion")
  public String getNumeroSequencial() {
    return numeroSequencial;
  }

  public void setNumeroSequencial(String numeroSequencial) {
    this.numeroSequencial = numeroSequencial;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transaccion transaccion = (Transaccion) o;
    return Objects.equals(this.codigo, transaccion.codigo) &&
        Objects.equals(this.cuentaAsociada, transaccion.cuentaAsociada) &&
        Objects.equals(this.canal, transaccion.canal) &&
        Objects.equals(this.chequera, transaccion.chequera) &&
        Objects.equals(this.cuentaDestino, transaccion.cuentaDestino) &&
        Objects.equals(this.cuentaOrigem, transaccion.cuentaOrigem) &&
        Objects.equals(this.montoTotal, transaccion.montoTotal) &&
        Objects.equals(this.fecha, transaccion.fecha) &&
        Objects.equals(this.transaccionReverso, transaccion.transaccionReverso) &&
        Objects.equals(this.cheque, transaccion.cheque) &&
        Objects.equals(this.moneda, transaccion.moneda) &&
        Objects.equals(this.usuario, transaccion.usuario) &&
        Objects.equals(this.atmOrigem, transaccion.atmOrigem) &&
        Objects.equals(this.local, transaccion.local) &&
        Objects.equals(this.transaccionFraudulenta, transaccion.transaccionFraudulenta) &&
        Objects.equals(this.origemAlertaFraude, transaccion.origemAlertaFraude) &&
        Objects.equals(this.idTransaccionFraudulenta, transaccion.idTransaccionFraudulenta) &&
        Objects.equals(this.codigoFuncionarioAutoriza, transaccion.codigoFuncionarioAutoriza) &&
        Objects.equals(this.operacion, transaccion.operacion) &&
        Objects.equals(this.montoTotalChequesTransaccion, transaccion.montoTotalChequesTransaccion) &&
        Objects.equals(this.montoTotalChequesAjenos, transaccion.montoTotalChequesAjenos) &&
        Objects.equals(this.id, transaccion.id) &&
        Objects.equals(this.ip, transaccion.ip) &&
        Objects.equals(this.numeroReferencia, transaccion.numeroReferencia) &&
        Objects.equals(this.codigoTipoPago, transaccion.codigoTipoPago) &&
        Objects.equals(this.montoTotalEfectivoTransaccion, transaccion.montoTotalEfectivoTransaccion) &&
        Objects.equals(this.numeroSequencial, transaccion.numeroSequencial);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codigo, cuentaAsociada, canal, chequera, cuentaDestino, cuentaOrigem, montoTotal, fecha, transaccionReverso, cheque, moneda, usuario, atmOrigem, local, transaccionFraudulenta, origemAlertaFraude, idTransaccionFraudulenta, codigoFuncionarioAutoriza, operacion, montoTotalChequesTransaccion, montoTotalChequesAjenos, id, ip, numeroReferencia, codigoTipoPago, montoTotalEfectivoTransaccion, numeroSequencial);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transaccion {\n");
    
    sb.append("    codigo: ").append(toIndentedString(codigo)).append("\n");
    sb.append("    cuentaAsociada: ").append(toIndentedString(cuentaAsociada)).append("\n");
    sb.append("    canal: ").append(toIndentedString(canal)).append("\n");
    sb.append("    chequera: ").append(toIndentedString(chequera)).append("\n");
    sb.append("    cuentaDestino: ").append(toIndentedString(cuentaDestino)).append("\n");
    sb.append("    cuentaOrigem: ").append(toIndentedString(cuentaOrigem)).append("\n");
    sb.append("    montoTotal: ").append(toIndentedString(montoTotal)).append("\n");
    sb.append("    fecha: ").append(toIndentedString(fecha)).append("\n");
    sb.append("    transaccionReverso: ").append(toIndentedString(transaccionReverso)).append("\n");
    sb.append("    cheque: ").append(toIndentedString(cheque)).append("\n");
    sb.append("    moneda: ").append(toIndentedString(moneda)).append("\n");
    sb.append("    usuario: ").append(toIndentedString(usuario)).append("\n");
    sb.append("    atmOrigem: ").append(toIndentedString(atmOrigem)).append("\n");
    sb.append("    local: ").append(toIndentedString(local)).append("\n");
    sb.append("    transaccionFraudulenta: ").append(toIndentedString(transaccionFraudulenta)).append("\n");
    sb.append("    origemAlertaFraude: ").append(toIndentedString(origemAlertaFraude)).append("\n");
    sb.append("    idTransaccionFraudulenta: ").append(toIndentedString(idTransaccionFraudulenta)).append("\n");
    sb.append("    codigoFuncionarioAutoriza: ").append(toIndentedString(codigoFuncionarioAutoriza)).append("\n");
    sb.append("    operacion: ").append(toIndentedString(operacion)).append("\n");
    sb.append("    montoTotalChequesTransaccion: ").append(toIndentedString(montoTotalChequesTransaccion)).append("\n");
    sb.append("    montoTotalChequesAjenos: ").append(toIndentedString(montoTotalChequesAjenos)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("    numeroReferencia: ").append(toIndentedString(numeroReferencia)).append("\n");
    sb.append("    codigoTipoPago: ").append(toIndentedString(codigoTipoPago)).append("\n");
    sb.append("    montoTotalEfectivoTransaccion: ").append(toIndentedString(montoTotalEfectivoTransaccion)).append("\n");
    sb.append("    numeroSequencial: ").append(toIndentedString(numeroSequencial)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

