/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * ValorTag
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class ValorTag   {
  @JsonProperty("correo")
  private Correo correo = null;

  @JsonProperty("tag")
  private TagCorreo tag = null;

  @JsonProperty("valor")
  private String valor = null;

  public ValorTag correo(Correo correo) {
    this.correo = correo;
    return this;
  }

  /**
   * Get correo
   * @return correo
   **/
  @JsonProperty("correo")
  @ApiModelProperty(value = "")
  public Correo getCorreo() {
    return correo;
  }

  public void setCorreo(Correo correo) {
    this.correo = correo;
  }

  public ValorTag tag(TagCorreo tag) {
    this.tag = tag;
    return this;
  }

  /**
   * Get tag
   * @return tag
   **/
  @JsonProperty("tag")
  @ApiModelProperty(value = "")
  public TagCorreo getTag() {
    return tag;
  }

  public void setTag(TagCorreo tag) {
    this.tag = tag;
  }

  public ValorTag valor(String valor) {
    this.valor = valor;
    return this;
  }

  /**
   * Que se enviará por correo electrónico
   * @return valor
   **/
  @JsonProperty("valor")
  @ApiModelProperty(value = "Que se enviará por correo electrónico")
  public String getValor() {
    return valor;
  }

  public void setValor(String valor) {
    this.valor = valor;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValorTag valorTag = (ValorTag) o;
    return Objects.equals(this.correo, valorTag.correo) &&
        Objects.equals(this.tag, valorTag.tag) &&
        Objects.equals(this.valor, valorTag.valor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(correo, tag, valor);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValorTag {\n");
    
    sb.append("    correo: ").append(toIndentedString(correo)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

