/*
 * BanBif - API
 * API de BanBif
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pe.com.banbif.correo.eletronico.service.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Objects;

/**
 * Voucher
 */
@ApiModel(description = "Voucher")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-02T12:18:15.278Z")
public class Voucher   {
  @JsonProperty("numeroSecuencia")
  private BigDecimal numeroSecuencia = null;

  @JsonProperty("fechaHoraProceso")
  private String fechaHoraProceso = null;

  @JsonProperty("deudaTotal")
  private BigDecimal deudaTotal = null;

  @JsonProperty("fechaVencimiento")
  private Date fechaVencimiento = null;

  @JsonProperty("numeroCuotasPagadas")
  private BigDecimal numeroCuotasPagadas = null;

  @JsonProperty("montoCapital")
  private BigDecimal montoCapital = null;

  @JsonProperty("interesCorriente")
  private BigDecimal interesCorriente = null;

  @JsonProperty("interesMoratorio")
  private BigDecimal interesMoratorio = null;

  @JsonProperty("montoSeguro")
  private BigDecimal montoSeguro = null;

  @JsonProperty("montoComision")
  private BigDecimal montoComision = null;

  @JsonProperty("montoComisionPJ")
  private BigDecimal montoComisionPJ = null;

  @JsonProperty("montoItf")
  private BigDecimal montoItf = null;

  @JsonProperty("montoPagoAnticipado")
  private BigDecimal montoPagoAnticipado = null;

  @JsonProperty("montoTotalCuotas")
  private BigDecimal montoTotalCuotas = null;

  @JsonProperty("cuentaCargo")
  private BigDecimal cuentaCargo = null;

  @JsonProperty("montoCargado")
  private BigDecimal montoCargado = null;

  @JsonProperty("tipoCambio")
  private BigDecimal tipoCambio = null;

  @JsonProperty("numeroPreliquidacion")
  private BigDecimal numeroPreliquidacion = null;

  @JsonProperty("totalPagar")
  private BigDecimal totalPagar = null;

  @JsonProperty("itf1")
  private BigDecimal itf1 = null;

  @JsonProperty("itf2")
  private BigDecimal itf2 = null;

  @JsonProperty("montoTotalCuota")
  private BigDecimal montoTotalCuota = null;

  @JsonProperty("totalCancelado")
  private BigDecimal totalCancelado = null;

  @JsonProperty("montoPagoParcial")
  private BigDecimal montoPagoParcial = null;

  @JsonProperty("oficina")
  private Oficina oficina = null;

  @JsonProperty("cliente")
  private Cliente cliente = null;

  @JsonProperty("pago")
  private Pago pago = null;

  public Voucher numeroSecuencia(BigDecimal numeroSecuencia) {
    this.numeroSecuencia = numeroSecuencia;
    return this;
  }

  /**
   * Nro de Secuencia
   * @return numeroSecuencia
   **/
  @JsonProperty("numeroSecuencia")
  @ApiModelProperty(value = "Nro de Secuencia")
  public BigDecimal getNumeroSecuencia() {
    return numeroSecuencia;
  }

  public void setNumeroSecuencia(BigDecimal numeroSecuencia) {
    this.numeroSecuencia = numeroSecuencia;
  }

  public Voucher fechaHoraProceso(String fechaHoraProceso) {
    this.fechaHoraProceso = fechaHoraProceso;
    return this;
  }

  /**
   * Fecha y hora de proceso
   * @return fechaHoraProceso
   **/
  @JsonProperty("fechaHoraProceso")
  @ApiModelProperty(value = "Fecha y hora de proceso")
  public String getFechaHoraProceso() {
    return fechaHoraProceso;
  }

  public void setFechaHoraProceso(String fechaHoraProceso) {
    this.fechaHoraProceso = fechaHoraProceso;
  }

  public Voucher deudaTotal(BigDecimal deudaTotal) {
    this.deudaTotal = deudaTotal;
    return this;
  }

  /**
   * Deuda Total
   * @return deudaTotal
   **/
  @JsonProperty("deudaTotal")
  @ApiModelProperty(value = "Deuda Total")
  public BigDecimal getDeudaTotal() {
    return deudaTotal;
  }

  public void setDeudaTotal(BigDecimal deudaTotal) {
    this.deudaTotal = deudaTotal;
  }

  public Voucher fechaVencimiento(Date fechaVencimiento) {
    this.fechaVencimiento = fechaVencimiento;
    return this;
  }

  /**
   * Fecha de Vencimiento
   * @return fechaVencimiento
   **/
  @JsonProperty("fechaVencimiento")
  @ApiModelProperty(value = "Fecha de Vencimiento")
  public Date getFechaVencimiento() {
    return fechaVencimiento;
  }

  public void setFechaVencimiento(Date fechaVencimiento) {
    this.fechaVencimiento = fechaVencimiento;
  }

  public Voucher numeroCuotasPagadas(BigDecimal numeroCuotasPagadas) {
    this.numeroCuotasPagadas = numeroCuotasPagadas;
    return this;
  }

  /**
   * Número de cuotas Pagadas
   * @return numeroCuotasPagadas
   **/
  @JsonProperty("numeroCuotasPagadas")
  @ApiModelProperty(value = "Número de cuotas Pagadas")
  public BigDecimal getNumeroCuotasPagadas() {
    return numeroCuotasPagadas;
  }

  public void setNumeroCuotasPagadas(BigDecimal numeroCuotasPagadas) {
    this.numeroCuotasPagadas = numeroCuotasPagadas;
  }

  public Voucher montoCapital(BigDecimal montoCapital) {
    this.montoCapital = montoCapital;
    return this;
  }

  /**
   * Monto Capital
   * @return montoCapital
   **/
  @JsonProperty("montoCapital")
  @ApiModelProperty(value = "Monto Capital")
  public BigDecimal getMontoCapital() {
    return montoCapital;
  }

  public void setMontoCapital(BigDecimal montoCapital) {
    this.montoCapital = montoCapital;
  }

  public Voucher interesCorriente(BigDecimal interesCorriente) {
    this.interesCorriente = interesCorriente;
    return this;
  }

  /**
   * Interés Corriente
   * @return interesCorriente
   **/
  @JsonProperty("interesCorriente")
  @ApiModelProperty(value = "Interés Corriente")
  public BigDecimal getInteresCorriente() {
    return interesCorriente;
  }

  public void setInteresCorriente(BigDecimal interesCorriente) {
    this.interesCorriente = interesCorriente;
  }

  public Voucher interesMoratorio(BigDecimal interesMoratorio) {
    this.interesMoratorio = interesMoratorio;
    return this;
  }

  /**
   * Interés Moratorio
   * @return interesMoratorio
   **/
  @JsonProperty("interesMoratorio")
  @ApiModelProperty(value = "Interés Moratorio")
  public BigDecimal getInteresMoratorio() {
    return interesMoratorio;
  }

  public void setInteresMoratorio(BigDecimal interesMoratorio) {
    this.interesMoratorio = interesMoratorio;
  }

  public Voucher montoSeguro(BigDecimal montoSeguro) {
    this.montoSeguro = montoSeguro;
    return this;
  }

  /**
   * Monto Seguro
   * @return montoSeguro
   **/
  @JsonProperty("montoSeguro")
  @ApiModelProperty(value = "Monto Seguro")
  public BigDecimal getMontoSeguro() {
    return montoSeguro;
  }

  public void setMontoSeguro(BigDecimal montoSeguro) {
    this.montoSeguro = montoSeguro;
  }

  public Voucher montoComision(BigDecimal montoComision) {
    this.montoComision = montoComision;
    return this;
  }

  /**
   * Monto Comisión
   * @return montoComision
   **/
  @JsonProperty("montoComision")
  @ApiModelProperty(value = "Monto Comisión")
  public BigDecimal getMontoComision() {
    return montoComision;
  }

  public void setMontoComision(BigDecimal montoComision) {
    this.montoComision = montoComision;
  }

  public Voucher montoComisionPJ(BigDecimal montoComisionPJ) {
    this.montoComisionPJ = montoComisionPJ;
    return this;
  }

  /**
   * Monto Comisión PJ
   * @return montoComisionPJ
   **/
  @JsonProperty("montoComisionPJ")
  @ApiModelProperty(value = "Monto Comisión PJ")
  public BigDecimal getMontoComisionPJ() {
    return montoComisionPJ;
  }

  public void setMontoComisionPJ(BigDecimal montoComisionPJ) {
    this.montoComisionPJ = montoComisionPJ;
  }

  public Voucher montoItf(BigDecimal montoItf) {
    this.montoItf = montoItf;
    return this;
  }

  /**
   * Monto ITF
   * @return montoItf
   **/
  @JsonProperty("montoItf")
  @ApiModelProperty(value = "Monto ITF")
  public BigDecimal getMontoItf() {
    return montoItf;
  }

  public void setMontoItf(BigDecimal montoItf) {
    this.montoItf = montoItf;
  }

  public Voucher montoPagoAnticipado(BigDecimal montoPagoAnticipado) {
    this.montoPagoAnticipado = montoPagoAnticipado;
    return this;
  }

  /**
   * Monto Pago Anticipado
   * @return montoPagoAnticipado
   **/
  @JsonProperty("montoPagoAnticipado")
  @ApiModelProperty(value = "Monto Pago Anticipado")
  public BigDecimal getMontoPagoAnticipado() {
    return montoPagoAnticipado;
  }

  public void setMontoPagoAnticipado(BigDecimal montoPagoAnticipado) {
    this.montoPagoAnticipado = montoPagoAnticipado;
  }

  public Voucher montoTotalCuotas(BigDecimal montoTotalCuotas) {
    this.montoTotalCuotas = montoTotalCuotas;
    return this;
  }

  /**
   * Monto Total Cuotas
   * @return montoTotalCuotas
   **/
  @JsonProperty("montoTotalCuotas")
  @ApiModelProperty(value = "Monto Total Cuotas")
  public BigDecimal getMontoTotalCuotas() {
    return montoTotalCuotas;
  }

  public void setMontoTotalCuotas(BigDecimal montoTotalCuotas) {
    this.montoTotalCuotas = montoTotalCuotas;
  }

  public Voucher cuentaCargo(BigDecimal cuentaCargo) {
    this.cuentaCargo = cuentaCargo;
    return this;
  }

  /**
   * Cuenta de Cargo
   * @return cuentaCargo
   **/
  @JsonProperty("cuentaCargo")
  @ApiModelProperty(value = "Cuenta de Cargo")
  public BigDecimal getCuentaCargo() {
    return cuentaCargo;
  }

  public void setCuentaCargo(BigDecimal cuentaCargo) {
    this.cuentaCargo = cuentaCargo;
  }

  public Voucher montoCargado(BigDecimal montoCargado) {
    this.montoCargado = montoCargado;
    return this;
  }

  /**
   * Monto cargado
   * @return montoCargado
   **/
  @JsonProperty("montoCargado")
  @ApiModelProperty(value = "Monto cargado")
  public BigDecimal getMontoCargado() {
    return montoCargado;
  }

  public void setMontoCargado(BigDecimal montoCargado) {
    this.montoCargado = montoCargado;
  }

  public Voucher tipoCambio(BigDecimal tipoCambio) {
    this.tipoCambio = tipoCambio;
    return this;
  }

  /**
   * Tipo de Cambio
   * @return tipoCambio
   **/
  @JsonProperty("tipoCambio")
  @ApiModelProperty(value = "Tipo de Cambio")
  public BigDecimal getTipoCambio() {
    return tipoCambio;
  }

  public void setTipoCambio(BigDecimal tipoCambio) {
    this.tipoCambio = tipoCambio;
  }

  public Voucher numeroPreliquidacion(BigDecimal numeroPreliquidacion) {
    this.numeroPreliquidacion = numeroPreliquidacion;
    return this;
  }

  /**
   * Nro de Preliquidación
   * @return numeroPreliquidacion
   **/
  @JsonProperty("numeroPreliquidacion")
  @ApiModelProperty(value = "Nro de Preliquidación")
  public BigDecimal getNumeroPreliquidacion() {
    return numeroPreliquidacion;
  }

  public void setNumeroPreliquidacion(BigDecimal numeroPreliquidacion) {
    this.numeroPreliquidacion = numeroPreliquidacion;
  }

  public Voucher totalPagar(BigDecimal totalPagar) {
    this.totalPagar = totalPagar;
    return this;
  }

  /**
   * Total a pagar
   * @return totalPagar
   **/
  @JsonProperty("totalPagar")
  @ApiModelProperty(value = "Total a pagar")
  public BigDecimal getTotalPagar() {
    return totalPagar;
  }

  public void setTotalPagar(BigDecimal totalPagar) {
    this.totalPagar = totalPagar;
  }

  public Voucher itf1(BigDecimal itf1) {
    this.itf1 = itf1;
    return this;
  }

  /**
   * ITF 1
   * @return itf1
   **/
  @JsonProperty("itf1")
  @ApiModelProperty(value = "ITF 1")
  public BigDecimal getItf1() {
    return itf1;
  }

  public void setItf1(BigDecimal itf1) {
    this.itf1 = itf1;
  }

  public Voucher itf2(BigDecimal itf2) {
    this.itf2 = itf2;
    return this;
  }

  /**
   * ITF 2
   * @return itf2
   **/
  @JsonProperty("itf2")
  @ApiModelProperty(value = "ITF 2")
  public BigDecimal getItf2() {
    return itf2;
  }

  public void setItf2(BigDecimal itf2) {
    this.itf2 = itf2;
  }

  public Voucher montoTotalCuota(BigDecimal montoTotalCuota) {
    this.montoTotalCuota = montoTotalCuota;
    return this;
  }

  /**
   * Monto Total Cuota
   * @return montoTotalCuota
   **/
  @JsonProperty("montoTotalCuota")
  @ApiModelProperty(value = "Monto Total Cuota")
  public BigDecimal getMontoTotalCuota() {
    return montoTotalCuota;
  }

  public void setMontoTotalCuota(BigDecimal montoTotalCuota) {
    this.montoTotalCuota = montoTotalCuota;
  }

  public Voucher totalCancelado(BigDecimal totalCancelado) {
    this.totalCancelado = totalCancelado;
    return this;
  }

  /**
   * Total Cancelado
   * @return totalCancelado
   **/
  @JsonProperty("totalCancelado")
  @ApiModelProperty(value = "Total Cancelado")
  public BigDecimal getTotalCancelado() {
    return totalCancelado;
  }

  public void setTotalCancelado(BigDecimal totalCancelado) {
    this.totalCancelado = totalCancelado;
  }

  public Voucher montoPagoParcial(BigDecimal montoPagoParcial) {
    this.montoPagoParcial = montoPagoParcial;
    return this;
  }

  /**
   * Monto Pago Parcial
   * @return montoPagoParcial
   **/
  @JsonProperty("montoPagoParcial")
  @ApiModelProperty(value = "Monto Pago Parcial")
  public BigDecimal getMontoPagoParcial() {
    return montoPagoParcial;
  }

  public void setMontoPagoParcial(BigDecimal montoPagoParcial) {
    this.montoPagoParcial = montoPagoParcial;
  }

  public Voucher oficina(Oficina oficina) {
    this.oficina = oficina;
    return this;
  }

  /**
   * Get oficina
   * @return oficina
   **/
  @JsonProperty("oficina")
  @ApiModelProperty(value = "")
  public Oficina getOficina() {
    return oficina;
  }

  public void setOficina(Oficina oficina) {
    this.oficina = oficina;
  }

  public Voucher cliente(Cliente cliente) {
    this.cliente = cliente;
    return this;
  }

  /**
   * Get cliente
   * @return cliente
   **/
  @JsonProperty("cliente")
  @ApiModelProperty(value = "")
  public Cliente getCliente() {
    return cliente;
  }

  public void setCliente(Cliente cliente) {
    this.cliente = cliente;
  }

  public Voucher pago(Pago pago) {
    this.pago = pago;
    return this;
  }

  /**
   * Get pago
   * @return pago
   **/
  @JsonProperty("pago")
  @ApiModelProperty(value = "")
  public Pago getPago() {
    return pago;
  }

  public void setPago(Pago pago) {
    this.pago = pago;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Voucher voucher = (Voucher) o;
    return Objects.equals(this.numeroSecuencia, voucher.numeroSecuencia) &&
        Objects.equals(this.fechaHoraProceso, voucher.fechaHoraProceso) &&
        Objects.equals(this.deudaTotal, voucher.deudaTotal) &&
        Objects.equals(this.fechaVencimiento, voucher.fechaVencimiento) &&
        Objects.equals(this.numeroCuotasPagadas, voucher.numeroCuotasPagadas) &&
        Objects.equals(this.montoCapital, voucher.montoCapital) &&
        Objects.equals(this.interesCorriente, voucher.interesCorriente) &&
        Objects.equals(this.interesMoratorio, voucher.interesMoratorio) &&
        Objects.equals(this.montoSeguro, voucher.montoSeguro) &&
        Objects.equals(this.montoComision, voucher.montoComision) &&
        Objects.equals(this.montoComisionPJ, voucher.montoComisionPJ) &&
        Objects.equals(this.montoItf, voucher.montoItf) &&
        Objects.equals(this.montoPagoAnticipado, voucher.montoPagoAnticipado) &&
        Objects.equals(this.montoTotalCuotas, voucher.montoTotalCuotas) &&
        Objects.equals(this.cuentaCargo, voucher.cuentaCargo) &&
        Objects.equals(this.montoCargado, voucher.montoCargado) &&
        Objects.equals(this.tipoCambio, voucher.tipoCambio) &&
        Objects.equals(this.numeroPreliquidacion, voucher.numeroPreliquidacion) &&
        Objects.equals(this.totalPagar, voucher.totalPagar) &&
        Objects.equals(this.itf1, voucher.itf1) &&
        Objects.equals(this.itf2, voucher.itf2) &&
        Objects.equals(this.montoTotalCuota, voucher.montoTotalCuota) &&
        Objects.equals(this.totalCancelado, voucher.totalCancelado) &&
        Objects.equals(this.montoPagoParcial, voucher.montoPagoParcial) &&
        Objects.equals(this.oficina, voucher.oficina) &&
        Objects.equals(this.cliente, voucher.cliente) &&
        Objects.equals(this.pago, voucher.pago);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroSecuencia, fechaHoraProceso, deudaTotal, fechaVencimiento, numeroCuotasPagadas, montoCapital, interesCorriente, interesMoratorio, montoSeguro, montoComision, montoComisionPJ, montoItf, montoPagoAnticipado, montoTotalCuotas, cuentaCargo, montoCargado, tipoCambio, numeroPreliquidacion, totalPagar, itf1, itf2, montoTotalCuota, totalCancelado, montoPagoParcial, oficina, cliente, pago);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Voucher {\n");
    
    sb.append("    numeroSecuencia: ").append(toIndentedString(numeroSecuencia)).append("\n");
    sb.append("    fechaHoraProceso: ").append(toIndentedString(fechaHoraProceso)).append("\n");
    sb.append("    deudaTotal: ").append(toIndentedString(deudaTotal)).append("\n");
    sb.append("    fechaVencimiento: ").append(toIndentedString(fechaVencimiento)).append("\n");
    sb.append("    numeroCuotasPagadas: ").append(toIndentedString(numeroCuotasPagadas)).append("\n");
    sb.append("    montoCapital: ").append(toIndentedString(montoCapital)).append("\n");
    sb.append("    interesCorriente: ").append(toIndentedString(interesCorriente)).append("\n");
    sb.append("    interesMoratorio: ").append(toIndentedString(interesMoratorio)).append("\n");
    sb.append("    montoSeguro: ").append(toIndentedString(montoSeguro)).append("\n");
    sb.append("    montoComision: ").append(toIndentedString(montoComision)).append("\n");
    sb.append("    montoComisionPJ: ").append(toIndentedString(montoComisionPJ)).append("\n");
    sb.append("    montoItf: ").append(toIndentedString(montoItf)).append("\n");
    sb.append("    montoPagoAnticipado: ").append(toIndentedString(montoPagoAnticipado)).append("\n");
    sb.append("    montoTotalCuotas: ").append(toIndentedString(montoTotalCuotas)).append("\n");
    sb.append("    cuentaCargo: ").append(toIndentedString(cuentaCargo)).append("\n");
    sb.append("    montoCargado: ").append(toIndentedString(montoCargado)).append("\n");
    sb.append("    tipoCambio: ").append(toIndentedString(tipoCambio)).append("\n");
    sb.append("    numeroPreliquidacion: ").append(toIndentedString(numeroPreliquidacion)).append("\n");
    sb.append("    totalPagar: ").append(toIndentedString(totalPagar)).append("\n");
    sb.append("    itf1: ").append(toIndentedString(itf1)).append("\n");
    sb.append("    itf2: ").append(toIndentedString(itf2)).append("\n");
    sb.append("    montoTotalCuota: ").append(toIndentedString(montoTotalCuota)).append("\n");
    sb.append("    totalCancelado: ").append(toIndentedString(totalCancelado)).append("\n");
    sb.append("    montoPagoParcial: ").append(toIndentedString(montoPagoParcial)).append("\n");
    sb.append("    oficina: ").append(toIndentedString(oficina)).append("\n");
    sb.append("    cliente: ").append(toIndentedString(cliente)).append("\n");
    sb.append("    pago: ").append(toIndentedString(pago)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

